/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.Fbt.V202408;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * GetFBTWarehouseListResponseDataWarehousesLogisticsServices
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-30T06:06:20.240402Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GetFBTWarehouseListResponseDataWarehousesLogisticsServices {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUBSCRIBED = "subscribed";
  @SerializedName(SERIALIZED_NAME_SUBSCRIBED)
  private Boolean subscribed;

  public GetFBTWarehouseListResponseDataWarehousesLogisticsServices() {
  }

  public GetFBTWarehouseListResponseDataWarehousesLogisticsServices id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier for logistics service in TikTok Shop system.
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public GetFBTWarehouseListResponseDataWarehousesLogisticsServices name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The logistics service name.
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public GetFBTWarehouseListResponseDataWarehousesLogisticsServices subscribed(Boolean subscribed) {
    this.subscribed = subscribed;
    return this;
  }

   /**
   * A flag indicating whether the logistic service is subscribed. True: Subscribed. False: Not subscribed.
   * @return subscribed
  **/
  @javax.annotation.Nullable
  public Boolean getSubscribed() {
    return subscribed;
  }

  public void setSubscribed(Boolean subscribed) {
    this.subscribed = subscribed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFBTWarehouseListResponseDataWarehousesLogisticsServices fbt202408GetFBTWarehouseListResponseDataWarehousesLogisticsServices = (GetFBTWarehouseListResponseDataWarehousesLogisticsServices) o;
    return Objects.equals(this.id, fbt202408GetFBTWarehouseListResponseDataWarehousesLogisticsServices.id) &&
        Objects.equals(this.name, fbt202408GetFBTWarehouseListResponseDataWarehousesLogisticsServices.name) &&
        Objects.equals(this.subscribed, fbt202408GetFBTWarehouseListResponseDataWarehousesLogisticsServices.subscribed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, subscribed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFBTWarehouseListResponseDataWarehousesLogisticsServices {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    subscribed: ").append(toIndentedString(subscribed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("subscribed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GetFBTWarehouseListResponseDataWarehousesLogisticsServices
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetFBTWarehouseListResponseDataWarehousesLogisticsServices.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetFBTWarehouseListResponseDataWarehousesLogisticsServices is not found in the empty JSON string", GetFBTWarehouseListResponseDataWarehousesLogisticsServices.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetFBTWarehouseListResponseDataWarehousesLogisticsServices.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetFBTWarehouseListResponseDataWarehousesLogisticsServices` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetFBTWarehouseListResponseDataWarehousesLogisticsServices.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetFBTWarehouseListResponseDataWarehousesLogisticsServices' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetFBTWarehouseListResponseDataWarehousesLogisticsServices> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetFBTWarehouseListResponseDataWarehousesLogisticsServices.class));

       return (TypeAdapter<T>) new TypeAdapter<GetFBTWarehouseListResponseDataWarehousesLogisticsServices>() {
           @Override
           public void write(JsonWriter out, GetFBTWarehouseListResponseDataWarehousesLogisticsServices value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetFBTWarehouseListResponseDataWarehousesLogisticsServices read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetFBTWarehouseListResponseDataWarehousesLogisticsServices given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetFBTWarehouseListResponseDataWarehousesLogisticsServices
  * @throws IOException if the JSON string is invalid with respect to GetFBTWarehouseListResponseDataWarehousesLogisticsServices
  */
  public static GetFBTWarehouseListResponseDataWarehousesLogisticsServices fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetFBTWarehouseListResponseDataWarehousesLogisticsServices.class);
  }

 /**
  * Convert an instance of GetFBTWarehouseListResponseDataWarehousesLogisticsServices to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

