/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.Fulfillment.V202309;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * BatchShipPackagesRequestBodyPackagesSelfShipment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-30T06:06:20.240402Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class BatchShipPackagesRequestBodyPackagesSelfShipment {
  public static final String SERIALIZED_NAME_SHIPPING_PROVIDER_ID = "shipping_provider_id";
  @SerializedName(SERIALIZED_NAME_SHIPPING_PROVIDER_ID)
  private String shippingProviderId;

  public static final String SERIALIZED_NAME_TRACKING_NUMBER = "tracking_number";
  @SerializedName(SERIALIZED_NAME_TRACKING_NUMBER)
  private String trackingNumber;

  public BatchShipPackagesRequestBodyPackagesSelfShipment() {
  }

  public BatchShipPackagesRequestBodyPackagesSelfShipment shippingProviderId(String shippingProviderId) {
    this.shippingProviderId = shippingProviderId;
    return this;
  }

   /**
   * For packages with the &#x60;SEND_BY_SELLER&#x60; delivery option type (seller shipping), you must provide the shipping provider information. Please use the [Get Shipping Providers](https://partner.tiktokshop.com/docv2/page/650aa48d4a0bb702c06d85cd?external_id&#x3D;650aa48d4a0bb702c06d85cd#Back%20To%20Top) API to obtain the &#x60;shipping_provider_id&#x60;.
   * @return shippingProviderId
  **/
  @javax.annotation.Nullable
  public String getShippingProviderId() {
    return shippingProviderId;
  }

  public void setShippingProviderId(String shippingProviderId) {
    this.shippingProviderId = shippingProviderId;
  }


  public BatchShipPackagesRequestBodyPackagesSelfShipment trackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

   /**
   * For packages with the &#x60;SEND_BY_SELLER&#x60; delivery option type (seller shipping), you must provide the package&#39;s tracking number.
   * @return trackingNumber
  **/
  @javax.annotation.Nullable
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchShipPackagesRequestBodyPackagesSelfShipment fulfillment202309BatchShipPackagesRequestBodyPackagesSelfShipment = (BatchShipPackagesRequestBodyPackagesSelfShipment) o;
    return Objects.equals(this.shippingProviderId, fulfillment202309BatchShipPackagesRequestBodyPackagesSelfShipment.shippingProviderId) &&
        Objects.equals(this.trackingNumber, fulfillment202309BatchShipPackagesRequestBodyPackagesSelfShipment.trackingNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shippingProviderId, trackingNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchShipPackagesRequestBodyPackagesSelfShipment {\n");
    sb.append("    shippingProviderId: ").append(toIndentedString(shippingProviderId)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("shipping_provider_id");
    openapiFields.add("tracking_number");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BatchShipPackagesRequestBodyPackagesSelfShipment
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchShipPackagesRequestBodyPackagesSelfShipment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BatchShipPackagesRequestBodyPackagesSelfShipment is not found in the empty JSON string", BatchShipPackagesRequestBodyPackagesSelfShipment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchShipPackagesRequestBodyPackagesSelfShipment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BatchShipPackagesRequestBodyPackagesSelfShipment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("shipping_provider_id") != null && !jsonObj.get("shipping_provider_id").isJsonNull()) && !jsonObj.get("shipping_provider_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipping_provider_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipping_provider_id").toString()));
      }
      if ((jsonObj.get("tracking_number") != null && !jsonObj.get("tracking_number").isJsonNull()) && !jsonObj.get("tracking_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tracking_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tracking_number").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchShipPackagesRequestBodyPackagesSelfShipment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchShipPackagesRequestBodyPackagesSelfShipment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchShipPackagesRequestBodyPackagesSelfShipment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchShipPackagesRequestBodyPackagesSelfShipment.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchShipPackagesRequestBodyPackagesSelfShipment>() {
           @Override
           public void write(JsonWriter out, BatchShipPackagesRequestBodyPackagesSelfShipment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchShipPackagesRequestBodyPackagesSelfShipment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BatchShipPackagesRequestBodyPackagesSelfShipment given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BatchShipPackagesRequestBodyPackagesSelfShipment
  * @throws IOException if the JSON string is invalid with respect to BatchShipPackagesRequestBodyPackagesSelfShipment
  */
  public static BatchShipPackagesRequestBodyPackagesSelfShipment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchShipPackagesRequestBodyPackagesSelfShipment.class);
  }

 /**
  * Convert an instance of BatchShipPackagesRequestBodyPackagesSelfShipment to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

