/*
 * Amazon Ads API SP
 * Amazon Advertising API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPMonetaryBudgetValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * MonetaryBudgetValue
 */
@JsonPropertyOrder({
  MonetaryBudgetValue.JSON_PROPERTY_MONETARY_BUDGET_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T22:24:09.384781+08:00[Asia/Shanghai]")
public class MonetaryBudgetValue {
  public static final String JSON_PROPERTY_MONETARY_BUDGET_VALUE = "monetaryBudgetValue";
  private SPMonetaryBudgetValue monetaryBudgetValue;

  public MonetaryBudgetValue() { 
  }

  public MonetaryBudgetValue monetaryBudgetValue(SPMonetaryBudgetValue monetaryBudgetValue) {
    this.monetaryBudgetValue = monetaryBudgetValue;
    return this;
  }

   /**
   * Get monetaryBudgetValue
   * @return monetaryBudgetValue
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MONETARY_BUDGET_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SPMonetaryBudgetValue getMonetaryBudgetValue() {
    return monetaryBudgetValue;
  }


  @JsonProperty(JSON_PROPERTY_MONETARY_BUDGET_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMonetaryBudgetValue(SPMonetaryBudgetValue monetaryBudgetValue) {
    this.monetaryBudgetValue = monetaryBudgetValue;
  }


  /**
   * Return true if this monetaryBudgetValue object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonetaryBudgetValue monetaryBudgetValue = (MonetaryBudgetValue) o;
    return Objects.equals(this.monetaryBudgetValue, monetaryBudgetValue.monetaryBudgetValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(monetaryBudgetValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonetaryBudgetValue {\n");
    sb.append("    monetaryBudgetValue: ").append(toIndentedString(monetaryBudgetValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `monetaryBudgetValue` to the URL query string
    if (getMonetaryBudgetValue() != null) {
      joiner.add(getMonetaryBudgetValue().toUrlQueryString(prefix + "monetaryBudgetValue" + suffix));
    }

    return joiner.toString();
  }
}

