/*
 * Amazon Ads API SP
 * Amazon Advertising API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPAdProduct;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPAdType;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPCreative;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPMarketplace;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPMarketplaceScope;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPState;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPStatus;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.sp.SPTag;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SPAd
 */
@JsonPropertyOrder({
  SPAd.JSON_PROPERTY_AD_GROUP_ID,
  SPAd.JSON_PROPERTY_AD_ID,
  SPAd.JSON_PROPERTY_AD_PRODUCT,
  SPAd.JSON_PROPERTY_AD_TYPE,
  SPAd.JSON_PROPERTY_CAMPAIGN_ID,
  SPAd.JSON_PROPERTY_CREATION_DATE_TIME,
  SPAd.JSON_PROPERTY_CREATIVE,
  SPAd.JSON_PROPERTY_GLOBAL_AD_ID,
  SPAd.JSON_PROPERTY_LAST_UPDATED_DATE_TIME,
  SPAd.JSON_PROPERTY_MARKETPLACE_SCOPE,
  SPAd.JSON_PROPERTY_MARKETPLACES,
  SPAd.JSON_PROPERTY_STATE,
  SPAd.JSON_PROPERTY_STATUS,
  SPAd.JSON_PROPERTY_TAGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T22:24:09.384781+08:00[Asia/Shanghai]")
public class SPAd {
  public static final String JSON_PROPERTY_AD_GROUP_ID = "adGroupId";
  private String adGroupId;

  public static final String JSON_PROPERTY_AD_ID = "adId";
  private String adId;

  public static final String JSON_PROPERTY_AD_PRODUCT = "adProduct";
  private SPAdProduct adProduct;

  public static final String JSON_PROPERTY_AD_TYPE = "adType";
  private SPAdType adType;

  public static final String JSON_PROPERTY_CAMPAIGN_ID = "campaignId";
  private String campaignId;

  public static final String JSON_PROPERTY_CREATION_DATE_TIME = "creationDateTime";
  private OffsetDateTime creationDateTime;

  public static final String JSON_PROPERTY_CREATIVE = "creative";
  private SPCreative creative;

  public static final String JSON_PROPERTY_GLOBAL_AD_ID = "globalAdId";
  private String globalAdId;

  public static final String JSON_PROPERTY_LAST_UPDATED_DATE_TIME = "lastUpdatedDateTime";
  private OffsetDateTime lastUpdatedDateTime;

  public static final String JSON_PROPERTY_MARKETPLACE_SCOPE = "marketplaceScope";
  private SPMarketplaceScope marketplaceScope;

  public static final String JSON_PROPERTY_MARKETPLACES = "marketplaces";
  private List<SPMarketplace> marketplaces = new ArrayList<>();

  public static final String JSON_PROPERTY_STATE = "state";
  private SPState state;

  public static final String JSON_PROPERTY_STATUS = "status";
  private SPStatus status;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<SPTag> tags;

  public SPAd() { 
  }

  public SPAd adGroupId(String adGroupId) {
    this.adGroupId = adGroupId;
    return this;
  }

   /**
   * The ad group associated with the ad.
   * @return adGroupId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AD_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdGroupId() {
    return adGroupId;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdGroupId(String adGroupId) {
    this.adGroupId = adGroupId;
  }


  public SPAd adId(String adId) {
    this.adId = adId;
    return this;
  }

   /**
   * The identifier of the ad.
   * @return adId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdId() {
    return adId;
  }


  @JsonProperty(JSON_PROPERTY_AD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdId(String adId) {
    this.adId = adId;
  }


  public SPAd adProduct(SPAdProduct adProduct) {
    this.adProduct = adProduct;
    return this;
  }

   /**
   * Get adProduct
   * @return adProduct
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AD_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SPAdProduct getAdProduct() {
    return adProduct;
  }


  @JsonProperty(JSON_PROPERTY_AD_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdProduct(SPAdProduct adProduct) {
    this.adProduct = adProduct;
  }


  public SPAd adType(SPAdType adType) {
    this.adType = adType;
    return this;
  }

   /**
   * Get adType
   * @return adType
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AD_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SPAdType getAdType() {
    return adType;
  }


  @JsonProperty(JSON_PROPERTY_AD_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdType(SPAdType adType) {
    this.adType = adType;
  }


  public SPAd campaignId(String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

   /**
   * The campaign associated with the ad. It&#39;s a read-only field.
   * @return campaignId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCampaignId() {
    return campaignId;
  }


  @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCampaignId(String campaignId) {
    this.campaignId = campaignId;
  }


  public SPAd creationDateTime(OffsetDateTime creationDateTime) {
    this.creationDateTime = creationDateTime;
    return this;
  }

   /**
   * The date time that the ad was created.
   * @return creationDateTime
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreationDateTime() {
    return creationDateTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreationDateTime(OffsetDateTime creationDateTime) {
    this.creationDateTime = creationDateTime;
  }


  public SPAd creative(SPCreative creative) {
    this.creative = creative;
    return this;
  }

   /**
   * Get creative
   * @return creative
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SPCreative getCreative() {
    return creative;
  }


  @JsonProperty(JSON_PROPERTY_CREATIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreative(SPCreative creative) {
    this.creative = creative;
  }


  public SPAd globalAdId(String globalAdId) {
    this.globalAdId = globalAdId;
    return this;
  }

   /**
   * The global ad identifier that manages this marketplace ad.
   * @return globalAdId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GLOBAL_AD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGlobalAdId() {
    return globalAdId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_AD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGlobalAdId(String globalAdId) {
    this.globalAdId = globalAdId;
  }


  public SPAd lastUpdatedDateTime(OffsetDateTime lastUpdatedDateTime) {
    this.lastUpdatedDateTime = lastUpdatedDateTime;
    return this;
  }

   /**
   * The date time that the ad was last updated.
   * @return lastUpdatedDateTime
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLastUpdatedDateTime() {
    return lastUpdatedDateTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastUpdatedDateTime(OffsetDateTime lastUpdatedDateTime) {
    this.lastUpdatedDateTime = lastUpdatedDateTime;
  }


  public SPAd marketplaceScope(SPMarketplaceScope marketplaceScope) {
    this.marketplaceScope = marketplaceScope;
    return this;
  }

   /**
   * Get marketplaceScope
   * @return marketplaceScope
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MARKETPLACE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SPMarketplaceScope getMarketplaceScope() {
    return marketplaceScope;
  }


  @JsonProperty(JSON_PROPERTY_MARKETPLACE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMarketplaceScope(SPMarketplaceScope marketplaceScope) {
    this.marketplaceScope = marketplaceScope;
  }


  public SPAd marketplaces(List<SPMarketplace> marketplaces) {
    this.marketplaces = marketplaces;
    return this;
  }

  public SPAd addMarketplacesItem(SPMarketplace marketplacesItem) {
    if (this.marketplaces == null) {
      this.marketplaces = new ArrayList<>();
    }
    this.marketplaces.add(marketplacesItem);
    return this;
  }

   /**
   * A list of country codes representing Amazon marketplaces | Marketplace | Description | | --- | --- | | &#x60;AE&#x60; |  | | &#x60;AU&#x60; |  | | &#x60;BE&#x60; |  | | &#x60;BR&#x60; |  | | &#x60;CA&#x60; |  | | &#x60;DE&#x60; |  | | &#x60;EG&#x60; |  | | &#x60;ES&#x60; |  | | &#x60;FR&#x60; |  | | &#x60;GB&#x60; |  | | &#x60;IE&#x60; |  | | &#x60;IN&#x60; |  | | &#x60;IT&#x60; |  | | &#x60;JP&#x60; |  | | &#x60;MX&#x60; |  | | &#x60;NL&#x60; |  | | &#x60;PL&#x60; |  | | &#x60;SA&#x60; |  | | &#x60;SE&#x60; |  | | &#x60;SG&#x60; |  | | &#x60;TR&#x60; |  | | &#x60;US&#x60; |  | | &#x60;ZA&#x60; |  |
   * @return marketplaces
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MARKETPLACES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SPMarketplace> getMarketplaces() {
    return marketplaces;
  }


  @JsonProperty(JSON_PROPERTY_MARKETPLACES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMarketplaces(List<SPMarketplace> marketplaces) {
    this.marketplaces = marketplaces;
  }


  public SPAd state(SPState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SPState getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(SPState state) {
    this.state = state;
  }


  public SPAd status(SPStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SPStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(SPStatus status) {
    this.status = status;
  }


  public SPAd tags(List<SPTag> tags) {
    this.tags = tags;
    return this;
  }

  public SPAd addTagsItem(SPTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Open ended labels with a key value pair applied to the ad
   * @return tags
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SPTag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<SPTag> tags) {
    this.tags = tags;
  }


  /**
   * Return true if this SPAd object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SPAd spAd = (SPAd) o;
    return Objects.equals(this.adGroupId, spAd.adGroupId) &&
        Objects.equals(this.adId, spAd.adId) &&
        Objects.equals(this.adProduct, spAd.adProduct) &&
        Objects.equals(this.adType, spAd.adType) &&
        Objects.equals(this.campaignId, spAd.campaignId) &&
        Objects.equals(this.creationDateTime, spAd.creationDateTime) &&
        Objects.equals(this.creative, spAd.creative) &&
        Objects.equals(this.globalAdId, spAd.globalAdId) &&
        Objects.equals(this.lastUpdatedDateTime, spAd.lastUpdatedDateTime) &&
        Objects.equals(this.marketplaceScope, spAd.marketplaceScope) &&
        Objects.equals(this.marketplaces, spAd.marketplaces) &&
        Objects.equals(this.state, spAd.state) &&
        Objects.equals(this.status, spAd.status) &&
        Objects.equals(this.tags, spAd.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adGroupId, adId, adProduct, adType, campaignId, creationDateTime, creative, globalAdId, lastUpdatedDateTime, marketplaceScope, marketplaces, state, status, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SPAd {\n");
    sb.append("    adGroupId: ").append(toIndentedString(adGroupId)).append("\n");
    sb.append("    adId: ").append(toIndentedString(adId)).append("\n");
    sb.append("    adProduct: ").append(toIndentedString(adProduct)).append("\n");
    sb.append("    adType: ").append(toIndentedString(adType)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    creationDateTime: ").append(toIndentedString(creationDateTime)).append("\n");
    sb.append("    creative: ").append(toIndentedString(creative)).append("\n");
    sb.append("    globalAdId: ").append(toIndentedString(globalAdId)).append("\n");
    sb.append("    lastUpdatedDateTime: ").append(toIndentedString(lastUpdatedDateTime)).append("\n");
    sb.append("    marketplaceScope: ").append(toIndentedString(marketplaceScope)).append("\n");
    sb.append("    marketplaces: ").append(toIndentedString(marketplaces)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `adGroupId` to the URL query string
    if (getAdGroupId() != null) {
      joiner.add(String.format("%sadGroupId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAdGroupId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `adId` to the URL query string
    if (getAdId() != null) {
      joiner.add(String.format("%sadId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAdId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `adProduct` to the URL query string
    if (getAdProduct() != null) {
      joiner.add(String.format("%sadProduct%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAdProduct()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `adType` to the URL query string
    if (getAdType() != null) {
      joiner.add(String.format("%sadType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAdType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `campaignId` to the URL query string
    if (getCampaignId() != null) {
      joiner.add(String.format("%scampaignId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCampaignId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `creationDateTime` to the URL query string
    if (getCreationDateTime() != null) {
      joiner.add(String.format("%screationDateTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreationDateTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `creative` to the URL query string
    if (getCreative() != null) {
      joiner.add(getCreative().toUrlQueryString(prefix + "creative" + suffix));
    }

    // add `globalAdId` to the URL query string
    if (getGlobalAdId() != null) {
      joiner.add(String.format("%sglobalAdId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getGlobalAdId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `lastUpdatedDateTime` to the URL query string
    if (getLastUpdatedDateTime() != null) {
      joiner.add(String.format("%slastUpdatedDateTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastUpdatedDateTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `marketplaceScope` to the URL query string
    if (getMarketplaceScope() != null) {
      joiner.add(String.format("%smarketplaceScope%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMarketplaceScope()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `marketplaces` to the URL query string
    if (getMarketplaces() != null) {
      for (int i = 0; i < getMarketplaces().size(); i++) {
        if (getMarketplaces().get(i) != null) {
          joiner.add(String.format("%smarketplaces%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getMarketplaces().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
        }
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(String.format("%sstate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getState()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(getStatus().toUrlQueryString(prefix + "status" + suffix));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        if (getTags().get(i) != null) {
          joiner.add(getTags().get(i).toUrlQueryString(String.format("%stags%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

