/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202405;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-28T03:28:06.328409Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus {
  public static final String SERIALIZED_NAME_BARCODE = "barcode";
  @SerializedName(SERIALIZED_NAME_BARCODE)
  @javax.annotation.Nullable
  private String barcode;

  public static final String SERIALIZED_NAME_EXTERNAL_SKU_CODE = "external_sku_code";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SKU_CODE)
  @javax.annotation.Nullable
  private String externalSkuCode;

  public static final String SERIALIZED_NAME_PLATFORM_SKU_CODE = "platform_sku_code";
  @SerializedName(SERIALIZED_NAME_PLATFORM_SKU_CODE)
  @javax.annotation.Nullable
  private String platformSkuCode;

  public static final String SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_NAME_EN = "second_key_attribute_name_en";
  @SerializedName(SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_NAME_EN)
  @javax.annotation.Nullable
  private String secondKeyAttributeNameEn;

  public static final String SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_NAME_ZH = "second_key_attribute_name_zh";
  @SerializedName(SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_NAME_ZH)
  @javax.annotation.Nullable
  private String secondKeyAttributeNameZh;

  public static final String SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_VALUE_EN = "second_key_attribute_value_en";
  @SerializedName(SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_VALUE_EN)
  @javax.annotation.Nullable
  private String secondKeyAttributeValueEn;

  public static final String SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_VALUE_ZH = "second_key_attribute_value_zh";
  @SerializedName(SERIALIZED_NAME_SECOND_KEY_ATTRIBUTE_VALUE_ZH)
  @javax.annotation.Nullable
  private String secondKeyAttributeValueZh;

  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus() {
  }

  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus barcode(@javax.annotation.Nullable String barcode) {
    this.barcode = barcode;
    return this;
  }

  /**
   * The barcode of platform-defined sku 
   * @return barcode
   */
  @javax.annotation.Nullable
  public String getBarcode() {
    return barcode;
  }

  public void setBarcode(@javax.annotation.Nullable String barcode) {
    this.barcode = barcode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus externalSkuCode(@javax.annotation.Nullable String externalSkuCode) {
    this.externalSkuCode = externalSkuCode;
    return this;
  }

  /**
   * The code of merchant-defined sku
   * @return externalSkuCode
   */
  @javax.annotation.Nullable
  public String getExternalSkuCode() {
    return externalSkuCode;
  }

  public void setExternalSkuCode(@javax.annotation.Nullable String externalSkuCode) {
    this.externalSkuCode = externalSkuCode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus platformSkuCode(@javax.annotation.Nullable String platformSkuCode) {
    this.platformSkuCode = platformSkuCode;
    return this;
  }

  /**
   * The code of platform-defined sku 
   * @return platformSkuCode
   */
  @javax.annotation.Nullable
  public String getPlatformSkuCode() {
    return platformSkuCode;
  }

  public void setPlatformSkuCode(@javax.annotation.Nullable String platformSkuCode) {
    this.platformSkuCode = platformSkuCode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus secondKeyAttributeNameEn(@javax.annotation.Nullable String secondKeyAttributeNameEn) {
    this.secondKeyAttributeNameEn = secondKeyAttributeNameEn;
    return this;
  }

  /**
   * The English name of the second key attribute for Platform-defined sku 
   * @return secondKeyAttributeNameEn
   */
  @javax.annotation.Nullable
  public String getSecondKeyAttributeNameEn() {
    return secondKeyAttributeNameEn;
  }

  public void setSecondKeyAttributeNameEn(@javax.annotation.Nullable String secondKeyAttributeNameEn) {
    this.secondKeyAttributeNameEn = secondKeyAttributeNameEn;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus secondKeyAttributeNameZh(@javax.annotation.Nullable String secondKeyAttributeNameZh) {
    this.secondKeyAttributeNameZh = secondKeyAttributeNameZh;
    return this;
  }

  /**
   * The Chinese name of the second key attribute for Platform-defined sku 
   * @return secondKeyAttributeNameZh
   */
  @javax.annotation.Nullable
  public String getSecondKeyAttributeNameZh() {
    return secondKeyAttributeNameZh;
  }

  public void setSecondKeyAttributeNameZh(@javax.annotation.Nullable String secondKeyAttributeNameZh) {
    this.secondKeyAttributeNameZh = secondKeyAttributeNameZh;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus secondKeyAttributeValueEn(@javax.annotation.Nullable String secondKeyAttributeValueEn) {
    this.secondKeyAttributeValueEn = secondKeyAttributeValueEn;
    return this;
  }

  /**
   * The English value of the second key attribute for Platform-defined sku 
   * @return secondKeyAttributeValueEn
   */
  @javax.annotation.Nullable
  public String getSecondKeyAttributeValueEn() {
    return secondKeyAttributeValueEn;
  }

  public void setSecondKeyAttributeValueEn(@javax.annotation.Nullable String secondKeyAttributeValueEn) {
    this.secondKeyAttributeValueEn = secondKeyAttributeValueEn;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus secondKeyAttributeValueZh(@javax.annotation.Nullable String secondKeyAttributeValueZh) {
    this.secondKeyAttributeValueZh = secondKeyAttributeValueZh;
    return this;
  }

  /**
   * The Chinese value of the second key attribute for Platform-defined sku 
   * @return secondKeyAttributeValueZh
   */
  @javax.annotation.Nullable
  public String getSecondKeyAttributeValueZh() {
    return secondKeyAttributeValueZh;
  }

  public void setSecondKeyAttributeValueZh(@javax.annotation.Nullable String secondKeyAttributeValueZh) {
    this.secondKeyAttributeValueZh = secondKeyAttributeValueZh;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus instance itself
   */
  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus = (GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus) o;
    return Objects.equals(this.barcode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.barcode) &&
        Objects.equals(this.externalSkuCode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.externalSkuCode) &&
        Objects.equals(this.platformSkuCode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.platformSkuCode) &&
        Objects.equals(this.secondKeyAttributeNameEn, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.secondKeyAttributeNameEn) &&
        Objects.equals(this.secondKeyAttributeNameZh, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.secondKeyAttributeNameZh) &&
        Objects.equals(this.secondKeyAttributeValueEn, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.secondKeyAttributeValueEn) &&
        Objects.equals(this.secondKeyAttributeValueZh, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.secondKeyAttributeValueZh)&&
        Objects.equals(this.additionalProperties, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barcode, externalSkuCode, platformSkuCode, secondKeyAttributeNameEn, secondKeyAttributeNameZh, secondKeyAttributeValueEn, secondKeyAttributeValueZh, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus {\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    externalSkuCode: ").append(toIndentedString(externalSkuCode)).append("\n");
    sb.append("    platformSkuCode: ").append(toIndentedString(platformSkuCode)).append("\n");
    sb.append("    secondKeyAttributeNameEn: ").append(toIndentedString(secondKeyAttributeNameEn)).append("\n");
    sb.append("    secondKeyAttributeNameZh: ").append(toIndentedString(secondKeyAttributeNameZh)).append("\n");
    sb.append("    secondKeyAttributeValueEn: ").append(toIndentedString(secondKeyAttributeValueEn)).append("\n");
    sb.append("    secondKeyAttributeValueZh: ").append(toIndentedString(secondKeyAttributeValueZh)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("barcode", "external_sku_code", "platform_sku_code", "second_key_attribute_name_en", "second_key_attribute_name_zh", "second_key_attribute_value_en", "second_key_attribute_value_zh"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus is not found in the empty JSON string", GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("barcode") != null && !jsonObj.get("barcode").isJsonNull()) && !jsonObj.get("barcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcode").toString()));
      }
      if ((jsonObj.get("external_sku_code") != null && !jsonObj.get("external_sku_code").isJsonNull()) && !jsonObj.get("external_sku_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `external_sku_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("external_sku_code").toString()));
      }
      if ((jsonObj.get("platform_sku_code") != null && !jsonObj.get("platform_sku_code").isJsonNull()) && !jsonObj.get("platform_sku_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `platform_sku_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform_sku_code").toString()));
      }
      if ((jsonObj.get("second_key_attribute_name_en") != null && !jsonObj.get("second_key_attribute_name_en").isJsonNull()) && !jsonObj.get("second_key_attribute_name_en").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `second_key_attribute_name_en` to be a primitive type in the JSON string but got `%s`", jsonObj.get("second_key_attribute_name_en").toString()));
      }
      if ((jsonObj.get("second_key_attribute_name_zh") != null && !jsonObj.get("second_key_attribute_name_zh").isJsonNull()) && !jsonObj.get("second_key_attribute_name_zh").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `second_key_attribute_name_zh` to be a primitive type in the JSON string but got `%s`", jsonObj.get("second_key_attribute_name_zh").toString()));
      }
      if ((jsonObj.get("second_key_attribute_value_en") != null && !jsonObj.get("second_key_attribute_value_en").isJsonNull()) && !jsonObj.get("second_key_attribute_value_en").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `second_key_attribute_value_en` to be a primitive type in the JSON string but got `%s`", jsonObj.get("second_key_attribute_value_en").toString()));
      }
      if ((jsonObj.get("second_key_attribute_value_zh") != null && !jsonObj.get("second_key_attribute_value_zh").isJsonNull()) && !jsonObj.get("second_key_attribute_value_zh").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `second_key_attribute_value_zh` to be a primitive type in the JSON string but got `%s`", jsonObj.get("second_key_attribute_value_zh").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.class));

       return (TypeAdapter<T>) new TypeAdapter<GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus>() {
           @Override
           public void write(JsonWriter out, GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus
   * @throws IOException if the JSON string is invalid with respect to GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus
   */
  public static GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.class);
  }

  /**
   * Convert an instance of GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

