/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202405;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202405.GSSearchDeliveryOrdersResponseDataDeliveryOrdersDeliveryPackages;
import tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202405.GSSearchDeliveryOrdersResponseDataDeliveryOrdersLogistics;
import tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202405.GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkc;
import tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202405.GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus;
import tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202405.GSSearchDeliveryOrdersResponseDataDeliveryOrdersWarehouseContact;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * GSSearchDeliveryOrdersResponseDataDeliveryOrders
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-28T03:28:06.328409Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class GSSearchDeliveryOrdersResponseDataDeliveryOrders {
  public static final String SERIALIZED_NAME_ARRIVED_TIME = "arrived_time";
  @SerializedName(SERIALIZED_NAME_ARRIVED_TIME)
  @javax.annotation.Nullable
  private Long arrivedTime;

  public static final String SERIALIZED_NAME_CATEGORY_ID = "category_id";
  @SerializedName(SERIALIZED_NAME_CATEGORY_ID)
  @javax.annotation.Nullable
  private String categoryId;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_DELIVERY_BATCH_CODE = "delivery_batch_code";
  @SerializedName(SERIALIZED_NAME_DELIVERY_BATCH_CODE)
  @javax.annotation.Nullable
  private String deliveryBatchCode;

  public static final String SERIALIZED_NAME_DELIVERY_PACKAGES = "delivery_packages";
  @SerializedName(SERIALIZED_NAME_DELIVERY_PACKAGES)
  @javax.annotation.Nullable
  private List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersDeliveryPackages> deliveryPackages = new ArrayList<>();

  public static final String SERIALIZED_NAME_DELIVERY_QUANTITY = "delivery_quantity";
  @SerializedName(SERIALIZED_NAME_DELIVERY_QUANTITY)
  @javax.annotation.Nullable
  private Long deliveryQuantity;

  public static final String SERIALIZED_NAME_DELIVERY_TYPE = "delivery_type";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TYPE)
  @javax.annotation.Nullable
  private String deliveryType;

  public static final String SERIALIZED_NAME_EMERGENCY_LEVEL = "emergency_level";
  @SerializedName(SERIALIZED_NAME_EMERGENCY_LEVEL)
  @javax.annotation.Nullable
  private String emergencyLevel;

  public static final String SERIALIZED_NAME_INBOUND_QUANTITY = "inbound_quantity";
  @SerializedName(SERIALIZED_NAME_INBOUND_QUANTITY)
  @javax.annotation.Nullable
  private Long inboundQuantity;

  public static final String SERIALIZED_NAME_IS_FIRST_ORDER = "is_first_order";
  @SerializedName(SERIALIZED_NAME_IS_FIRST_ORDER)
  @javax.annotation.Nullable
  private Boolean isFirstOrder;

  public static final String SERIALIZED_NAME_IS_SAMPLE_INCLUDED = "is_sample_included";
  @SerializedName(SERIALIZED_NAME_IS_SAMPLE_INCLUDED)
  @javax.annotation.Nullable
  private Boolean isSampleIncluded;

  public static final String SERIALIZED_NAME_LATEST_STATUS_UPDATE_TIME = "latest_status_update_time";
  @SerializedName(SERIALIZED_NAME_LATEST_STATUS_UPDATE_TIME)
  @javax.annotation.Nullable
  private Long latestStatusUpdateTime;

  public static final String SERIALIZED_NAME_LOGISTICS = "logistics";
  @SerializedName(SERIALIZED_NAME_LOGISTICS)
  @javax.annotation.Nullable
  private GSSearchDeliveryOrdersResponseDataDeliveryOrdersLogistics logistics;

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  @javax.annotation.Nullable
  private String mode;

  public static final String SERIALIZED_NAME_PLATFORM_SPU_CODE = "platform_spu_code";
  @SerializedName(SERIALIZED_NAME_PLATFORM_SPU_CODE)
  @javax.annotation.Nullable
  private String platformSpuCode;

  public static final String SERIALIZED_NAME_PREDICTED_ARRIVED_TIME = "predicted_arrived_time";
  @SerializedName(SERIALIZED_NAME_PREDICTED_ARRIVED_TIME)
  @javax.annotation.Nullable
  private Long predictedArrivedTime;

  public static final String SERIALIZED_NAME_PREDICTED_SHIP_TIME = "predicted_ship_time";
  @SerializedName(SERIALIZED_NAME_PREDICTED_SHIP_TIME)
  @javax.annotation.Nullable
  private Long predictedShipTime;

  public static final String SERIALIZED_NAME_QUALIFIED_QUANTITY = "qualified_quantity";
  @SerializedName(SERIALIZED_NAME_QUALIFIED_QUANTITY)
  @javax.annotation.Nullable
  private Long qualifiedQuantity;

  public static final String SERIALIZED_NAME_QUALITY_CHECK_RESULT = "quality_check_result";
  @SerializedName(SERIALIZED_NAME_QUALITY_CHECK_RESULT)
  @javax.annotation.Nullable
  private String qualityCheckResult;

  public static final String SERIALIZED_NAME_RECEIVED_QUANTITY = "received_quantity";
  @SerializedName(SERIALIZED_NAME_RECEIVED_QUANTITY)
  @javax.annotation.Nullable
  private Long receivedQuantity;

  public static final String SERIALIZED_NAME_RELATIVE_CODE = "relative_code";
  @SerializedName(SERIALIZED_NAME_RELATIVE_CODE)
  @javax.annotation.Nullable
  private String relativeCode;

  public static final String SERIALIZED_NAME_RELATIVE_CODE_TYPE = "relative_code_type";
  @SerializedName(SERIALIZED_NAME_RELATIVE_CODE_TYPE)
  @javax.annotation.Nullable
  private String relativeCodeType;

  public static final String SERIALIZED_NAME_REQUIRE_ARRIVED_TIME = "require_arrived_time";
  @SerializedName(SERIALIZED_NAME_REQUIRE_ARRIVED_TIME)
  @javax.annotation.Nullable
  private Long requireArrivedTime;

  public static final String SERIALIZED_NAME_RETURNED_QUANTITY = "returned_quantity";
  @SerializedName(SERIALIZED_NAME_RETURNED_QUANTITY)
  @javax.annotation.Nullable
  private Long returnedQuantity;

  public static final String SERIALIZED_NAME_SAMPLE_CODE = "sample_code";
  @SerializedName(SERIALIZED_NAME_SAMPLE_CODE)
  @javax.annotation.Nullable
  private String sampleCode;

  public static final String SERIALIZED_NAME_SAMPLE_STATUS = "sample_status";
  @SerializedName(SERIALIZED_NAME_SAMPLE_STATUS)
  @javax.annotation.Nullable
  private String sampleStatus;

  public static final String SERIALIZED_NAME_SHIP_TIME = "ship_time";
  @SerializedName(SERIALIZED_NAME_SHIP_TIME)
  @javax.annotation.Nullable
  private Long shipTime;

  public static final String SERIALIZED_NAME_SKC = "skc";
  @SerializedName(SERIALIZED_NAME_SKC)
  @javax.annotation.Nullable
  private GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkc skc;

  public static final String SERIALIZED_NAME_SKUS = "skus";
  @SerializedName(SERIALIZED_NAME_SKUS)
  @javax.annotation.Nullable
  private List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus> skus = new ArrayList<>();

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_STOCKUP_TYPE = "stockup_type";
  @SerializedName(SERIALIZED_NAME_STOCKUP_TYPE)
  @javax.annotation.Nullable
  private String stockupType;

  public static final String SERIALIZED_NAME_UNQUALIFIED_QUANTITY = "unqualified_quantity";
  @SerializedName(SERIALIZED_NAME_UNQUALIFIED_QUANTITY)
  @javax.annotation.Nullable
  private Long unqualifiedQuantity;

  public static final String SERIALIZED_NAME_WAREHOUSE_CODE = "warehouse_code";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_CODE)
  @javax.annotation.Nullable
  private String warehouseCode;

  public static final String SERIALIZED_NAME_WAREHOUSE_CONTACT = "warehouse_contact";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_CONTACT)
  @javax.annotation.Nullable
  private GSSearchDeliveryOrdersResponseDataDeliveryOrdersWarehouseContact warehouseContact;

  public static final String SERIALIZED_NAME_WAREHOUSE_NAME = "warehouse_name";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_NAME)
  @javax.annotation.Nullable
  private String warehouseName;

  public GSSearchDeliveryOrdersResponseDataDeliveryOrders() {
  }

  public GSSearchDeliveryOrdersResponseDataDeliveryOrders arrivedTime(@javax.annotation.Nullable Long arrivedTime) {
    this.arrivedTime = arrivedTime;
    return this;
  }

  /**
   * The actual time to arrive at the warehouse
   * @return arrivedTime
   */
  @javax.annotation.Nullable
  public Long getArrivedTime() {
    return arrivedTime;
  }

  public void setArrivedTime(@javax.annotation.Nullable Long arrivedTime) {
    this.arrivedTime = arrivedTime;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders categoryId(@javax.annotation.Nullable String categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * The category ID of product which has been defined by platform.
   * @return categoryId
   */
  @javax.annotation.Nullable
  public String getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(@javax.annotation.Nullable String categoryId) {
    this.categoryId = categoryId;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * Delivery type, support multiple selection. 1. DELIVERY_NORMAL: Delivery of normal stockup process. 2. DEFECTIVE_REPAIR: Re-delivery of partial defective products returned for repair. 3. ALL_RETURN_REPAIR: Re-delivery of all defective products returned for repair. 4. LESS_SUPPLEMENT: Re-delivery of shortage of delivery quantity. 5. LOGISTICS_IN_BATCH: The logistics provider delivers the goods to the warehouse in multiple batches. 6. REPLENISH_IN_WAREHOUSE: The platform receives goods in multiple batches in the warehouse.
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders deliveryBatchCode(@javax.annotation.Nullable String deliveryBatchCode) {
    this.deliveryBatchCode = deliveryBatchCode;
    return this;
  }

  /**
   * The code of delivery batch
   * @return deliveryBatchCode
   */
  @javax.annotation.Nullable
  public String getDeliveryBatchCode() {
    return deliveryBatchCode;
  }

  public void setDeliveryBatchCode(@javax.annotation.Nullable String deliveryBatchCode) {
    this.deliveryBatchCode = deliveryBatchCode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders deliveryPackages(@javax.annotation.Nullable List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersDeliveryPackages> deliveryPackages) {
    this.deliveryPackages = deliveryPackages;
    return this;
  }

  public GSSearchDeliveryOrdersResponseDataDeliveryOrders addDeliveryPackagesItem(GSSearchDeliveryOrdersResponseDataDeliveryOrdersDeliveryPackages deliveryPackagesItem) {
    if (this.deliveryPackages == null) {
      this.deliveryPackages = new ArrayList<>();
    }
    this.deliveryPackages.add(deliveryPackagesItem);
    return this;
  }

  /**
   * The information list of delivery package 
   * @return deliveryPackages
   */
  @javax.annotation.Nullable
  public List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersDeliveryPackages> getDeliveryPackages() {
    return deliveryPackages;
  }

  public void setDeliveryPackages(@javax.annotation.Nullable List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersDeliveryPackages> deliveryPackages) {
    this.deliveryPackages = deliveryPackages;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders deliveryQuantity(@javax.annotation.Nullable Long deliveryQuantity) {
    this.deliveryQuantity = deliveryQuantity;
    return this;
  }

  /**
   * The quantity of goods which have been shipped from the merchant.
   * @return deliveryQuantity
   */
  @javax.annotation.Nullable
  public Long getDeliveryQuantity() {
    return deliveryQuantity;
  }

  public void setDeliveryQuantity(@javax.annotation.Nullable Long deliveryQuantity) {
    this.deliveryQuantity = deliveryQuantity;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders deliveryType(@javax.annotation.Nullable String deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Delivery type, support multiple selection. 1. DELIVERY_NORMAL: Delivery of normal stockup process. 2. DEFECTIVE_REPAIR: Re-delivery of partial defective products returned for repair. 3. ALL_RETURN_REPAIR: Re-delivery of all defective products returned for repair. 4. LESS_SUPPLEMENT: Re-delivery of shortage of delivery quantity. 5. LOGISTICS_IN_BATCH: The logistics provider delivers the goods to the warehouse in multiple batches. 6. REPLENISH_IN_WAREHOUSE: The platform receives goods in multiple batches in the warehouse.
   * @return deliveryType
   */
  @javax.annotation.Nullable
  public String getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(@javax.annotation.Nullable String deliveryType) {
    this.deliveryType = deliveryType;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders emergencyLevel(@javax.annotation.Nullable String emergencyLevel) {
    this.emergencyLevel = emergencyLevel;
    return this;
  }

  /**
   * Delivery-Order&#39;s Emergency level code. 1. URGENT: the emergency level of stockup order is defined as urgent once created. 2. EXPEDITED: the emergency level of stockup order is defined as expedited in transit. 3. GENERAL: the emergency level of stockup order is defined as general.
   * @return emergencyLevel
   */
  @javax.annotation.Nullable
  public String getEmergencyLevel() {
    return emergencyLevel;
  }

  public void setEmergencyLevel(@javax.annotation.Nullable String emergencyLevel) {
    this.emergencyLevel = emergencyLevel;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders inboundQuantity(@javax.annotation.Nullable Long inboundQuantity) {
    this.inboundQuantity = inboundQuantity;
    return this;
  }

  /**
   * The quantity of goods which have beeninbound by the warehouse.
   * @return inboundQuantity
   */
  @javax.annotation.Nullable
  public Long getInboundQuantity() {
    return inboundQuantity;
  }

  public void setInboundQuantity(@javax.annotation.Nullable Long inboundQuantity) {
    this.inboundQuantity = inboundQuantity;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders isFirstOrder(@javax.annotation.Nullable Boolean isFirstOrder) {
    this.isFirstOrder = isFirstOrder;
    return this;
  }

  /**
   * Whether first delivery order for merchant
   * @return isFirstOrder
   */
  @javax.annotation.Nullable
  public Boolean getIsFirstOrder() {
    return isFirstOrder;
  }

  public void setIsFirstOrder(@javax.annotation.Nullable Boolean isFirstOrder) {
    this.isFirstOrder = isFirstOrder;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders isSampleIncluded(@javax.annotation.Nullable Boolean isSampleIncluded) {
    this.isSampleIncluded = isSampleIncluded;
    return this;
  }

  /**
   * Whether sample product should be sent with bulk delivery
   * @return isSampleIncluded
   */
  @javax.annotation.Nullable
  public Boolean getIsSampleIncluded() {
    return isSampleIncluded;
  }

  public void setIsSampleIncluded(@javax.annotation.Nullable Boolean isSampleIncluded) {
    this.isSampleIncluded = isSampleIncluded;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders latestStatusUpdateTime(@javax.annotation.Nullable Long latestStatusUpdateTime) {
    this.latestStatusUpdateTime = latestStatusUpdateTime;
    return this;
  }

  /**
   * The time of the latest status update.
   * @return latestStatusUpdateTime
   */
  @javax.annotation.Nullable
  public Long getLatestStatusUpdateTime() {
    return latestStatusUpdateTime;
  }

  public void setLatestStatusUpdateTime(@javax.annotation.Nullable Long latestStatusUpdateTime) {
    this.latestStatusUpdateTime = latestStatusUpdateTime;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders logistics(@javax.annotation.Nullable GSSearchDeliveryOrdersResponseDataDeliveryOrdersLogistics logistics) {
    this.logistics = logistics;
    return this;
  }

  /**
   * Get logistics
   * @return logistics
   */
  @javax.annotation.Nullable
  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersLogistics getLogistics() {
    return logistics;
  }

  public void setLogistics(@javax.annotation.Nullable GSSearchDeliveryOrdersResponseDataDeliveryOrdersLogistics logistics) {
    this.logistics = logistics;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders mode(@javax.annotation.Nullable String mode) {
    this.mode = mode;
    return this;
  }

  /**
   * The mode of delivery goods to GS. 1. SELF_DELIVERY 2. PLATFORM_DELIVERY
   * @return mode
   */
  @javax.annotation.Nullable
  public String getMode() {
    return mode;
  }

  public void setMode(@javax.annotation.Nullable String mode) {
    this.mode = mode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders platformSpuCode(@javax.annotation.Nullable String platformSpuCode) {
    this.platformSpuCode = platformSpuCode;
    return this;
  }

  /**
   * The code of platform-defined sku.
   * @return platformSpuCode
   */
  @javax.annotation.Nullable
  public String getPlatformSpuCode() {
    return platformSpuCode;
  }

  public void setPlatformSpuCode(@javax.annotation.Nullable String platformSpuCode) {
    this.platformSpuCode = platformSpuCode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders predictedArrivedTime(@javax.annotation.Nullable Long predictedArrivedTime) {
    this.predictedArrivedTime = predictedArrivedTime;
    return this;
  }

  /**
   * The predicted time to arrive at the warehouse
   * @return predictedArrivedTime
   */
  @javax.annotation.Nullable
  public Long getPredictedArrivedTime() {
    return predictedArrivedTime;
  }

  public void setPredictedArrivedTime(@javax.annotation.Nullable Long predictedArrivedTime) {
    this.predictedArrivedTime = predictedArrivedTime;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders predictedShipTime(@javax.annotation.Nullable Long predictedShipTime) {
    this.predictedShipTime = predictedShipTime;
    return this;
  }

  /**
   * The predicted time for merchant delivery goods
   * @return predictedShipTime
   */
  @javax.annotation.Nullable
  public Long getPredictedShipTime() {
    return predictedShipTime;
  }

  public void setPredictedShipTime(@javax.annotation.Nullable Long predictedShipTime) {
    this.predictedShipTime = predictedShipTime;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders qualifiedQuantity(@javax.annotation.Nullable Long qualifiedQuantity) {
    this.qualifiedQuantity = qualifiedQuantity;
    return this;
  }

  /**
   * The quantity of goods which is quality-check qualified in warehouse.
   * @return qualifiedQuantity
   */
  @javax.annotation.Nullable
  public Long getQualifiedQuantity() {
    return qualifiedQuantity;
  }

  public void setQualifiedQuantity(@javax.annotation.Nullable Long qualifiedQuantity) {
    this.qualifiedQuantity = qualifiedQuantity;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders qualityCheckResult(@javax.annotation.Nullable String qualityCheckResult) {
    this.qualityCheckResult = qualityCheckResult;
    return this;
  }

  /**
   * The result of quality-check 1. PASS 2. FAIL 3. PART_FAIL
   * @return qualityCheckResult
   */
  @javax.annotation.Nullable
  public String getQualityCheckResult() {
    return qualityCheckResult;
  }

  public void setQualityCheckResult(@javax.annotation.Nullable String qualityCheckResult) {
    this.qualityCheckResult = qualityCheckResult;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders receivedQuantity(@javax.annotation.Nullable Long receivedQuantity) {
    this.receivedQuantity = receivedQuantity;
    return this;
  }

  /**
   * The quantity of goods which have been received and counted by the warehouse.
   * @return receivedQuantity
   */
  @javax.annotation.Nullable
  public Long getReceivedQuantity() {
    return receivedQuantity;
  }

  public void setReceivedQuantity(@javax.annotation.Nullable Long receivedQuantity) {
    this.receivedQuantity = receivedQuantity;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders relativeCode(@javax.annotation.Nullable String relativeCode) {
    this.relativeCode = relativeCode;
    return this;
  }

  /**
   * The relative code of delivery order
   * @return relativeCode
   */
  @javax.annotation.Nullable
  public String getRelativeCode() {
    return relativeCode;
  }

  public void setRelativeCode(@javax.annotation.Nullable String relativeCode) {
    this.relativeCode = relativeCode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders relativeCodeType(@javax.annotation.Nullable String relativeCodeType) {
    this.relativeCodeType = relativeCodeType;
    return this;
  }

  /**
   * The relative code of delivery order, such as stockup order code and abnormal order code. Up to 50 1. STOCKUP_ORDER 2. ABNORMAL_ORDER
   * @return relativeCodeType
   */
  @javax.annotation.Nullable
  public String getRelativeCodeType() {
    return relativeCodeType;
  }

  public void setRelativeCodeType(@javax.annotation.Nullable String relativeCodeType) {
    this.relativeCodeType = relativeCodeType;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders requireArrivedTime(@javax.annotation.Nullable Long requireArrivedTime) {
    this.requireArrivedTime = requireArrivedTime;
    return this;
  }

  /**
   * The deadline should arrive at the warehouse
   * @return requireArrivedTime
   */
  @javax.annotation.Nullable
  public Long getRequireArrivedTime() {
    return requireArrivedTime;
  }

  public void setRequireArrivedTime(@javax.annotation.Nullable Long requireArrivedTime) {
    this.requireArrivedTime = requireArrivedTime;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders returnedQuantity(@javax.annotation.Nullable Long returnedQuantity) {
    this.returnedQuantity = returnedQuantity;
    return this;
  }

  /**
   * The quantity of goods which have been returned due to quality problems.
   * @return returnedQuantity
   */
  @javax.annotation.Nullable
  public Long getReturnedQuantity() {
    return returnedQuantity;
  }

  public void setReturnedQuantity(@javax.annotation.Nullable Long returnedQuantity) {
    this.returnedQuantity = returnedQuantity;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders sampleCode(@javax.annotation.Nullable String sampleCode) {
    this.sampleCode = sampleCode;
    return this;
  }

  /**
   * The code of sample product
   * @return sampleCode
   */
  @javax.annotation.Nullable
  public String getSampleCode() {
    return sampleCode;
  }

  public void setSampleCode(@javax.annotation.Nullable String sampleCode) {
    this.sampleCode = sampleCode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders sampleStatus(@javax.annotation.Nullable String sampleStatus) {
    this.sampleStatus = sampleStatus;
    return this;
  }

  /**
   * The status of sample product management 1. WAIT_FOR_SEND 2. SAMPLE_SENT 3. PLATFORM_SIGNED 4. WAIT_FOR_SUPPLIER_SIGN 5. SUPPLIER_SIGNED 6. CANCELED
   * @return sampleStatus
   */
  @javax.annotation.Nullable
  public String getSampleStatus() {
    return sampleStatus;
  }

  public void setSampleStatus(@javax.annotation.Nullable String sampleStatus) {
    this.sampleStatus = sampleStatus;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders shipTime(@javax.annotation.Nullable Long shipTime) {
    this.shipTime = shipTime;
    return this;
  }

  /**
   * The actual time of merchant delivery goods by logistics
   * @return shipTime
   */
  @javax.annotation.Nullable
  public Long getShipTime() {
    return shipTime;
  }

  public void setShipTime(@javax.annotation.Nullable Long shipTime) {
    this.shipTime = shipTime;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders skc(@javax.annotation.Nullable GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkc skc) {
    this.skc = skc;
    return this;
  }

  /**
   * Get skc
   * @return skc
   */
  @javax.annotation.Nullable
  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkc getSkc() {
    return skc;
  }

  public void setSkc(@javax.annotation.Nullable GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkc skc) {
    this.skc = skc;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders skus(@javax.annotation.Nullable List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus> skus) {
    this.skus = skus;
    return this;
  }

  public GSSearchDeliveryOrdersResponseDataDeliveryOrders addSkusItem(GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus skusItem) {
    if (this.skus == null) {
      this.skus = new ArrayList<>();
    }
    this.skus.add(skusItem);
    return this;
  }

  /**
   * The information list of sku
   * @return skus
   */
  @javax.annotation.Nullable
  public List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus> getSkus() {
    return skus;
  }

  public void setSkus(@javax.annotation.Nullable List<GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus> skus) {
    this.skus = skus;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * The status code of delivery-order. 1. WAIT_DELIVERY:  wait for merchants to deliver goods 2. DELIVERED: Merchant already delivered goods to GS by logistics. 3. SIGNED: The logistics track shows that it has been signed by the warehouse 4. RECEIVED: The goods have been received and unpacked in the warehouse. 5. IN_QUALITY_CHECK:  The goods are being quality inspected in the warehouse. 6. QUALITY_CHECK_COMPLETED: The goods have finished quality inspected in the warehouse. 7. INBOUND: The goods haveinbounded in the warehouse. 8. RETURN_COMPLETED:  The goods have returned and shipped to merchant. 9. CANCELED: The delivery order was canceled, merchants didn&#39;t need to deliver goods to GS.
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders stockupType(@javax.annotation.Nullable String stockupType) {
    this.stockupType = stockupType;
    return this;
  }

  /**
   * The stockup type of delivery JIT: Stockup is determined by sales. NORMAL: Stockup is for sales.
   * @return stockupType
   */
  @javax.annotation.Nullable
  public String getStockupType() {
    return stockupType;
  }

  public void setStockupType(@javax.annotation.Nullable String stockupType) {
    this.stockupType = stockupType;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders unqualifiedQuantity(@javax.annotation.Nullable Long unqualifiedQuantity) {
    this.unqualifiedQuantity = unqualifiedQuantity;
    return this;
  }

  /**
   * The quantity of goods which is quality-check unqualified in warehouse.
   * @return unqualifiedQuantity
   */
  @javax.annotation.Nullable
  public Long getUnqualifiedQuantity() {
    return unqualifiedQuantity;
  }

  public void setUnqualifiedQuantity(@javax.annotation.Nullable Long unqualifiedQuantity) {
    this.unqualifiedQuantity = unqualifiedQuantity;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders warehouseCode(@javax.annotation.Nullable String warehouseCode) {
    this.warehouseCode = warehouseCode;
    return this;
  }

  /**
   *  warehouse code
   * @return warehouseCode
   */
  @javax.annotation.Nullable
  public String getWarehouseCode() {
    return warehouseCode;
  }

  public void setWarehouseCode(@javax.annotation.Nullable String warehouseCode) {
    this.warehouseCode = warehouseCode;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders warehouseContact(@javax.annotation.Nullable GSSearchDeliveryOrdersResponseDataDeliveryOrdersWarehouseContact warehouseContact) {
    this.warehouseContact = warehouseContact;
    return this;
  }

  /**
   * Get warehouseContact
   * @return warehouseContact
   */
  @javax.annotation.Nullable
  public GSSearchDeliveryOrdersResponseDataDeliveryOrdersWarehouseContact getWarehouseContact() {
    return warehouseContact;
  }

  public void setWarehouseContact(@javax.annotation.Nullable GSSearchDeliveryOrdersResponseDataDeliveryOrdersWarehouseContact warehouseContact) {
    this.warehouseContact = warehouseContact;
  }


  public GSSearchDeliveryOrdersResponseDataDeliveryOrders warehouseName(@javax.annotation.Nullable String warehouseName) {
    this.warehouseName = warehouseName;
    return this;
  }

  /**
   *  warehouse name
   * @return warehouseName
   */
  @javax.annotation.Nullable
  public String getWarehouseName() {
    return warehouseName;
  }

  public void setWarehouseName(@javax.annotation.Nullable String warehouseName) {
    this.warehouseName = warehouseName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GSSearchDeliveryOrdersResponseDataDeliveryOrders instance itself
   */
  public GSSearchDeliveryOrdersResponseDataDeliveryOrders putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GSSearchDeliveryOrdersResponseDataDeliveryOrders gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders = (GSSearchDeliveryOrdersResponseDataDeliveryOrders) o;
    return Objects.equals(this.arrivedTime, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.arrivedTime) &&
        Objects.equals(this.categoryId, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.categoryId) &&
        Objects.equals(this.code, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.code) &&
        Objects.equals(this.deliveryBatchCode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.deliveryBatchCode) &&
        Objects.equals(this.deliveryPackages, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.deliveryPackages) &&
        Objects.equals(this.deliveryQuantity, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.deliveryQuantity) &&
        Objects.equals(this.deliveryType, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.deliveryType) &&
        Objects.equals(this.emergencyLevel, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.emergencyLevel) &&
        Objects.equals(this.inboundQuantity, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.inboundQuantity) &&
        Objects.equals(this.isFirstOrder, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.isFirstOrder) &&
        Objects.equals(this.isSampleIncluded, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.isSampleIncluded) &&
        Objects.equals(this.latestStatusUpdateTime, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.latestStatusUpdateTime) &&
        Objects.equals(this.logistics, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.logistics) &&
        Objects.equals(this.mode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.mode) &&
        Objects.equals(this.platformSpuCode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.platformSpuCode) &&
        Objects.equals(this.predictedArrivedTime, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.predictedArrivedTime) &&
        Objects.equals(this.predictedShipTime, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.predictedShipTime) &&
        Objects.equals(this.qualifiedQuantity, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.qualifiedQuantity) &&
        Objects.equals(this.qualityCheckResult, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.qualityCheckResult) &&
        Objects.equals(this.receivedQuantity, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.receivedQuantity) &&
        Objects.equals(this.relativeCode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.relativeCode) &&
        Objects.equals(this.relativeCodeType, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.relativeCodeType) &&
        Objects.equals(this.requireArrivedTime, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.requireArrivedTime) &&
        Objects.equals(this.returnedQuantity, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.returnedQuantity) &&
        Objects.equals(this.sampleCode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.sampleCode) &&
        Objects.equals(this.sampleStatus, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.sampleStatus) &&
        Objects.equals(this.shipTime, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.shipTime) &&
        Objects.equals(this.skc, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.skc) &&
        Objects.equals(this.skus, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.skus) &&
        Objects.equals(this.status, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.status) &&
        Objects.equals(this.stockupType, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.stockupType) &&
        Objects.equals(this.unqualifiedQuantity, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.unqualifiedQuantity) &&
        Objects.equals(this.warehouseCode, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.warehouseCode) &&
        Objects.equals(this.warehouseContact, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.warehouseContact) &&
        Objects.equals(this.warehouseName, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.warehouseName)&&
        Objects.equals(this.additionalProperties, gsFullServiceShipment202405GSSearchDeliveryOrdersResponseDataDeliveryOrders.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arrivedTime, categoryId, code, deliveryBatchCode, deliveryPackages, deliveryQuantity, deliveryType, emergencyLevel, inboundQuantity, isFirstOrder, isSampleIncluded, latestStatusUpdateTime, logistics, mode, platformSpuCode, predictedArrivedTime, predictedShipTime, qualifiedQuantity, qualityCheckResult, receivedQuantity, relativeCode, relativeCodeType, requireArrivedTime, returnedQuantity, sampleCode, sampleStatus, shipTime, skc, skus, status, stockupType, unqualifiedQuantity, warehouseCode, warehouseContact, warehouseName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GSSearchDeliveryOrdersResponseDataDeliveryOrders {\n");
    sb.append("    arrivedTime: ").append(toIndentedString(arrivedTime)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    deliveryBatchCode: ").append(toIndentedString(deliveryBatchCode)).append("\n");
    sb.append("    deliveryPackages: ").append(toIndentedString(deliveryPackages)).append("\n");
    sb.append("    deliveryQuantity: ").append(toIndentedString(deliveryQuantity)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    emergencyLevel: ").append(toIndentedString(emergencyLevel)).append("\n");
    sb.append("    inboundQuantity: ").append(toIndentedString(inboundQuantity)).append("\n");
    sb.append("    isFirstOrder: ").append(toIndentedString(isFirstOrder)).append("\n");
    sb.append("    isSampleIncluded: ").append(toIndentedString(isSampleIncluded)).append("\n");
    sb.append("    latestStatusUpdateTime: ").append(toIndentedString(latestStatusUpdateTime)).append("\n");
    sb.append("    logistics: ").append(toIndentedString(logistics)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    platformSpuCode: ").append(toIndentedString(platformSpuCode)).append("\n");
    sb.append("    predictedArrivedTime: ").append(toIndentedString(predictedArrivedTime)).append("\n");
    sb.append("    predictedShipTime: ").append(toIndentedString(predictedShipTime)).append("\n");
    sb.append("    qualifiedQuantity: ").append(toIndentedString(qualifiedQuantity)).append("\n");
    sb.append("    qualityCheckResult: ").append(toIndentedString(qualityCheckResult)).append("\n");
    sb.append("    receivedQuantity: ").append(toIndentedString(receivedQuantity)).append("\n");
    sb.append("    relativeCode: ").append(toIndentedString(relativeCode)).append("\n");
    sb.append("    relativeCodeType: ").append(toIndentedString(relativeCodeType)).append("\n");
    sb.append("    requireArrivedTime: ").append(toIndentedString(requireArrivedTime)).append("\n");
    sb.append("    returnedQuantity: ").append(toIndentedString(returnedQuantity)).append("\n");
    sb.append("    sampleCode: ").append(toIndentedString(sampleCode)).append("\n");
    sb.append("    sampleStatus: ").append(toIndentedString(sampleStatus)).append("\n");
    sb.append("    shipTime: ").append(toIndentedString(shipTime)).append("\n");
    sb.append("    skc: ").append(toIndentedString(skc)).append("\n");
    sb.append("    skus: ").append(toIndentedString(skus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    stockupType: ").append(toIndentedString(stockupType)).append("\n");
    sb.append("    unqualifiedQuantity: ").append(toIndentedString(unqualifiedQuantity)).append("\n");
    sb.append("    warehouseCode: ").append(toIndentedString(warehouseCode)).append("\n");
    sb.append("    warehouseContact: ").append(toIndentedString(warehouseContact)).append("\n");
    sb.append("    warehouseName: ").append(toIndentedString(warehouseName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("arrived_time", "category_id", "code", "delivery_batch_code", "delivery_packages", "delivery_quantity", "delivery_type", "emergency_level", "inbound_quantity", "is_first_order", "is_sample_included", "latest_status_update_time", "logistics", "mode", "platform_spu_code", "predicted_arrived_time", "predicted_ship_time", "qualified_quantity", "quality_check_result", "received_quantity", "relative_code", "relative_code_type", "require_arrived_time", "returned_quantity", "sample_code", "sample_status", "ship_time", "skc", "skus", "status", "stockup_type", "unqualified_quantity", "warehouse_code", "warehouse_contact", "warehouse_name"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GSSearchDeliveryOrdersResponseDataDeliveryOrders
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GSSearchDeliveryOrdersResponseDataDeliveryOrders.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GSSearchDeliveryOrdersResponseDataDeliveryOrders is not found in the empty JSON string", GSSearchDeliveryOrdersResponseDataDeliveryOrders.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("category_id") != null && !jsonObj.get("category_id").isJsonNull()) && !jsonObj.get("category_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category_id").toString()));
      }
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if ((jsonObj.get("delivery_batch_code") != null && !jsonObj.get("delivery_batch_code").isJsonNull()) && !jsonObj.get("delivery_batch_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_batch_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_batch_code").toString()));
      }
      if (jsonObj.get("delivery_packages") != null && !jsonObj.get("delivery_packages").isJsonNull()) {
        JsonArray jsonArraydeliveryPackages = jsonObj.getAsJsonArray("delivery_packages");
        if (jsonArraydeliveryPackages != null) {
          // ensure the json data is an array
          if (!jsonObj.get("delivery_packages").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `delivery_packages` to be an array in the JSON string but got `%s`", jsonObj.get("delivery_packages").toString()));
          }

          // validate the optional field `delivery_packages` (array)
          for (int i = 0; i < jsonArraydeliveryPackages.size(); i++) {
            GSSearchDeliveryOrdersResponseDataDeliveryOrdersDeliveryPackages.validateJsonElement(jsonArraydeliveryPackages.get(i));
          };
        }
      }
      if ((jsonObj.get("delivery_type") != null && !jsonObj.get("delivery_type").isJsonNull()) && !jsonObj.get("delivery_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_type").toString()));
      }
      if ((jsonObj.get("emergency_level") != null && !jsonObj.get("emergency_level").isJsonNull()) && !jsonObj.get("emergency_level").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `emergency_level` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emergency_level").toString()));
      }
      // validate the optional field `logistics`
      if (jsonObj.get("logistics") != null && !jsonObj.get("logistics").isJsonNull()) {
        GSSearchDeliveryOrdersResponseDataDeliveryOrdersLogistics.validateJsonElement(jsonObj.get("logistics"));
      }
      if ((jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) && !jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      if ((jsonObj.get("platform_spu_code") != null && !jsonObj.get("platform_spu_code").isJsonNull()) && !jsonObj.get("platform_spu_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `platform_spu_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform_spu_code").toString()));
      }
      if ((jsonObj.get("quality_check_result") != null && !jsonObj.get("quality_check_result").isJsonNull()) && !jsonObj.get("quality_check_result").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `quality_check_result` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quality_check_result").toString()));
      }
      if ((jsonObj.get("relative_code") != null && !jsonObj.get("relative_code").isJsonNull()) && !jsonObj.get("relative_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relative_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relative_code").toString()));
      }
      if ((jsonObj.get("relative_code_type") != null && !jsonObj.get("relative_code_type").isJsonNull()) && !jsonObj.get("relative_code_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relative_code_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relative_code_type").toString()));
      }
      if ((jsonObj.get("sample_code") != null && !jsonObj.get("sample_code").isJsonNull()) && !jsonObj.get("sample_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sample_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sample_code").toString()));
      }
      if ((jsonObj.get("sample_status") != null && !jsonObj.get("sample_status").isJsonNull()) && !jsonObj.get("sample_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sample_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sample_status").toString()));
      }
      // validate the optional field `skc`
      if (jsonObj.get("skc") != null && !jsonObj.get("skc").isJsonNull()) {
        GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkc.validateJsonElement(jsonObj.get("skc"));
      }
      if (jsonObj.get("skus") != null && !jsonObj.get("skus").isJsonNull()) {
        JsonArray jsonArrayskus = jsonObj.getAsJsonArray("skus");
        if (jsonArrayskus != null) {
          // ensure the json data is an array
          if (!jsonObj.get("skus").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `skus` to be an array in the JSON string but got `%s`", jsonObj.get("skus").toString()));
          }

          // validate the optional field `skus` (array)
          for (int i = 0; i < jsonArrayskus.size(); i++) {
            GSSearchDeliveryOrdersResponseDataDeliveryOrdersSkus.validateJsonElement(jsonArrayskus.get(i));
          };
        }
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("stockup_type") != null && !jsonObj.get("stockup_type").isJsonNull()) && !jsonObj.get("stockup_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stockup_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stockup_type").toString()));
      }
      if ((jsonObj.get("warehouse_code") != null && !jsonObj.get("warehouse_code").isJsonNull()) && !jsonObj.get("warehouse_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `warehouse_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("warehouse_code").toString()));
      }
      // validate the optional field `warehouse_contact`
      if (jsonObj.get("warehouse_contact") != null && !jsonObj.get("warehouse_contact").isJsonNull()) {
        GSSearchDeliveryOrdersResponseDataDeliveryOrdersWarehouseContact.validateJsonElement(jsonObj.get("warehouse_contact"));
      }
      if ((jsonObj.get("warehouse_name") != null && !jsonObj.get("warehouse_name").isJsonNull()) && !jsonObj.get("warehouse_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `warehouse_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("warehouse_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GSSearchDeliveryOrdersResponseDataDeliveryOrders.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GSSearchDeliveryOrdersResponseDataDeliveryOrders' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GSSearchDeliveryOrdersResponseDataDeliveryOrders> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GSSearchDeliveryOrdersResponseDataDeliveryOrders.class));

       return (TypeAdapter<T>) new TypeAdapter<GSSearchDeliveryOrdersResponseDataDeliveryOrders>() {
           @Override
           public void write(JsonWriter out, GSSearchDeliveryOrdersResponseDataDeliveryOrders value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GSSearchDeliveryOrdersResponseDataDeliveryOrders read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GSSearchDeliveryOrdersResponseDataDeliveryOrders instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GSSearchDeliveryOrdersResponseDataDeliveryOrders given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GSSearchDeliveryOrdersResponseDataDeliveryOrders
   * @throws IOException if the JSON string is invalid with respect to GSSearchDeliveryOrdersResponseDataDeliveryOrders
   */
  public static GSSearchDeliveryOrdersResponseDataDeliveryOrders fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GSSearchDeliveryOrdersResponseDataDeliveryOrders.class);
  }

  /**
   * Convert an instance of GSSearchDeliveryOrdersResponseDataDeliveryOrders to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

