/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.api;

import tiktokshop.open.sdk_java.invoke.ApiException;
import tiktokshop.open.sdk_java.model.DataReconciliation.V202310.QualityFactoryOrderDataImportAPIRequestBody;
import tiktokshop.open.sdk_java.model.DataReconciliation.V202310.QualityFactoryOrderDataImportAPIResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataReconciliationV202310Api
 */
@Disabled
public class DataReconciliationV202310ApiTest {

    private final DataReconciliationV202310Api api = new DataReconciliationV202310Api();

    /**
     * QualityFactoryOrderDataImportAPI
     *
     * TikTok Shop-Connector exchange order data from DTC(Direct To Consumer) platform to Tiktok Shop-QE system to compare the order data of DTC platform and Tiktok Shop. Which systems of users are involved with the API? For example, DTC platform Connector App, Shipping App, WMS, PIM, Multi Channel App, etc.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void dataReconciliation202310OrdersImportPostTest() throws ApiException {
        String xTtsAccessToken = null;
        String contentType = null;
        String shopCipher = null;
        QualityFactoryOrderDataImportAPIRequestBody dataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody = null;
        QualityFactoryOrderDataImportAPIResponse response = api.dataReconciliation202310OrdersImportPost(xTtsAccessToken, contentType, shopCipher, dataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody);
        // TODO: test validations
    }

}
