/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.api;

import tiktokshop.open.sdk_java.invoke.ApiException;
import tiktokshop.open.sdk_java.model.Product.V202404.OptimizedImagesRequestBody;
import tiktokshop.open.sdk_java.model.Product.V202404.OptimizedImagesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductV202404Api
 */
@Disabled
public class ProductV202404ApiTest {

    private final ProductV202404Api api = new ProductV202404Api();

    /**
     * OptimizedImages
     *
     * Optimize images used in your TikTok Shop by changing the background to white. This is especially useful for images displayed in the product image gallery as it enhances product visibility.  **Note**:  - The images to be optimized must first be uploaded to TikTok Shop through the [Upload Product Image API](https://partner.tiktokshop.com/docv2/page/6509df95defece02be598a22). You will not be able to optimize any images that are not hosted by TikTok Shop. - Images that were previously optimized will not be processed again. - The optimization is processed asynchronously and typically completes within a few seconds. Therefore, the &#x60;optimize_status&#x60; returned in the first API request for an image is always &#x60;PROCESSING&#x60;, indicating that optimization is underway. Please call the API again after a few seconds to get the final optimization status.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void product202404ImagesOptimizePostTest() throws ApiException {
        String xTtsAccessToken = null;
        String contentType = null;
        String shopCipher = null;
        OptimizedImagesRequestBody product202404OptimizedImagesRequestBody = null;
        OptimizedImagesResponse response = api.product202404ImagesOptimizePost(xTtsAccessToken, contentType, shopCipher, product202404OptimizedImagesRequestBody);
        // TODO: test validations
    }

}
