/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.Product.V202409;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import tiktokshop.open.sdk_java.model.Product.V202409.SearchResponsiblePersonsResponseDataResponsiblePersons;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * SearchResponsiblePersonsResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-30T06:06:20.240402Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class SearchResponsiblePersonsResponseData {
  public static final String SERIALIZED_NAME_NEXT_PAGE_TOKEN = "next_page_token";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE_TOKEN)
  private String nextPageToken;

  public static final String SERIALIZED_NAME_RESPONSIBLE_PERSONS = "responsible_persons";
  @SerializedName(SERIALIZED_NAME_RESPONSIBLE_PERSONS)
  private List<SearchResponsiblePersonsResponseDataResponsiblePersons> responsiblePersons = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "total_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private Long totalCount;

  public SearchResponsiblePersonsResponseData() {
  }

  public SearchResponsiblePersonsResponseData nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * An opaque token used to retrieve the next page of a paginated result set. Provide this value in the &#x60;page_token&#x60; parameter of your request if the current response does not return all the results.
   * @return nextPageToken
  **/
  @javax.annotation.Nullable
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  public SearchResponsiblePersonsResponseData responsiblePersons(List<SearchResponsiblePersonsResponseDataResponsiblePersons> responsiblePersons) {
    this.responsiblePersons = responsiblePersons;
    return this;
  }

  public SearchResponsiblePersonsResponseData addResponsiblePersonsItem(SearchResponsiblePersonsResponseDataResponsiblePersons responsiblePersonsItem) {
    if (this.responsiblePersons == null) {
      this.responsiblePersons = new ArrayList<>();
    }
    this.responsiblePersons.add(responsiblePersonsItem);
    return this;
  }

   /**
   * The list of responsible persons that meet the query conditions.
   * @return responsiblePersons
  **/
  @javax.annotation.Nullable
  public List<SearchResponsiblePersonsResponseDataResponsiblePersons> getResponsiblePersons() {
    return responsiblePersons;
  }

  public void setResponsiblePersons(List<SearchResponsiblePersonsResponseDataResponsiblePersons> responsiblePersons) {
    this.responsiblePersons = responsiblePersons;
  }


  public SearchResponsiblePersonsResponseData totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * The number of responsible persons that meet the query conditions.
   * @return totalCount
  **/
  @javax.annotation.Nullable
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponsiblePersonsResponseData product202409SearchResponsiblePersonsResponseData = (SearchResponsiblePersonsResponseData) o;
    return Objects.equals(this.nextPageToken, product202409SearchResponsiblePersonsResponseData.nextPageToken) &&
        Objects.equals(this.responsiblePersons, product202409SearchResponsiblePersonsResponseData.responsiblePersons) &&
        Objects.equals(this.totalCount, product202409SearchResponsiblePersonsResponseData.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextPageToken, responsiblePersons, totalCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponsiblePersonsResponseData {\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("    responsiblePersons: ").append(toIndentedString(responsiblePersons)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("next_page_token");
    openapiFields.add("responsible_persons");
    openapiFields.add("total_count");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SearchResponsiblePersonsResponseData
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchResponsiblePersonsResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchResponsiblePersonsResponseData is not found in the empty JSON string", SearchResponsiblePersonsResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchResponsiblePersonsResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchResponsiblePersonsResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("next_page_token") != null && !jsonObj.get("next_page_token").isJsonNull()) && !jsonObj.get("next_page_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `next_page_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("next_page_token").toString()));
      }
      if (jsonObj.get("responsible_persons") != null && !jsonObj.get("responsible_persons").isJsonNull()) {
        JsonArray jsonArrayresponsiblePersons = jsonObj.getAsJsonArray("responsible_persons");
        if (jsonArrayresponsiblePersons != null) {
          // ensure the json data is an array
          if (!jsonObj.get("responsible_persons").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `responsible_persons` to be an array in the JSON string but got `%s`", jsonObj.get("responsible_persons").toString()));
          }

          // validate the optional field `responsible_persons` (array)
          for (int i = 0; i < jsonArrayresponsiblePersons.size(); i++) {
            SearchResponsiblePersonsResponseDataResponsiblePersons.validateJsonElement(jsonArrayresponsiblePersons.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchResponsiblePersonsResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchResponsiblePersonsResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchResponsiblePersonsResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchResponsiblePersonsResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchResponsiblePersonsResponseData>() {
           @Override
           public void write(JsonWriter out, SearchResponsiblePersonsResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchResponsiblePersonsResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SearchResponsiblePersonsResponseData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SearchResponsiblePersonsResponseData
  * @throws IOException if the JSON string is invalid with respect to SearchResponsiblePersonsResponseData
  */
  public static SearchResponsiblePersonsResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchResponsiblePersonsResponseData.class);
  }

 /**
  * Convert an instance of SearchResponsiblePersonsResponseData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

