/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.GsFullServiceShipment.V202407;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * GlobalSellingGetQualityDocumentsResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-30T06:06:20.240402Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class GlobalSellingGetQualityDocumentsResponseData {
  public static final String SERIALIZED_NAME_DOCUMENT_URL = "document_url";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_URL)
  private String documentUrl;

  public GlobalSellingGetQualityDocumentsResponseData() {
  }

  public GlobalSellingGetQualityDocumentsResponseData documentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
    return this;
  }

   /**
   * The url of a printable pdf document of quality check results.
   * @return documentUrl
  **/
  @javax.annotation.Nullable
  public String getDocumentUrl() {
    return documentUrl;
  }

  public void setDocumentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalSellingGetQualityDocumentsResponseData gsFullServiceShipment202407GlobalSellingGetQualityDocumentsResponseData = (GlobalSellingGetQualityDocumentsResponseData) o;
    return Objects.equals(this.documentUrl, gsFullServiceShipment202407GlobalSellingGetQualityDocumentsResponseData.documentUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalSellingGetQualityDocumentsResponseData {\n");
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("document_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GlobalSellingGetQualityDocumentsResponseData
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GlobalSellingGetQualityDocumentsResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GlobalSellingGetQualityDocumentsResponseData is not found in the empty JSON string", GlobalSellingGetQualityDocumentsResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GlobalSellingGetQualityDocumentsResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GlobalSellingGetQualityDocumentsResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("document_url") != null && !jsonObj.get("document_url").isJsonNull()) && !jsonObj.get("document_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `document_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("document_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GlobalSellingGetQualityDocumentsResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GlobalSellingGetQualityDocumentsResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GlobalSellingGetQualityDocumentsResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GlobalSellingGetQualityDocumentsResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<GlobalSellingGetQualityDocumentsResponseData>() {
           @Override
           public void write(JsonWriter out, GlobalSellingGetQualityDocumentsResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GlobalSellingGetQualityDocumentsResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GlobalSellingGetQualityDocumentsResponseData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GlobalSellingGetQualityDocumentsResponseData
  * @throws IOException if the JSON string is invalid with respect to GlobalSellingGetQualityDocumentsResponseData
  */
  public static GlobalSellingGetQualityDocumentsResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GlobalSellingGetQualityDocumentsResponseData.class);
  }

 /**
  * Convert an instance of GlobalSellingGetQualityDocumentsResponseData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

