/*
 * Amazon Ads API SB
 * Amazon Advertising API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hzltd.module.erplus.adv.adapter.amazon.model.sb;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hzltd.module.erplus.adv.adapter.amazon.model.sb.SBUpdateAutoCollectionSettings;
import com.hzltd.module.erplus.adv.adapter.amazon.model.sb.SBUpdateManualCollectionSettings;
import com.hzltd.module.erplus.adv.adapter.amazon.model.sb.SBUpdateProductCollectionSettings;
import com.hzltd.module.erplus.adv.adapter.amazon.model.sb.SBUpdateProductVideoSettings;
import com.hzltd.module.erplus.adv.adapter.amazon.model.sb.SBUpdateStoreSpotlightSettings;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SBUpdateComponentCreative
 */
@JsonPropertyOrder({
  SBUpdateComponentCreative.JSON_PROPERTY_AUTO_COLLECTION_SETTINGS,
  SBUpdateComponentCreative.JSON_PROPERTY_MANUAL_COLLECTION_SETTINGS,
  SBUpdateComponentCreative.JSON_PROPERTY_PRODUCT_COLLECTION_SETTINGS,
  SBUpdateComponentCreative.JSON_PROPERTY_PRODUCT_VIDEO_SETTINGS,
  SBUpdateComponentCreative.JSON_PROPERTY_STORE_SPOTLIGHT_SETTINGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-22T09:29:15.693761+08:00[Asia/Shanghai]")
public class SBUpdateComponentCreative {
  public static final String JSON_PROPERTY_AUTO_COLLECTION_SETTINGS = "autoCollectionSettings";
  private SBUpdateAutoCollectionSettings autoCollectionSettings;

  public static final String JSON_PROPERTY_MANUAL_COLLECTION_SETTINGS = "manualCollectionSettings";
  private SBUpdateManualCollectionSettings manualCollectionSettings;

  public static final String JSON_PROPERTY_PRODUCT_COLLECTION_SETTINGS = "productCollectionSettings";
  private SBUpdateProductCollectionSettings productCollectionSettings;

  public static final String JSON_PROPERTY_PRODUCT_VIDEO_SETTINGS = "productVideoSettings";
  private SBUpdateProductVideoSettings productVideoSettings;

  public static final String JSON_PROPERTY_STORE_SPOTLIGHT_SETTINGS = "storeSpotlightSettings";
  private SBUpdateStoreSpotlightSettings storeSpotlightSettings;

  public SBUpdateComponentCreative() { 
  }

  public SBUpdateComponentCreative autoCollectionSettings(SBUpdateAutoCollectionSettings autoCollectionSettings) {
    this.autoCollectionSettings = autoCollectionSettings;
    return this;
  }

   /**
   * Get autoCollectionSettings
   * @return autoCollectionSettings
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTO_COLLECTION_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SBUpdateAutoCollectionSettings getAutoCollectionSettings() {
    return autoCollectionSettings;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_COLLECTION_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoCollectionSettings(SBUpdateAutoCollectionSettings autoCollectionSettings) {
    this.autoCollectionSettings = autoCollectionSettings;
  }


  public SBUpdateComponentCreative manualCollectionSettings(SBUpdateManualCollectionSettings manualCollectionSettings) {
    this.manualCollectionSettings = manualCollectionSettings;
    return this;
  }

   /**
   * Get manualCollectionSettings
   * @return manualCollectionSettings
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANUAL_COLLECTION_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SBUpdateManualCollectionSettings getManualCollectionSettings() {
    return manualCollectionSettings;
  }


  @JsonProperty(JSON_PROPERTY_MANUAL_COLLECTION_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManualCollectionSettings(SBUpdateManualCollectionSettings manualCollectionSettings) {
    this.manualCollectionSettings = manualCollectionSettings;
  }


  public SBUpdateComponentCreative productCollectionSettings(SBUpdateProductCollectionSettings productCollectionSettings) {
    this.productCollectionSettings = productCollectionSettings;
    return this;
  }

   /**
   * Get productCollectionSettings
   * @return productCollectionSettings
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT_COLLECTION_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SBUpdateProductCollectionSettings getProductCollectionSettings() {
    return productCollectionSettings;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_COLLECTION_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductCollectionSettings(SBUpdateProductCollectionSettings productCollectionSettings) {
    this.productCollectionSettings = productCollectionSettings;
  }


  public SBUpdateComponentCreative productVideoSettings(SBUpdateProductVideoSettings productVideoSettings) {
    this.productVideoSettings = productVideoSettings;
    return this;
  }

   /**
   * Get productVideoSettings
   * @return productVideoSettings
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT_VIDEO_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SBUpdateProductVideoSettings getProductVideoSettings() {
    return productVideoSettings;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_VIDEO_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductVideoSettings(SBUpdateProductVideoSettings productVideoSettings) {
    this.productVideoSettings = productVideoSettings;
  }


  public SBUpdateComponentCreative storeSpotlightSettings(SBUpdateStoreSpotlightSettings storeSpotlightSettings) {
    this.storeSpotlightSettings = storeSpotlightSettings;
    return this;
  }

   /**
   * Get storeSpotlightSettings
   * @return storeSpotlightSettings
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STORE_SPOTLIGHT_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SBUpdateStoreSpotlightSettings getStoreSpotlightSettings() {
    return storeSpotlightSettings;
  }


  @JsonProperty(JSON_PROPERTY_STORE_SPOTLIGHT_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoreSpotlightSettings(SBUpdateStoreSpotlightSettings storeSpotlightSettings) {
    this.storeSpotlightSettings = storeSpotlightSettings;
  }


  /**
   * Return true if this SBUpdateComponentCreative object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SBUpdateComponentCreative sbUpdateComponentCreative = (SBUpdateComponentCreative) o;
    return Objects.equals(this.autoCollectionSettings, sbUpdateComponentCreative.autoCollectionSettings) &&
        Objects.equals(this.manualCollectionSettings, sbUpdateComponentCreative.manualCollectionSettings) &&
        Objects.equals(this.productCollectionSettings, sbUpdateComponentCreative.productCollectionSettings) &&
        Objects.equals(this.productVideoSettings, sbUpdateComponentCreative.productVideoSettings) &&
        Objects.equals(this.storeSpotlightSettings, sbUpdateComponentCreative.storeSpotlightSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoCollectionSettings, manualCollectionSettings, productCollectionSettings, productVideoSettings, storeSpotlightSettings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SBUpdateComponentCreative {\n");
    sb.append("    autoCollectionSettings: ").append(toIndentedString(autoCollectionSettings)).append("\n");
    sb.append("    manualCollectionSettings: ").append(toIndentedString(manualCollectionSettings)).append("\n");
    sb.append("    productCollectionSettings: ").append(toIndentedString(productCollectionSettings)).append("\n");
    sb.append("    productVideoSettings: ").append(toIndentedString(productVideoSettings)).append("\n");
    sb.append("    storeSpotlightSettings: ").append(toIndentedString(storeSpotlightSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `autoCollectionSettings` to the URL query string
    if (getAutoCollectionSettings() != null) {
      joiner.add(getAutoCollectionSettings().toUrlQueryString(prefix + "autoCollectionSettings" + suffix));
    }

    // add `manualCollectionSettings` to the URL query string
    if (getManualCollectionSettings() != null) {
      joiner.add(getManualCollectionSettings().toUrlQueryString(prefix + "manualCollectionSettings" + suffix));
    }

    // add `productCollectionSettings` to the URL query string
    if (getProductCollectionSettings() != null) {
      joiner.add(getProductCollectionSettings().toUrlQueryString(prefix + "productCollectionSettings" + suffix));
    }

    // add `productVideoSettings` to the URL query string
    if (getProductVideoSettings() != null) {
      joiner.add(getProductVideoSettings().toUrlQueryString(prefix + "productVideoSettings" + suffix));
    }

    // add `storeSpotlightSettings` to the URL query string
    if (getStoreSpotlightSettings() != null) {
      joiner.add(getStoreSpotlightSettings().toUrlQueryString(prefix + "storeSpotlightSettings" + suffix));
    }

    return joiner.toString();
  }
}

