/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.api;

import tiktokshop.open.sdk_java.invoke.ApiCallback;
import tiktokshop.open.sdk_java.invoke.ApiClient;
import tiktokshop.open.sdk_java.invoke.ApiException;
import tiktokshop.open.sdk_java.invoke.ApiResponse;
import tiktokshop.open.sdk_java.invoke.Configuration;
import tiktokshop.open.sdk_java.invoke.Pair;
import tiktokshop.open.sdk_java.invoke.ProgressRequestBody;
import tiktokshop.open.sdk_java.invoke.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import tiktokshop.open.sdk_java.model.Finance.V202309.GetPaymentsResponse;
import tiktokshop.open.sdk_java.model.Finance.V202309.GetStatementsResponse;
import tiktokshop.open.sdk_java.model.Finance.V202309.GetTransactionsbyOrderResponse;
import tiktokshop.open.sdk_java.model.Finance.V202309.GetTransactionsbyStatementResponse;
import tiktokshop.open.sdk_java.model.Finance.V202309.GetWithdrawalsResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FinanceV202309Api {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public FinanceV202309Api() {
        this(Configuration.getDefaultApiClient());
    }

    public FinanceV202309Api(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for finance202309OrdersOrderIdStatementTransactionsGet
     * @param orderId The order ID in TikTok Shop. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309OrdersOrderIdStatementTransactionsGetCall(@javax.annotation.Nonnull String orderId, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/finance/202309/orders/{order_id}/statement_transactions"
            .replace("{" + "order_id" + "}", localVarApiClient.escapeString(orderId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (shopCipher != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shop_cipher", shopCipher));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xTtsAccessToken != null) {
            localVarHeaderParams.put("x-tts-access-token", localVarApiClient.parameterToString(xTtsAccessToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call finance202309OrdersOrderIdStatementTransactionsGetValidateBeforeCall(@javax.annotation.Nonnull String orderId, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orderId' is set
        if (orderId == null) {
            throw new ApiException("Missing the required parameter 'orderId' when calling finance202309OrdersOrderIdStatementTransactionsGet(Async)");
        }

        // verify the required parameter 'xTtsAccessToken' is set
        if (xTtsAccessToken == null) {
            throw new ApiException("Missing the required parameter 'xTtsAccessToken' when calling finance202309OrdersOrderIdStatementTransactionsGet(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling finance202309OrdersOrderIdStatementTransactionsGet(Async)");
        }

        return finance202309OrdersOrderIdStatementTransactionsGetCall(orderId, xTtsAccessToken, contentType, shopCipher, _callback);

    }

    /**
     * GetTransactionsbyOrder
     * **This API is currently exclusive to the following markets: US, UK.** Retrieves the transactions associated with an order, including both order-level transactions and SKU-level detailed transactions. This covers all transactions related to sales, fees, commissions, shipping, taxes, adjustments, and refunds.
     * @param orderId The order ID in TikTok Shop. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @return GetTransactionsbyOrderResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public GetTransactionsbyOrderResponse finance202309OrdersOrderIdStatementTransactionsGet(@javax.annotation.Nonnull String orderId, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher) throws ApiException {
        ApiResponse<GetTransactionsbyOrderResponse> localVarResp = finance202309OrdersOrderIdStatementTransactionsGetWithHttpInfo(orderId, xTtsAccessToken, contentType, shopCipher);
        return localVarResp.getData();
    }

    /**
     * GetTransactionsbyOrder
     * **This API is currently exclusive to the following markets: US, UK.** Retrieves the transactions associated with an order, including both order-level transactions and SKU-level detailed transactions. This covers all transactions related to sales, fees, commissions, shipping, taxes, adjustments, and refunds.
     * @param orderId The order ID in TikTok Shop. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @return ApiResponse&lt;GetTransactionsbyOrderResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetTransactionsbyOrderResponse> finance202309OrdersOrderIdStatementTransactionsGetWithHttpInfo(@javax.annotation.Nonnull String orderId, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher) throws ApiException {
        okhttp3.Call localVarCall = finance202309OrdersOrderIdStatementTransactionsGetValidateBeforeCall(orderId, xTtsAccessToken, contentType, shopCipher, null);
        Type localVarReturnType = new TypeToken<GetTransactionsbyOrderResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * GetTransactionsbyOrder (asynchronously)
     * **This API is currently exclusive to the following markets: US, UK.** Retrieves the transactions associated with an order, including both order-level transactions and SKU-level detailed transactions. This covers all transactions related to sales, fees, commissions, shipping, taxes, adjustments, and refunds.
     * @param orderId The order ID in TikTok Shop. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309OrdersOrderIdStatementTransactionsGetAsync(@javax.annotation.Nonnull String orderId, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, final ApiCallback<GetTransactionsbyOrderResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = finance202309OrdersOrderIdStatementTransactionsGetValidateBeforeCall(orderId, xTtsAccessToken, contentType, shopCipher, _callback);
        Type localVarReturnType = new TypeToken<GetTransactionsbyOrderResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for finance202309PaymentsGet
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;create_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Filter payments to show only those that occurred before the specified date and time. Unix timestamp. Refer to notes in &#x60;create_time_ge&#x60; for more usage information. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param createTimeGe Filter payments to show only those that occurred on or after the specified date and time. Unix timestamp.  **Note:** &#x60;create_time_ge&#x60; and &#x60;create_time_lt&#x60; together constitute the creation time filter condition. - If &#x60;create_time_ge&#x60; is filled but &#x60;create_time_lt&#x60; is empty, &#x60;create_time_lt&#x60; will default to the current time. - If &#x60;create_time_lt&#x60; is filled but &#x60;create_time_ge&#x60; is empty, &#x60;create_time_ge&#x60; will default to the earliest shop time. (optional)
     * @param shopCipher  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309PaymentsGetCall(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/finance/202309/payments";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (createTimeLt != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("create_time_lt", createTimeLt));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        if (pageToken != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_token", pageToken));
        }

        if (sortField != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort_field", sortField));
        }

        if (sortOrder != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort_order", sortOrder));
        }

        if (createTimeGe != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("create_time_ge", createTimeGe));
        }

        if (shopCipher != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shop_cipher", shopCipher));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xTtsAccessToken != null) {
            localVarHeaderParams.put("x-tts-access-token", localVarApiClient.parameterToString(xTtsAccessToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call finance202309PaymentsGetValidateBeforeCall(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sortField' is set
        if (sortField == null) {
            throw new ApiException("Missing the required parameter 'sortField' when calling finance202309PaymentsGet(Async)");
        }

        // verify the required parameter 'xTtsAccessToken' is set
        if (xTtsAccessToken == null) {
            throw new ApiException("Missing the required parameter 'xTtsAccessToken' when calling finance202309PaymentsGet(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling finance202309PaymentsGet(Async)");
        }

        return finance202309PaymentsGetCall(sortField, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, sortOrder, createTimeGe, shopCipher, _callback);

    }

    /**
     * GetPayments
     * **This API is currently unavailable to SEA markets.** Retrieves records of automated payments for a shop based on a specified date range. Use the returned list to verify and reconcile payments with the transactions in the seller&#39;s bank account.
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;create_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Filter payments to show only those that occurred before the specified date and time. Unix timestamp. Refer to notes in &#x60;create_time_ge&#x60; for more usage information. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param createTimeGe Filter payments to show only those that occurred on or after the specified date and time. Unix timestamp.  **Note:** &#x60;create_time_ge&#x60; and &#x60;create_time_lt&#x60; together constitute the creation time filter condition. - If &#x60;create_time_ge&#x60; is filled but &#x60;create_time_lt&#x60; is empty, &#x60;create_time_lt&#x60; will default to the current time. - If &#x60;create_time_lt&#x60; is filled but &#x60;create_time_ge&#x60; is empty, &#x60;create_time_ge&#x60; will default to the earliest shop time. (optional)
     * @param shopCipher  (optional)
     * @return GetPaymentsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public GetPaymentsResponse finance202309PaymentsGet(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher) throws ApiException {
        ApiResponse<GetPaymentsResponse> localVarResp = finance202309PaymentsGetWithHttpInfo(sortField, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, sortOrder, createTimeGe, shopCipher);
        return localVarResp.getData();
    }

    /**
     * GetPayments
     * **This API is currently unavailable to SEA markets.** Retrieves records of automated payments for a shop based on a specified date range. Use the returned list to verify and reconcile payments with the transactions in the seller&#39;s bank account.
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;create_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Filter payments to show only those that occurred before the specified date and time. Unix timestamp. Refer to notes in &#x60;create_time_ge&#x60; for more usage information. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param createTimeGe Filter payments to show only those that occurred on or after the specified date and time. Unix timestamp.  **Note:** &#x60;create_time_ge&#x60; and &#x60;create_time_lt&#x60; together constitute the creation time filter condition. - If &#x60;create_time_ge&#x60; is filled but &#x60;create_time_lt&#x60; is empty, &#x60;create_time_lt&#x60; will default to the current time. - If &#x60;create_time_lt&#x60; is filled but &#x60;create_time_ge&#x60; is empty, &#x60;create_time_ge&#x60; will default to the earliest shop time. (optional)
     * @param shopCipher  (optional)
     * @return ApiResponse&lt;GetPaymentsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetPaymentsResponse> finance202309PaymentsGetWithHttpInfo(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher) throws ApiException {
        okhttp3.Call localVarCall = finance202309PaymentsGetValidateBeforeCall(sortField, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, sortOrder, createTimeGe, shopCipher, null);
        Type localVarReturnType = new TypeToken<GetPaymentsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * GetPayments (asynchronously)
     * **This API is currently unavailable to SEA markets.** Retrieves records of automated payments for a shop based on a specified date range. Use the returned list to verify and reconcile payments with the transactions in the seller&#39;s bank account.
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;create_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Filter payments to show only those that occurred before the specified date and time. Unix timestamp. Refer to notes in &#x60;create_time_ge&#x60; for more usage information. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param createTimeGe Filter payments to show only those that occurred on or after the specified date and time. Unix timestamp.  **Note:** &#x60;create_time_ge&#x60; and &#x60;create_time_lt&#x60; together constitute the creation time filter condition. - If &#x60;create_time_ge&#x60; is filled but &#x60;create_time_lt&#x60; is empty, &#x60;create_time_lt&#x60; will default to the current time. - If &#x60;create_time_lt&#x60; is filled but &#x60;create_time_ge&#x60; is empty, &#x60;create_time_ge&#x60; will default to the earliest shop time. (optional)
     * @param shopCipher  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309PaymentsGetAsync(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback<GetPaymentsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = finance202309PaymentsGetValidateBeforeCall(sortField, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, sortOrder, createTimeGe, shopCipher, _callback);
        Type localVarReturnType = new TypeToken<GetPaymentsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for finance202309StatementsGet
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;statement_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param statementTimeLt Filter statements to show only those that are generated before the specified date and time. Unix timestamp. Refer to notes in &#x60;statement_time_ge&#x60; for more usage information. (optional)
     * @param paymentStatus Filter statements based on the payment status. Possible values: - PAID: Payment has been transferred to the seller. - FAILED: Payment transfer failed. - PROCESSING: Payment is currently being processed. Default: All statuses are returned. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param statementTimeGe Filter statements to show only those that are generated on or after the specified date and time. Unix timestamp.  **Note:** &#x60;statement_time_ge&#x60; and &#x60;statement_time_le&#x60; together constitute the creation time filter condition. - If &#x60;statement_time_ge&#x60; is filled but &#x60;statement_time_lt&#x60; is empty, &#x60;statement_time_lt&#x60; will default to the current time. - If &#x60;statement_time_lt&#x60; is filled but &#x60;statement_time_ge&#x60; is empty, &#x60;statement_time_ge&#x60; will default to the earliest shop time.  **Example:** As statements are generated daily at 00:00 UTC, to retrieve statements for the period from Oct 5 to Oct 10, configure the parameters as follows: - Set &#x60;statement_time_ge&#x60; to 00:00 on Oct 6  or any time on Oct 5 (excluding 00:00). - Set &#x60;statement_time_lt&#x60; to any time on Oct 11 (excluding 00:00). (optional)
     * @param shopCipher  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309StatementsGetCall(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long statementTimeLt, @javax.annotation.Nullable String paymentStatus, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long statementTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/finance/202309/statements";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (statementTimeLt != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("statement_time_lt", statementTimeLt));
        }

        if (paymentStatus != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("payment_status", paymentStatus));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        if (pageToken != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_token", pageToken));
        }

        if (sortField != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort_field", sortField));
        }

        if (sortOrder != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort_order", sortOrder));
        }

        if (statementTimeGe != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("statement_time_ge", statementTimeGe));
        }

        if (shopCipher != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shop_cipher", shopCipher));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xTtsAccessToken != null) {
            localVarHeaderParams.put("x-tts-access-token", localVarApiClient.parameterToString(xTtsAccessToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call finance202309StatementsGetValidateBeforeCall(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long statementTimeLt, @javax.annotation.Nullable String paymentStatus, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long statementTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sortField' is set
        if (sortField == null) {
            throw new ApiException("Missing the required parameter 'sortField' when calling finance202309StatementsGet(Async)");
        }

        // verify the required parameter 'xTtsAccessToken' is set
        if (xTtsAccessToken == null) {
            throw new ApiException("Missing the required parameter 'xTtsAccessToken' when calling finance202309StatementsGet(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling finance202309StatementsGet(Async)");
        }

        return finance202309StatementsGetCall(sortField, xTtsAccessToken, contentType, statementTimeLt, paymentStatus, pageSize, pageToken, sortOrder, statementTimeGe, shopCipher, _callback);

    }

    /**
     * GetStatements
     * Retrieves the statements generated for a shop and the key statement information based on a specified date range or their payment status. Use this API to get an overview of your daily statements over a range of time, or to find out which statements have been paid or not. For the detailed transactions, refer to [Get Statement Transactions](650a6749defece02be67da87) or [Get Order Statement Transactions](650a6734defece02be67d724). Applicable for all regions&#39; sellers. Only data after 2023-07-01 is available.
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;statement_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param statementTimeLt Filter statements to show only those that are generated before the specified date and time. Unix timestamp. Refer to notes in &#x60;statement_time_ge&#x60; for more usage information. (optional)
     * @param paymentStatus Filter statements based on the payment status. Possible values: - PAID: Payment has been transferred to the seller. - FAILED: Payment transfer failed. - PROCESSING: Payment is currently being processed. Default: All statuses are returned. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param statementTimeGe Filter statements to show only those that are generated on or after the specified date and time. Unix timestamp.  **Note:** &#x60;statement_time_ge&#x60; and &#x60;statement_time_le&#x60; together constitute the creation time filter condition. - If &#x60;statement_time_ge&#x60; is filled but &#x60;statement_time_lt&#x60; is empty, &#x60;statement_time_lt&#x60; will default to the current time. - If &#x60;statement_time_lt&#x60; is filled but &#x60;statement_time_ge&#x60; is empty, &#x60;statement_time_ge&#x60; will default to the earliest shop time.  **Example:** As statements are generated daily at 00:00 UTC, to retrieve statements for the period from Oct 5 to Oct 10, configure the parameters as follows: - Set &#x60;statement_time_ge&#x60; to 00:00 on Oct 6  or any time on Oct 5 (excluding 00:00). - Set &#x60;statement_time_lt&#x60; to any time on Oct 11 (excluding 00:00). (optional)
     * @param shopCipher  (optional)
     * @return GetStatementsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public GetStatementsResponse finance202309StatementsGet(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long statementTimeLt, @javax.annotation.Nullable String paymentStatus, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long statementTimeGe, @javax.annotation.Nullable String shopCipher) throws ApiException {
        ApiResponse<GetStatementsResponse> localVarResp = finance202309StatementsGetWithHttpInfo(sortField, xTtsAccessToken, contentType, statementTimeLt, paymentStatus, pageSize, pageToken, sortOrder, statementTimeGe, shopCipher);
        return localVarResp.getData();
    }

    /**
     * GetStatements
     * Retrieves the statements generated for a shop and the key statement information based on a specified date range or their payment status. Use this API to get an overview of your daily statements over a range of time, or to find out which statements have been paid or not. For the detailed transactions, refer to [Get Statement Transactions](650a6749defece02be67da87) or [Get Order Statement Transactions](650a6734defece02be67d724). Applicable for all regions&#39; sellers. Only data after 2023-07-01 is available.
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;statement_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param statementTimeLt Filter statements to show only those that are generated before the specified date and time. Unix timestamp. Refer to notes in &#x60;statement_time_ge&#x60; for more usage information. (optional)
     * @param paymentStatus Filter statements based on the payment status. Possible values: - PAID: Payment has been transferred to the seller. - FAILED: Payment transfer failed. - PROCESSING: Payment is currently being processed. Default: All statuses are returned. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param statementTimeGe Filter statements to show only those that are generated on or after the specified date and time. Unix timestamp.  **Note:** &#x60;statement_time_ge&#x60; and &#x60;statement_time_le&#x60; together constitute the creation time filter condition. - If &#x60;statement_time_ge&#x60; is filled but &#x60;statement_time_lt&#x60; is empty, &#x60;statement_time_lt&#x60; will default to the current time. - If &#x60;statement_time_lt&#x60; is filled but &#x60;statement_time_ge&#x60; is empty, &#x60;statement_time_ge&#x60; will default to the earliest shop time.  **Example:** As statements are generated daily at 00:00 UTC, to retrieve statements for the period from Oct 5 to Oct 10, configure the parameters as follows: - Set &#x60;statement_time_ge&#x60; to 00:00 on Oct 6  or any time on Oct 5 (excluding 00:00). - Set &#x60;statement_time_lt&#x60; to any time on Oct 11 (excluding 00:00). (optional)
     * @param shopCipher  (optional)
     * @return ApiResponse&lt;GetStatementsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetStatementsResponse> finance202309StatementsGetWithHttpInfo(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long statementTimeLt, @javax.annotation.Nullable String paymentStatus, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long statementTimeGe, @javax.annotation.Nullable String shopCipher) throws ApiException {
        okhttp3.Call localVarCall = finance202309StatementsGetValidateBeforeCall(sortField, xTtsAccessToken, contentType, statementTimeLt, paymentStatus, pageSize, pageToken, sortOrder, statementTimeGe, shopCipher, null);
        Type localVarReturnType = new TypeToken<GetStatementsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * GetStatements (asynchronously)
     * Retrieves the statements generated for a shop and the key statement information based on a specified date range or their payment status. Use this API to get an overview of your daily statements over a range of time, or to find out which statements have been paid or not. For the detailed transactions, refer to [Get Statement Transactions](650a6749defece02be67da87) or [Get Order Statement Transactions](650a6734defece02be67d724). Applicable for all regions&#39; sellers. Only data after 2023-07-01 is available.
     * @param sortField The returned results will be sorted by the specified field. Only supports &#x60;statement_time&#x60;. (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param statementTimeLt Filter statements to show only those that are generated before the specified date and time. Unix timestamp. Refer to notes in &#x60;statement_time_ge&#x60; for more usage information. (optional)
     * @param paymentStatus Filter statements based on the payment status. Possible values: - PAID: Payment has been transferred to the seller. - FAILED: Payment transfer failed. - PROCESSING: Payment is currently being processed. Default: All statuses are returned. (optional)
     * @param pageSize The number of results to be returned per page.  Default: 20 Valid range: [1-100] (optional)
     * @param pageToken An opaque token used to retrieve the next page of a paginated result set. Retrieve this value from the result of the &#x60;next_page_token&#x60; from a previous response. It is not needed for the first page. (optional)
     * @param sortOrder The sort order for the &#x60;sort_field&#x60; parameter.  Default: ASC  Possible values: - ASC: Ascending order - DESC: Descending order (optional)
     * @param statementTimeGe Filter statements to show only those that are generated on or after the specified date and time. Unix timestamp.  **Note:** &#x60;statement_time_ge&#x60; and &#x60;statement_time_le&#x60; together constitute the creation time filter condition. - If &#x60;statement_time_ge&#x60; is filled but &#x60;statement_time_lt&#x60; is empty, &#x60;statement_time_lt&#x60; will default to the current time. - If &#x60;statement_time_lt&#x60; is filled but &#x60;statement_time_ge&#x60; is empty, &#x60;statement_time_ge&#x60; will default to the earliest shop time.  **Example:** As statements are generated daily at 00:00 UTC, to retrieve statements for the period from Oct 5 to Oct 10, configure the parameters as follows: - Set &#x60;statement_time_ge&#x60; to 00:00 on Oct 6  or any time on Oct 5 (excluding 00:00). - Set &#x60;statement_time_lt&#x60; to any time on Oct 11 (excluding 00:00). (optional)
     * @param shopCipher  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309StatementsGetAsync(@javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long statementTimeLt, @javax.annotation.Nullable String paymentStatus, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Long statementTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback<GetStatementsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = finance202309StatementsGetValidateBeforeCall(sortField, xTtsAccessToken, contentType, statementTimeLt, paymentStatus, pageSize, pageToken, sortOrder, statementTimeGe, shopCipher, _callback);
        Type localVarReturnType = new TypeToken<GetStatementsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for finance202309StatementsStatementIdStatementTransactionsGet
     * @param statementId The unique id of statement (required)
     * @param sortField Only support: order_create_time (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param pageToken The default is empty string (optional)
     * @param sortOrder The default is ASC, the developer can choose ASC or DESC (optional)
     * @param pageSize The default is 20. It must be a positive integer,the range is 1-100 (optional)
     * @param shopCipher  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309StatementsStatementIdStatementTransactionsGetCall(@javax.annotation.Nonnull String statementId, @javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/finance/202309/statements/{statement_id}/statement_transactions"
            .replace("{" + "statement_id" + "}", localVarApiClient.escapeString(statementId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageToken != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_token", pageToken));
        }

        if (sortField != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort_field", sortField));
        }

        if (sortOrder != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort_order", sortOrder));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        if (shopCipher != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shop_cipher", shopCipher));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xTtsAccessToken != null) {
            localVarHeaderParams.put("x-tts-access-token", localVarApiClient.parameterToString(xTtsAccessToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call finance202309StatementsStatementIdStatementTransactionsGetValidateBeforeCall(@javax.annotation.Nonnull String statementId, @javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'statementId' is set
        if (statementId == null) {
            throw new ApiException("Missing the required parameter 'statementId' when calling finance202309StatementsStatementIdStatementTransactionsGet(Async)");
        }

        // verify the required parameter 'sortField' is set
        if (sortField == null) {
            throw new ApiException("Missing the required parameter 'sortField' when calling finance202309StatementsStatementIdStatementTransactionsGet(Async)");
        }

        // verify the required parameter 'xTtsAccessToken' is set
        if (xTtsAccessToken == null) {
            throw new ApiException("Missing the required parameter 'xTtsAccessToken' when calling finance202309StatementsStatementIdStatementTransactionsGet(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling finance202309StatementsStatementIdStatementTransactionsGet(Async)");
        }

        return finance202309StatementsStatementIdStatementTransactionsGetCall(statementId, sortField, xTtsAccessToken, contentType, pageToken, sortOrder, pageSize, shopCipher, _callback);

    }

    /**
     * GetTransactionsbyStatement
     * Only for UK and US local sellers. Get a list of transactions based on statement_id. We will return a list of orders. If you require the SKU level transaction details, pass in the order_id to Get Order Statement Transactions.
     * @param statementId The unique id of statement (required)
     * @param sortField Only support: order_create_time (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param pageToken The default is empty string (optional)
     * @param sortOrder The default is ASC, the developer can choose ASC or DESC (optional)
     * @param pageSize The default is 20. It must be a positive integer,the range is 1-100 (optional)
     * @param shopCipher  (optional)
     * @return GetTransactionsbyStatementResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public GetTransactionsbyStatementResponse finance202309StatementsStatementIdStatementTransactionsGet(@javax.annotation.Nonnull String statementId, @javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String shopCipher) throws ApiException {
        ApiResponse<GetTransactionsbyStatementResponse> localVarResp = finance202309StatementsStatementIdStatementTransactionsGetWithHttpInfo(statementId, sortField, xTtsAccessToken, contentType, pageToken, sortOrder, pageSize, shopCipher);
        return localVarResp.getData();
    }

    /**
     * GetTransactionsbyStatement
     * Only for UK and US local sellers. Get a list of transactions based on statement_id. We will return a list of orders. If you require the SKU level transaction details, pass in the order_id to Get Order Statement Transactions.
     * @param statementId The unique id of statement (required)
     * @param sortField Only support: order_create_time (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param pageToken The default is empty string (optional)
     * @param sortOrder The default is ASC, the developer can choose ASC or DESC (optional)
     * @param pageSize The default is 20. It must be a positive integer,the range is 1-100 (optional)
     * @param shopCipher  (optional)
     * @return ApiResponse&lt;GetTransactionsbyStatementResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetTransactionsbyStatementResponse> finance202309StatementsStatementIdStatementTransactionsGetWithHttpInfo(@javax.annotation.Nonnull String statementId, @javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String shopCipher) throws ApiException {
        okhttp3.Call localVarCall = finance202309StatementsStatementIdStatementTransactionsGetValidateBeforeCall(statementId, sortField, xTtsAccessToken, contentType, pageToken, sortOrder, pageSize, shopCipher, null);
        Type localVarReturnType = new TypeToken<GetTransactionsbyStatementResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * GetTransactionsbyStatement (asynchronously)
     * Only for UK and US local sellers. Get a list of transactions based on statement_id. We will return a list of orders. If you require the SKU level transaction details, pass in the order_id to Get Order Statement Transactions.
     * @param statementId The unique id of statement (required)
     * @param sortField Only support: order_create_time (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param pageToken The default is empty string (optional)
     * @param sortOrder The default is ASC, the developer can choose ASC or DESC (optional)
     * @param pageSize The default is 20. It must be a positive integer,the range is 1-100 (optional)
     * @param shopCipher  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309StatementsStatementIdStatementTransactionsGetAsync(@javax.annotation.Nonnull String statementId, @javax.annotation.Nonnull String sortField, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable String sortOrder, @javax.annotation.Nullable Object pageSize, @javax.annotation.Nullable String shopCipher, final ApiCallback<GetTransactionsbyStatementResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = finance202309StatementsStatementIdStatementTransactionsGetValidateBeforeCall(statementId, sortField, xTtsAccessToken, contentType, pageToken, sortOrder, pageSize, shopCipher, _callback);
        Type localVarReturnType = new TypeToken<GetTransactionsbyStatementResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for finance202309WithdrawalsGet
     * @param types The type of transaction. Possible values: - WITHDRAW：The action of the seller to receive the settlement amount to the bank card through the action of withdrawal - SETTLE：The platform settles the amount to the seller - TRANSFER：Platform subsidies or deductions due to platform policies - REVERSE：Withdrawal failure due to incorrect bank card  (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Unix timestamp representing the end of transactions time range one wants to request (optional)
     * @param pageSize The default is 20, it must be positive integer,the range is 1-100 (optional)
     * @param pageToken The next page token (optional)
     * @param createTimeGe Unix timestamp representing the start of transactions time range one wants to request (optional)
     * @param shopCipher  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309WithdrawalsGetCall(@javax.annotation.Nonnull List<String> types, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/finance/202309/withdrawals";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (createTimeLt != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("create_time_lt", createTimeLt));
        }

        if (types != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "types", types));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        if (pageToken != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_token", pageToken));
        }

        if (createTimeGe != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("create_time_ge", createTimeGe));
        }

        if (shopCipher != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shop_cipher", shopCipher));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xTtsAccessToken != null) {
            localVarHeaderParams.put("x-tts-access-token", localVarApiClient.parameterToString(xTtsAccessToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call finance202309WithdrawalsGetValidateBeforeCall(@javax.annotation.Nonnull List<String> types, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'types' is set
        if (types == null) {
            throw new ApiException("Missing the required parameter 'types' when calling finance202309WithdrawalsGet(Async)");
        }

        // verify the required parameter 'xTtsAccessToken' is set
        if (xTtsAccessToken == null) {
            throw new ApiException("Missing the required parameter 'xTtsAccessToken' when calling finance202309WithdrawalsGet(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling finance202309WithdrawalsGet(Async)");
        }

        return finance202309WithdrawalsGetCall(types, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, createTimeGe, shopCipher, _callback);

    }

    /**
     * GetWithdrawals
     * Get the list of the withdrawal records (when Seller&#39;s withdraw money from TikTokShop) based on the specified date range. 
     * @param types The type of transaction. Possible values: - WITHDRAW：The action of the seller to receive the settlement amount to the bank card through the action of withdrawal - SETTLE：The platform settles the amount to the seller - TRANSFER：Platform subsidies or deductions due to platform policies - REVERSE：Withdrawal failure due to incorrect bank card  (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Unix timestamp representing the end of transactions time range one wants to request (optional)
     * @param pageSize The default is 20, it must be positive integer,the range is 1-100 (optional)
     * @param pageToken The next page token (optional)
     * @param createTimeGe Unix timestamp representing the start of transactions time range one wants to request (optional)
     * @param shopCipher  (optional)
     * @return GetWithdrawalsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public GetWithdrawalsResponse finance202309WithdrawalsGet(@javax.annotation.Nonnull List<String> types, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher) throws ApiException {
        ApiResponse<GetWithdrawalsResponse> localVarResp = finance202309WithdrawalsGetWithHttpInfo(types, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, createTimeGe, shopCipher);
        return localVarResp.getData();
    }

    /**
     * GetWithdrawals
     * Get the list of the withdrawal records (when Seller&#39;s withdraw money from TikTokShop) based on the specified date range. 
     * @param types The type of transaction. Possible values: - WITHDRAW：The action of the seller to receive the settlement amount to the bank card through the action of withdrawal - SETTLE：The platform settles the amount to the seller - TRANSFER：Platform subsidies or deductions due to platform policies - REVERSE：Withdrawal failure due to incorrect bank card  (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Unix timestamp representing the end of transactions time range one wants to request (optional)
     * @param pageSize The default is 20, it must be positive integer,the range is 1-100 (optional)
     * @param pageToken The next page token (optional)
     * @param createTimeGe Unix timestamp representing the start of transactions time range one wants to request (optional)
     * @param shopCipher  (optional)
     * @return ApiResponse&lt;GetWithdrawalsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetWithdrawalsResponse> finance202309WithdrawalsGetWithHttpInfo(@javax.annotation.Nonnull List<String> types, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher) throws ApiException {
        okhttp3.Call localVarCall = finance202309WithdrawalsGetValidateBeforeCall(types, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, createTimeGe, shopCipher, null);
        Type localVarReturnType = new TypeToken<GetWithdrawalsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * GetWithdrawals (asynchronously)
     * Get the list of the withdrawal records (when Seller&#39;s withdraw money from TikTokShop) based on the specified date range. 
     * @param types The type of transaction. Possible values: - WITHDRAW：The action of the seller to receive the settlement amount to the bank card through the action of withdrawal - SETTLE：The platform settles the amount to the seller - TRANSFER：Platform subsidies or deductions due to platform policies - REVERSE：Withdrawal failure due to incorrect bank card  (required)
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param createTimeLt Unix timestamp representing the end of transactions time range one wants to request (optional)
     * @param pageSize The default is 20, it must be positive integer,the range is 1-100 (optional)
     * @param pageToken The next page token (optional)
     * @param createTimeGe Unix timestamp representing the start of transactions time range one wants to request (optional)
     * @param shopCipher  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call finance202309WithdrawalsGetAsync(@javax.annotation.Nonnull List<String> types, @javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable Long createTimeLt, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Long createTimeGe, @javax.annotation.Nullable String shopCipher, final ApiCallback<GetWithdrawalsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = finance202309WithdrawalsGetValidateBeforeCall(types, xTtsAccessToken, contentType, createTimeLt, pageSize, pageToken, createTimeGe, shopCipher, _callback);
        Type localVarReturnType = new TypeToken<GetWithdrawalsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
