/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.api;

import tiktokshop.open.sdk_java.invoke.ApiCallback;
import tiktokshop.open.sdk_java.invoke.ApiClient;
import tiktokshop.open.sdk_java.invoke.ApiException;
import tiktokshop.open.sdk_java.invoke.ApiResponse;
import tiktokshop.open.sdk_java.invoke.Configuration;
import tiktokshop.open.sdk_java.invoke.Pair;
import tiktokshop.open.sdk_java.invoke.ProgressRequestBody;
import tiktokshop.open.sdk_java.invoke.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import tiktokshop.open.sdk_java.model.Product.V202404.OptimizedImagesRequestBody;
import tiktokshop.open.sdk_java.model.Product.V202404.OptimizedImagesResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductV202404Api {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ProductV202404Api() {
        this(Configuration.getDefaultApiClient());
    }

    public ProductV202404Api(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for product202404ImagesOptimizePost
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @param product202404OptimizedImagesRequestBody  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call product202404ImagesOptimizePostCall(@javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, @javax.annotation.Nullable OptimizedImagesRequestBody product202404OptimizedImagesRequestBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = product202404OptimizedImagesRequestBody;

        // create path and map variables
        String localVarPath = "/product/202404/images/optimize";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (shopCipher != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shop_cipher", shopCipher));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xTtsAccessToken != null) {
            localVarHeaderParams.put("x-tts-access-token", localVarApiClient.parameterToString(xTtsAccessToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call product202404ImagesOptimizePostValidateBeforeCall(@javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, @javax.annotation.Nullable OptimizedImagesRequestBody product202404OptimizedImagesRequestBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xTtsAccessToken' is set
        if (xTtsAccessToken == null) {
            throw new ApiException("Missing the required parameter 'xTtsAccessToken' when calling product202404ImagesOptimizePost(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling product202404ImagesOptimizePost(Async)");
        }

        return product202404ImagesOptimizePostCall(xTtsAccessToken, contentType, shopCipher, product202404OptimizedImagesRequestBody, _callback);

    }

    /**
     * OptimizedImages
     * Optimize images used in your TikTok Shop by changing the background to white. This is especially useful for images displayed in the product image gallery as it enhances product visibility.  **Note**:  - The images to be optimized must first be uploaded to TikTok Shop through the [Upload Product Image API](https://partner.tiktokshop.com/docv2/page/6509df95defece02be598a22). You will not be able to optimize any images that are not hosted by TikTok Shop. - Images that were previously optimized will not be processed again. - The optimization is processed asynchronously and typically completes within a few seconds. Therefore, the &#x60;optimize_status&#x60; returned in the first API request for an image is always &#x60;PROCESSING&#x60;, indicating that optimization is underway. Please call the API again after a few seconds to get the final optimization status.
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @param product202404OptimizedImagesRequestBody  (optional)
     * @return OptimizedImagesResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public OptimizedImagesResponse product202404ImagesOptimizePost(@javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, @javax.annotation.Nullable OptimizedImagesRequestBody product202404OptimizedImagesRequestBody) throws ApiException {
        ApiResponse<OptimizedImagesResponse> localVarResp = product202404ImagesOptimizePostWithHttpInfo(xTtsAccessToken, contentType, shopCipher, product202404OptimizedImagesRequestBody);
        return localVarResp.getData();
    }

    /**
     * OptimizedImages
     * Optimize images used in your TikTok Shop by changing the background to white. This is especially useful for images displayed in the product image gallery as it enhances product visibility.  **Note**:  - The images to be optimized must first be uploaded to TikTok Shop through the [Upload Product Image API](https://partner.tiktokshop.com/docv2/page/6509df95defece02be598a22). You will not be able to optimize any images that are not hosted by TikTok Shop. - Images that were previously optimized will not be processed again. - The optimization is processed asynchronously and typically completes within a few seconds. Therefore, the &#x60;optimize_status&#x60; returned in the first API request for an image is always &#x60;PROCESSING&#x60;, indicating that optimization is underway. Please call the API again after a few seconds to get the final optimization status.
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @param product202404OptimizedImagesRequestBody  (optional)
     * @return ApiResponse&lt;OptimizedImagesResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OptimizedImagesResponse> product202404ImagesOptimizePostWithHttpInfo(@javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, @javax.annotation.Nullable OptimizedImagesRequestBody product202404OptimizedImagesRequestBody) throws ApiException {
        okhttp3.Call localVarCall = product202404ImagesOptimizePostValidateBeforeCall(xTtsAccessToken, contentType, shopCipher, product202404OptimizedImagesRequestBody, null);
        Type localVarReturnType = new TypeToken<OptimizedImagesResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * OptimizedImages (asynchronously)
     * Optimize images used in your TikTok Shop by changing the background to white. This is especially useful for images displayed in the product image gallery as it enhances product visibility.  **Note**:  - The images to be optimized must first be uploaded to TikTok Shop through the [Upload Product Image API](https://partner.tiktokshop.com/docv2/page/6509df95defece02be598a22). You will not be able to optimize any images that are not hosted by TikTok Shop. - Images that were previously optimized will not be processed again. - The optimization is processed asynchronously and typically completes within a few seconds. Therefore, the &#x60;optimize_status&#x60; returned in the first API request for an image is always &#x60;PROCESSING&#x60;, indicating that optimization is underway. Please call the API again after a few seconds to get the final optimization status.
     * @param xTtsAccessToken  (required)
     * @param contentType Allowed type: application/json (required)
     * @param shopCipher  (optional)
     * @param product202404OptimizedImagesRequestBody  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call product202404ImagesOptimizePostAsync(@javax.annotation.Nonnull String xTtsAccessToken, @javax.annotation.Nonnull String contentType, @javax.annotation.Nullable String shopCipher, @javax.annotation.Nullable OptimizedImagesRequestBody product202404OptimizedImagesRequestBody, final ApiCallback<OptimizedImagesResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = product202404ImagesOptimizePostValidateBeforeCall(xTtsAccessToken, contentType, shopCipher, product202404OptimizedImagesRequestBody, _callback);
        Type localVarReturnType = new TypeToken<OptimizedImagesResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
