/*
 * Amazon Ads API ALL
 * Amazon Advertising API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hzltd.module.erplus.adv.adapter.amazon.v2.model.all;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.all.ContentInstreamPositionTarget;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ContentInstreamPositionTarget1
 */
@JsonPropertyOrder({
  ContentInstreamPositionTarget1.JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T22:23:49.722362+08:00[Asia/Shanghai]")
public class ContentInstreamPositionTarget1 {
  public static final String JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET = "contentInstreamPositionTarget";
  private ContentInstreamPositionTarget contentInstreamPositionTarget;

  public ContentInstreamPositionTarget1() { 
  }

  public ContentInstreamPositionTarget1 contentInstreamPositionTarget(ContentInstreamPositionTarget contentInstreamPositionTarget) {
    this.contentInstreamPositionTarget = contentInstreamPositionTarget;
    return this;
  }

   /**
   * Get contentInstreamPositionTarget
   * @return contentInstreamPositionTarget
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContentInstreamPositionTarget getContentInstreamPositionTarget() {
    return contentInstreamPositionTarget;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentInstreamPositionTarget(ContentInstreamPositionTarget contentInstreamPositionTarget) {
    this.contentInstreamPositionTarget = contentInstreamPositionTarget;
  }


  /**
   * Return true if this contentInstreamPositionTarget_1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentInstreamPositionTarget1 contentInstreamPositionTarget1 = (ContentInstreamPositionTarget1) o;
    return Objects.equals(this.contentInstreamPositionTarget, contentInstreamPositionTarget1.contentInstreamPositionTarget);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentInstreamPositionTarget);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentInstreamPositionTarget1 {\n");
    sb.append("    contentInstreamPositionTarget: ").append(toIndentedString(contentInstreamPositionTarget)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `contentInstreamPositionTarget` to the URL query string
    if (getContentInstreamPositionTarget() != null) {
      joiner.add(getContentInstreamPositionTarget().toUrlQueryString(prefix + "contentInstreamPositionTarget" + suffix));
    }

    return joiner.toString();
  }
}

