/*
 * Amazon Ads API ALL
 * Amazon Advertising API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hzltd.module.erplus.adv.adapter.amazon.v2.model.all;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.all.FrequencyTargetingSetting;
import com.hzltd.module.erplus.adv.adapter.amazon.v2.model.all.TimeUnit;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CreateFrequency
 */
@JsonPropertyOrder({
  CreateFrequency.JSON_PROPERTY_EVENT_MAX_COUNT,
  CreateFrequency.JSON_PROPERTY_FREQUENCY_TARGETING_SETTING,
  CreateFrequency.JSON_PROPERTY_TIME_COUNT,
  CreateFrequency.JSON_PROPERTY_TIME_UNIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T22:23:49.722362+08:00[Asia/Shanghai]")
public class CreateFrequency {
  public static final String JSON_PROPERTY_EVENT_MAX_COUNT = "eventMaxCount";
  private Integer eventMaxCount;

  public static final String JSON_PROPERTY_FREQUENCY_TARGETING_SETTING = "frequencyTargetingSetting";
  private FrequencyTargetingSetting frequencyTargetingSetting;

  public static final String JSON_PROPERTY_TIME_COUNT = "timeCount";
  private Integer timeCount;

  public static final String JSON_PROPERTY_TIME_UNIT = "timeUnit";
  private TimeUnit timeUnit;

  public CreateFrequency() { 
  }

  public CreateFrequency eventMaxCount(Integer eventMaxCount) {
    this.eventMaxCount = eventMaxCount;
    return this;
  }

   /**
   * The maximum number of times an EventType is served per user. For ADSP ad group, maximum supported value is 500.
   * minimum: 1
   * maximum: 99000
   * @return eventMaxCount
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENT_MAX_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEventMaxCount() {
    return eventMaxCount;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_MAX_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventMaxCount(Integer eventMaxCount) {
    this.eventMaxCount = eventMaxCount;
  }


  public CreateFrequency frequencyTargetingSetting(FrequencyTargetingSetting frequencyTargetingSetting) {
    this.frequencyTargetingSetting = frequencyTargetingSetting;
    return this;
  }

   /**
   * Get frequencyTargetingSetting
   * @return frequencyTargetingSetting
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FREQUENCY_TARGETING_SETTING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FrequencyTargetingSetting getFrequencyTargetingSetting() {
    return frequencyTargetingSetting;
  }


  @JsonProperty(JSON_PROPERTY_FREQUENCY_TARGETING_SETTING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrequencyTargetingSetting(FrequencyTargetingSetting frequencyTargetingSetting) {
    this.frequencyTargetingSetting = frequencyTargetingSetting;
  }


  public CreateFrequency timeCount(Integer timeCount) {
    this.timeCount = timeCount;
    return this;
  }

   /**
   * The value associated with the time and unit of time for this frequency cap.
   * minimum: 1
   * maximum: 60
   * @return timeCount
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTimeCount() {
    return timeCount;
  }


  @JsonProperty(JSON_PROPERTY_TIME_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeCount(Integer timeCount) {
    this.timeCount = timeCount;
  }


  public CreateFrequency timeUnit(TimeUnit timeUnit) {
    this.timeUnit = timeUnit;
    return this;
  }

   /**
   * Get timeUnit
   * @return timeUnit
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME_UNIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TimeUnit getTimeUnit() {
    return timeUnit;
  }


  @JsonProperty(JSON_PROPERTY_TIME_UNIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeUnit(TimeUnit timeUnit) {
    this.timeUnit = timeUnit;
  }


  /**
   * Return true if this CreateFrequency object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateFrequency createFrequency = (CreateFrequency) o;
    return Objects.equals(this.eventMaxCount, createFrequency.eventMaxCount) &&
        Objects.equals(this.frequencyTargetingSetting, createFrequency.frequencyTargetingSetting) &&
        Objects.equals(this.timeCount, createFrequency.timeCount) &&
        Objects.equals(this.timeUnit, createFrequency.timeUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventMaxCount, frequencyTargetingSetting, timeCount, timeUnit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateFrequency {\n");
    sb.append("    eventMaxCount: ").append(toIndentedString(eventMaxCount)).append("\n");
    sb.append("    frequencyTargetingSetting: ").append(toIndentedString(frequencyTargetingSetting)).append("\n");
    sb.append("    timeCount: ").append(toIndentedString(timeCount)).append("\n");
    sb.append("    timeUnit: ").append(toIndentedString(timeUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `eventMaxCount` to the URL query string
    if (getEventMaxCount() != null) {
      joiner.add(String.format("%seventMaxCount%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEventMaxCount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `frequencyTargetingSetting` to the URL query string
    if (getFrequencyTargetingSetting() != null) {
      joiner.add(String.format("%sfrequencyTargetingSetting%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFrequencyTargetingSetting()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `timeCount` to the URL query string
    if (getTimeCount() != null) {
      joiner.add(String.format("%stimeCount%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTimeCount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `timeUnit` to the URL query string
    if (getTimeUnit() != null) {
      joiner.add(String.format("%stimeUnit%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTimeUnit()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

