CREATE TABLE IF NOT EXISTS `mas_skill_def` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `skill_code` varchar(128) NOT NULL COMMENT '技能唯一编码',
  `name` varchar(128) NOT NULL COMMENT '技能名称',
  `description` varchar(512) DEFAULT NULL COMMENT '技能描述',
  `icon` varchar(255) DEFAULT NULL COMMENT '技能图标 url',
  `use_case_tags` varchar(255) DEFAULT NULL COMMENT '适用场景标签',
  `strategy_instruction` text COMMENT '策略指导书',
  `required_tools` varchar(1024) DEFAULT NULL COMMENT '允许使用的工具集 json',
  `param_schema` text COMMENT '技能参数定义 schema json',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_code` (`skill_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MAS 技能定义表';

CREATE TABLE IF NOT EXISTS `mas_task_skill_rel` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `task_id` bigint NOT NULL COMMENT '关联的 mas_task_job 的 ID',
  `skill_code` varchar(128) NOT NULL COMMENT '应用的技能编码',
  `target_biz_id` varchar(128) NOT NULL COMMENT '目标业务对象的唯一标识',
  `target_biz_name` varchar(255) DEFAULT NULL COMMENT '目标业务对象的名称',
  `config_params` text COMMENT '用户配置的运行参数 JSON',
  `current_stage` varchar(255) DEFAULT NULL COMMENT '当前进度或状态文本',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MAS 任务与技能绑定关系表';

INSERT INTO mas_skill_def (skill_code, name, description, icon, use_case_tags, strategy_instruction, required_tools, param_schema) VALUES
('NEW_PRODUCT_LAUNCH_V1', '「火箭飙升」冷启动', '专为新品打造的 30 天自动出价与拓词策略，前3天自动广告收集数据，后14天开启否定及长尾词提取，最终稳定ACOS。', 'Lightning', '新品期, 拓流, 预算控制', '{"summary":{"description":"专为新品打造的 30 天自动出价与拓词策略，前3天自动广告收集数据，后14天开启否定及长尾词提取，最终稳定ACOS。","phases":[{"name":"Phase 1: 数据积累","description":"通过自动广告快速获取充足的基础数据（建议执行 3 天）。"},{"name":"Phase 2: 词汇清洗与挖掘","description":"每日巡检搜索词，剔除低效词，提取高效词（执行 11 天）。"},{"name":"Phase 3: ACOS 稳定控制","description":"动态微调竞价，逐步贴近目标 ACOS，优化预算分配（执行 16 天）。"}]},"strategy":[{"name":"Phase 1: 数据积累","description":"通过自动广告快速获取充足的基础数据。","order":1,"cycleType":"ONCE","interval":259200,"tools":["AD_SP_API"],"instruction":"开启自动广告，使用广泛匹配组合。若无历史数据，禁止人工否定关键词。目标：快速获取充足的基础曝光和点击。"},{"name":"Phase 2: 词汇清洗与挖掘","description":"每日巡检搜索词，剔除低效词，提取高效词。","order":2,"cycleType":"PERIODIC","interval":86400,"tools":["AD_SP_API","KEYWORD_SUGGESTION"],"instruction":"每日巡检 Search Term 数据报告。当花费偏高且0转化的词，进入精确否定名单。出单转化高的词，剥离并建立手动精准广告活动。"},{"name":"Phase 3: ACOS 稳定控制","description":"动态微调竞价，逐步贴近目标 ACOS，优化预算分配。","order":3,"cycleType":"PERIODIC","interval":14400,"tools":["AD_SP_API"],"instruction":"每 4 小时动态微调竞价，逐步贴近设定目标。自动关闭表现最差的 10% 广告组，释放预算。若累计花费即将触及总预算阀值，提前进入收网模式。"}]}', '["AD_SP_API", "KEYWORD_SUGGESTION"]', '{"targetRoas": { "type": "number", "label": "目标 ROAS", "required": true }, "totalBudget": { "type": "number", "label": "总预算 ($)", "required": true }}'),

('SEASONAL_RUSH_V1', '「旺季抢位」防守反击', '针对旺季的高频波动，每两小时监控由于缺货或竞争加剧导致的排名下降，自动进行防守调价。', 'DataLine', '旺季爆单, 排名卡位', '{"summary":{"description":"针对旺季的高频波动，每两小时监控由于缺货或竞争加剧导致的排名下降，自动进行防守调价。","phases":[{"name":"Phase 1: 高频排名监控","description":"周期性调用排名接口，实时掌握核心词位置。"},{"name":"Phase 2: 竞价防守反击","description":"当排名跌出理想区间时，梯度提价并增加 Top 位置权重。"},{"name":"Phase 3: 熔断与告警","description":"当达到报价上限仍无法回升排名时，停止自动操作并告警。"}]},"strategy":[{"name":"Phase 1: 高频排名监控","description":"周期性调用排名接口，实时掌握核心词位置。","order":1,"cycleType":"PERIODIC","interval":7200,"tools":["AD_RANK_API"],"instruction":"周期性调用 AD_RANK_API 获取商品在其核心词的综合卡位。判断流量分布情况，如果主核心词掉出搜索结果首页：立刻激活 Phase 2。"},{"name":"Phase 2: 竞价防守反击","description":"当排名跌出理想区间时，梯度提价并增加 Top 位置权重。","order":2,"cycleType":"PERIODIC","interval":14400,"tools":["AD_SP_API"],"instruction":"在设定上限之内，梯度提振广告 Bid（每次上升约20%）。优先部署 Top of Search 溢价系数。在后续 4 小时内对比排名上升趋势，如果已恢复至理想排位，暂停提价。"},{"name":"Phase 3: 熔断与告警","description":"当达到报价上限仍无法回升排名时，停止自动操作并告警。","order":3,"cycleType":"ONCE","interval":0,"tools":[],"instruction":"如果当前竞价已达到或溢出设定上限，且排名依然无法重夺前列，抛出系统异常告警。暂停自动操作状态，交由人类运营专家介入。"}]}', '["AD_RANK_API"]', '{"maxBid": { "type": "number", "label": "单次点击上限 ($)", "required": true }}'),

('CLEARANCE_V1', '「智能清仓」库存消化', '识别冗余库存商品，联动降价机制与高投入比广告，在最短周期内释放库存压力，挽回现金流。', 'ShoppingCart', '清仓抛售, 现金流恢复', '{"summary":{"description":"识别冗余库存商品，联动降价机制与高投入比广告，在最短周期内释放库存压力，挽回现金流。","phases":[{"name":"Phase 1: 健康度体检","description":"定位严重冗余 SKU，设定安全退出阈值。"},{"name":"Phase 2: 组合促销放量","description":"通过 Prime 折扣与展示型广告开启首周探测。"},{"name":"Phase 3: 终极倾销模式","description":"如果清理进度仍不达标，触发底线价探底策略。"}]},"strategy":[{"name":"Phase 1: 健康度体检","description":"定位严重冗余 SKU，设定安全退出阈值。","order":1,"cycleType":"ONCE","interval":0,"tools":["INVENTORY_API"],"instruction":"使用 INVENTORY_API 定位库龄远超健康周期的 SKU，划定严重冗余等级。计算剩余日均销售（Velocity），设立安全退出阈值。"},{"name":"Phase 2: 组合促销放量","description":"通过 Prime 折扣与展示型广告开启首周探测。","order":2,"cycleType":"PERIODIC","interval":259200,"tools":["AD_SP_API"],"instruction":"首周：启动 Prime 专享折扣，配搭展示型推流广告。观测三日销量环比变化。"},{"name":"Phase 3: 终极倾销模式","description":"如果清理进度仍不达标，触发底线价探底策略。","order":3,"cycleType":"ONCE","interval":0,"tools":["AD_SP_API"],"instruction":"如果 Phase 2 下推流效率仍无法清理掉积压的 50% 库存，则触发探底模式。自动将产品修改至底线清仓价，不再关注利润，并在多渠道申报站外 Deal。"}]}', '["INVENTORY_API"]', '{"lowestPrice": { "type": "number", "label": "最低清仓底线价", "required": true }}'),

('KEYWORD_REAPING_V1', '「高效拓词」流量转化', '自动收割自动广告和广泛匹配中的高转化搜索词，将其转化为精准匹配，确保持续的流量优势。', 'Search', '拓词, 流量增长', '{"summary":{"description":"自动收割高转化搜索词，确保持续的流量优势。","phases":[{"name":"Phase 1: 流量扫描","description":"分析自动和广泛匹配广告组产生的所有搜索词。"},{"name":"Phase 2: 高效词提取","description":"根据点击和转化指标，筛选出值得收割的高价值搜索词。"},{"name":"Phase 3: 广告组迁移","description":"将这些搜索词自动迁移到精准匹配广告组并设置建议竞价。"}]},"strategy":[{"name":"Phase 1: 流量扫描","description":"分析自动和广泛匹配广告组产生的所有搜索词。","order":1,"cycleType":"PERIODIC","interval":86400,"tools":["AD_SP_API"],"instruction":"周期性拉取 Search Term 报告，涵盖过去 7 天的数据，计算每个词的点击率和转化率。"},{"name":"Phase 2: 高效词提取","description":"筛选出值得收割的高价值搜索词。","order":2,"cycleType":"PERIODIC","interval":86400,"tools":["KEYWORD_ADVISOR"],"instruction":"对转化率 > 3% 且 订单数 >= 2 的搜索词进行标记，确认其不是已存在的精准词。"},{"name":"Phase 3: 广告组迁移","description":"将搜索词自动迁移到精准匹配广告组。","order":3,"cycleType":"ONCE","interval":0,"tools":["AD_SP_API"],"instruction":"在目标精准广告活动中新增这些词，并建议竞价，同时在原广告组中将其设为否定关键词。"}]}', '["AD_SP_API", "KEYWORD_ADVISOR"]', '{"conversionThreshold": {"type": "number", "label": "转化率阈值 (%)", "default": 3}}'),

('BUDGET_PACING_V1', '「预算罗盘」均匀支出', '防止广告预算在早间被过快耗尽，通过动态调整竞价策略，确保全天候的流量覆盖。', 'Compass', '预算控制, 均匀分布', '{"summary":{"description":"防止广告预算过快耗尽，确保全天候流量覆盖。","phases":[{"name":"Phase 1: 预算消耗监控","description":"每小时实时监控各广告活动的预算支出进度。"},{"name":"Phase 2: 弹性竞价调节","description":"当消耗速度过快时，自动下调竞价以节省预算。"},{"name":"Phase 3: 晚间流量补位","description":"在流量高峰期（下午/晚上）逐步恢复竞价以捕获最佳流量。"}]},"strategy":[{"name":"Phase 1: 预算消耗监控","description":"实时监控预算支出进度。","order":1,"cycleType":"PERIODIC","interval":3600,"tools":["AD_SP_API"],"instruction":"通过 API 记录每个小时的累积花费，并与全天平均消耗速率进行对比。"},{"name":"Phase 2: 弹性竞价调节","description":"消耗过快时，自动下调竞价。","order":2,"cycleType":"PERIODIC","interval":3600,"tools":["AD_SP_API"],"instruction":"如果当前时间消耗已超过当日预算的 60%，且尚未到中午，自动将 Bid 下调 15%-25%。"},{"name":"Phase 3: 晚间流量补位","description":"晚间恢复竞价。","order":3,"cycleType":"PERIODIC","interval":3600,"tools":["AD_SP_API"],"instruction":"到当地时间 18:00 后，根据剩余预算量，逐步线性恢复竞价至原始水平。"}]}', '["AD_SP_API"]', '{"dailyBudget": {"type": "number", "label": "预期每日限额 ($)"}}'),

('ASIN_DEFENSE_V1', '「品牌护盾」闭环防御', '通过投放自己的 ASIN，在产品详情页形成闭环防御，防止客户流向竞争对手页面。', 'Shield', '品牌保护, 关联销售', '{"summary":{"description":"通过投放自有 ASIN 形成闭环防御。","phases":[{"name":"Phase 1: 关联池构建","description":"基于购买关联度，构建互补或替代产品的 ASIN 矩阵。"},{"name":"Phase 2: 广告位抢占","description":"通过商品投放广告（SP/SD），强势占据详情页相关位置。"},{"name":"Phase 3: 转化溢出优化","description":"分析 ASIN 间的交叉购买行为，优化投放预算分配。"}]},"strategy":[{"name":"Phase 1: 关联池构建","description":"构建互补或替代产品的 ASIN 矩阵。","order":1,"cycleType":"ONCE","interval":0,"tools":["MARKET_ANALYTICS"],"instruction":"拉取店铺内热销榜单，提取经常组合购买的 ASIN 对，作为首优投放靶点。"},{"name":"Phase 2: 广告位抢占","description":"占据详情页相关位置。","order":2,"cycleType":"PERIODIC","interval":86400,"tools":["AD_SP_API"],"instruction":"开启商品投放计划，设置高溢价以确保在详情页的 Top 位置展示，并将竞品 ASIN 设为否定。"},{"name":"Phase 3: 转化溢出优化","description":"优化投放预算分配。","order":3,"cycleType":"PERIODIC","interval":172800,"tools":["AD_SP_API"],"instruction":"如果发现某些 ASIN 间的 ACOS 极低，则从通用池中拨出更多预算用于这两者间的固定防御。"}]}', '["AD_SP_API", "MARKET_ANALYTICS"]', '{"targetAsins": {"type": "string", "label": "核心防御 ASIN (逗号分隔)"}}'),

('COMPETITOR_CONQUEST_V1', '「猎虎行动」竞品截流', '针对核心竞品的 ASIN 和品牌关键词进行精准狙击，在对手的流量高地抢夺精准客群。', 'Target', '竞品分析, 流量掠夺', '{"summary":{"description":"针对核心竞品进行精准狙击。","phases":[{"name":"Phase 1: 竞品雷达识别","description":"利用类目排名和搜索权重，定位表现最强劲的前 5 名对手。"},{"name":"Phase 2: 侧翼进攻投放","description":"对这些对手的 ASIN 投放强力广告，并搭配具有竞争力的优惠价格。"},{"name":"Phase 3: 转化归因追踪","description":"追踪从竞品流量流向本品的转化链路，动态加码高效广告组。"}]},"strategy":[{"name":"Phase 1: 竞品雷达识别","description":"定位前 5 名强劲对手。","order":1,"cycleType":"ONCE","interval":0,"tools":["AD_RANK_API"],"instruction":"根据类目 BSR 排名和目标关键词首页覆盖率，自动识别出重叠度最高的竞品 ASIN。"},{"name":"Phase 2: 侧翼进攻投放","description":"对竞品投放强力广告。","order":2,"cycleType":"PERIODIC","interval":86400,"tools":["AD_SP_API"],"instruction":"创建竞争性投放广告活动，对目标 ASIN 给出比系统建议竞价高出 30% 的 Bid。"},{"name":"Phase 3: 转化归因追踪","description":"追踪并加码高效组。","order":3,"cycleType":"PERIODIC","interval":432000,"tools":["AD_SP_API"],"instruction":"每 5 天结算一次归因报告，若 ACOS < 25%，则该组追加 50% 预算，否则维持或微降。"}]}', '["AD_SP_API", "AD_RANK_API"]', '{"budgetCap": {"type": "number", "label": "最高消耗限额 ($)"}}'),

('LOW_CONVERSION_CLEANUP_V1', '「止损卫士」无效清理', '自动监控并暂停那些花费巨大但转化极差的“僵尸”关键词，保护整体 ACOS 不受侵蚀。', 'Trash', '降本增效, 风险控制', '{"summary":{"description":"自动监控并清理转化极差的关键词。","phases":[{"name":"Phase 1: 异常流量侦测","description":"扫描历史 30 天数据，找出点击次数多但 0 转化的关键词。"},{"name":"Phase 2: 阶梯式温和降价","description":"先对这些词下调 50% 竞价进行观察，而非直接暂停。"},{"name":"Phase 3: 终极清理关停","description":"若调价后仍无起色且继续造成损失，则彻底暂停任务。"}]},"strategy":[{"name":"Phase 1: 异常流量侦测","description":"找出高点击 0 转化词。","order":1,"cycleType":"PERIODIC","interval":172800,"tools":["AD_SP_API"],"instruction":"设置过滤规则：过去 30 天点击 > 15 次 且 订单 = 0。"},{"name":"Phase 2: 阶梯式温和降价","description":"下调 50% 竞价。","order":2,"cycleType":"ONCE","interval":0,"tools":["AD_SP_API"],"instruction":"将筛选出的词 Bid 强制压低至 $0.10，设置观察期为 48 小时。"},{"name":"Phase 3: 终极清理关停","description":"彻底暂停任务。","order":3,"cycleType":"ONCE","interval":0,"tools":["AD_SP_API"],"instruction":"若 48 小时后依然产生超过 5 次点击且无单，则将其状态更新为 PAUSED。"}]}', '["AD_SP_API"]', '{"maxClicksNoOrder": {"type": "number", "label": "最高点击限额", "default": 20}}'),

('OUT_OF_STOCK_PROTECTION_V1', '「断货预案」广告调控', '实时同步库存状态，在商品接近断货时自动减少广告投入，防止在大促后因断货导致的排名骤降。', 'Warning', '库存保护, 排名卡位', '{"summary":{"description":"库存接近断货时自动减少广告投入。","phases":[{"name":"Phase 1: 实时库存巡检","description":"每小时拉取 FBA 在库及在途库存数据，计算剩余可售天数。"},{"name":"Phase 2: 阶梯式降温策略","description":"根据库存天数逐步缩减预算和竞价（例如 7 天降 50%，3 天降 80%）。"},{"name":"Phase 3: 库存回归监测","description":"监测入库上架情况，一旦库存恢复正常水平，立即秒回原始广告配置。"}]},"strategy":[{"name":"Phase 1: 实时库存巡检","description":"结算剩余可售天数。","order":1,"cycleType":"PERIODIC","interval":3600,"tools":["INVENTORY_API"],"instruction":"拉取 FBA 可售库存。计算：库存数 / 近 30 日销量均值 = 剩余天数。"},{"name":"Phase 2: 阶梯式降温策略","description":"缩减预算和竞价。","order":2,"cycleType":"PERIODIC","interval":14400,"tools":["AD_SP_API"],"instruction":"当剩余天数 < 7 时，预算下调 50%；天数 < 3 时，仅保留最小竞价；天数 = 0 时，全量 PAUSED。"},{"name":"Phase 3: 库存回归监测","description":"恢复原始广告配置。","order":3,"cycleType":"PERIODIC","interval":14400,"tools":["INVENTORY_API"],"instruction":"检测到库存天数回升至 14 天以上后，自动撤销所有降级限制，恢复原始设置。"}]}', '["INVENTORY_API", "AD_SP_API"]', '{"minSafeDays": {"type": "number", "label": "安全库存天数", "default": 7}}'),

('PRIME_DAY_PREP_V1', '「大促蓄水」权重构建', '在大促前 14 天开启，通过适度的超额支出来积累历史点击和权重，为大促期间的高效转化铺路。', 'Water', '活动预热, 权重提升', '{"summary":{"description":"大促前 14 天积累权重。","phases":[{"name":"Phase 1: 核心词抢位","description":"对目标关键词进行集中覆盖，提升自然和广告排名位置。"},{"name":"Phase 2: 再营销受众积累","description":"通过 SD 广告积累“看过未买”的受众池，为大促返场做准备。"},{"name":"Phase 3: 峰值转化收网","description":"在大促当天全面释放折扣，配合顶格预算，实现流量峰值转化。"}]},"strategy":[{"name":"Phase 1: 核心词抢位","description":"提升排名位置。","order":1,"cycleType":"PERIODIC","interval":86400,"tools":["AD_SP_API"],"instruction":"大促前 2 周，将核心词的比重调高 20%，不仅追求 ROI，更追求排名上浮。"},{"name":"Phase 2: 再营销受众积累","description":"积累受众池。","order":2,"cycleType":"PERIODIC","interval":86400,"tools":["AD_SD_API"],"instruction":"利用 Sponsored Display 记录访问过 Listing 的 Cookie 信息，为大促期再投放储备。"},{"name":"Phase 3: 峰值转化收网","description":"释放折扣实现转化。","order":3,"cycleType":"ONCE","interval":0,"tools":["AD_SP_API"],"instruction":"根据大促主日程，在 00:00 激活全网最高溢价和最高预算限额。"}]}', '["AD_SP_API", "AD_SD_API"]', '{"promoDate": {"type": "string", "label": "大促开始日期 (YYYY-MM-DD)"}}'),

('BRAND_PROTECTION_V1', '「品牌霸屏」流量收拢', '监控品牌关键词，确保品牌旗舰店广告和商品广告覆盖搜索结果首页 50% 以上，不让竞品分流。', 'Home', '品牌安全, 点击垄断', '{"summary":{"description":"确保品牌关键词在首页形成覆盖优势。","phases":[{"name":"Phase 1: 品牌词占位巡检","description":"监控前 5 个品牌词下的广告位所有归属，检测是否有竞品投放。"},{"name":"Phase 2: 动态提价反击","description":"一旦发现竞品由于高价抢夺品牌词位置，自动触发 Top 位加价逻辑。"},{"name":"Phase 3: 全案覆盖布局","description":"联动 SBV (品牌视频) 和 SP 广告，在首页构建多维可见度。"}]},"strategy":[{"name":"Phase 1: 品牌词占位巡检","description":"检测是否有竞品投放。","order":1,"cycleType":"PERIODIC","interval":7200,"tools":["AD_RANK_API"],"instruction":"实时分析搜索结果，若前 3 位广告中出现非本品牌 ASIN，记录其对手名称。"},{"name":"Phase 2: 动态提价反击","description":"触发 Top 位加价逻辑。","order":2,"cycleType":"PERIODIC","interval":7200,"tools":["AD_SP_API"],"instruction":"将品牌词的 Top 溢价系数额外上调 100%，直至竞品退出前三。"},{"name":"Phase 3: 全案覆盖布局","description":"首页多维可见度构筑。","order":3,"cycleType":"ONCE","interval":0,"tools":["AD_SB_API"],"instruction":"在品牌词下加载已准备好的品牌视频广告页，占据搜索中部的视觉中心。"}]}', '["AD_RANK_API", "AD_SP_API", "AD_SB_API"]', '{"brandKeywords": {"type": "string", "label": "核心品牌词 (逗号分隔)"}}'),

('LOWER_FUNNEL_RETARGETING_V1', '「漏斗收割」二次转化', '专注于针对那些浏览过页面但未购买的访客，使用 Sponsored Display 进行全网追数，提高最终转化。', 'Filter', '再营销, 提升转化', '{"summary":{"description":"针对浏览未购买访客进行全网追数。","phases":[{"name":"Phase 1: 流失受众画像分析","description":"分析漏斗流失率，根据加购未买和仅浏览未买进行细分分层。"},{"name":"Phase 2: 差异化内容追数","description":"对不同层级受众投放针对性折扣（如 5% vs 10%）的 SD 广告。"},{"name":"Phase 3: 转化闭环结算","description":"统计再营销带来的增量订单，计算综合 ROI 贡献度。"}]},"strategy":[{"name":"Phase 1: 流失受众画像分析","description":"分析漏斗流失率和受众分层。","order":1,"cycleType":"PERIODIC","interval":172800,"tools":["MARKET_ANALYTICS"],"instruction":"拉取后台受众洞察数据，分出“热受众”池。"},{"name":"Phase 2: 差异化内容追数","description":"投放针对性 SD 广告。","order":2,"cycleType":"PERIODIC","interval":86400,"tools":["AD_SD_API"],"instruction":"启用 SD Viewable-CPM 竞价模式，重点投放在“同类产品关联页”及“站外展示位”。"},{"name":"Phase 3: 转化闭环结算","description":"计算综合 ROI 贡献度。","order":3,"cycleType":"PERIODIC","interval":604800,"tools":["AD_SD_API"],"instruction":"对比再营销激活前后，整体店铺自然转化的提升系数。"}]}', '["AD_SD_API", "MARKET_ANALYTICS"]', '{"targetDays": {"type": "number", "label": "追溯天数", "default": 30}}'),

('STAGNANT_PRODUCT_BOOST_V1', '「滞销激活」唤醒计划', '针对库存周转极低且无流量的“僵尸”listing，通过短期的脉冲式广告投放，强制拉回算法推荐视线。', 'Power', '激活 Listing, 动销优化', '{"summary":{"description":"针对滞销 Listing 强制拉回推荐视线。","phases":[{"name":"Phase 1: 潜力词库重建","description":"彻底清空原有低效词，重新利用生成式 AI 挖掘 20 个高匹配长尾词。"},{"name":"Phase 2: 脉冲式高出价探测","description":"在 3 天内给予核心词平时 3 倍的预算，换取第一波算法交互数据。"},{"name":"Phase 3: 推荐链路固化","description":"根据脉冲期的反馈，保留有转化的词，进入常规 PENDING 执行状态。"}]},"strategy":[{"name":"Phase 1: 潜力词库重建","description":"挖掘 20 个长尾词。","order":1,"cycleType":"ONCE","interval":0,"tools":["KEYWORD_ADVISOR"],"instruction":"使用 AI 模型分析标题，生成 20 个高相关但低竞争的长尾流量词。"},{"name":"Phase 2: 脉冲式高出价探测","description":"换取算法交互数据。","order":2,"cycleType":"PERIODIC","interval":259200,"tools":["AD_SP_API"],"instruction":"启动高额竞价策略，目标是抢夺相关页头部位置，不计日均成本，只求激活点击。"},{"name":"Phase 3: 推荐链路固化","description":"固化推荐链路。","order":3,"cycleType":"ONCE","interval":0,"tools":["AD_SP_API"],"instruction":"筛选出在脉冲期内有点击且加购的词，转为正式投放，其余的一概清理。"}]}', '["KEYWORD_ADVISOR", "AD_SP_API"]', '{"boostBudget": {"type": "number", "label": "激活阶段脉冲预算 ($)"}}');
