/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hzltd.module.amz.adv.client.sp.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * BulkBudgetRulesAssociationResponse
 */
@JsonPropertyOrder({
  BulkBudgetRulesAssociationResponse.JSON_PROPERTY_BUDGET_RULES_ASSOCIATIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class BulkBudgetRulesAssociationResponse {
  public static final String JSON_PROPERTY_BUDGET_RULES_ASSOCIATIONS = "budgetRulesAssociations";
  @javax.annotation.Nullable
  private BulkBudgetRulesAssociationResponseBudgetRulesAssociations budgetRulesAssociations;

  public BulkBudgetRulesAssociationResponse() { 
  }

  public BulkBudgetRulesAssociationResponse budgetRulesAssociations(@javax.annotation.Nullable BulkBudgetRulesAssociationResponseBudgetRulesAssociations budgetRulesAssociations) {
    this.budgetRulesAssociations = budgetRulesAssociations;
    return this;
  }

  /**
   * Get budgetRulesAssociations
   * @return budgetRulesAssociations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUDGET_RULES_ASSOCIATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BulkBudgetRulesAssociationResponseBudgetRulesAssociations getBudgetRulesAssociations() {
    return budgetRulesAssociations;
  }


  @JsonProperty(value = JSON_PROPERTY_BUDGET_RULES_ASSOCIATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBudgetRulesAssociations(@javax.annotation.Nullable BulkBudgetRulesAssociationResponseBudgetRulesAssociations budgetRulesAssociations) {
    this.budgetRulesAssociations = budgetRulesAssociations;
  }


  /**
   * Return true if this BulkBudgetRulesAssociationResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkBudgetRulesAssociationResponse bulkBudgetRulesAssociationResponse = (BulkBudgetRulesAssociationResponse) o;
    return Objects.equals(this.budgetRulesAssociations, bulkBudgetRulesAssociationResponse.budgetRulesAssociations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budgetRulesAssociations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkBudgetRulesAssociationResponse {\n");
    sb.append("    budgetRulesAssociations: ").append(toIndentedString(budgetRulesAssociations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `budgetRulesAssociations` to the URL query string
    if (getBudgetRulesAssociations() != null) {
      joiner.add(getBudgetRulesAssociations().toUrlQueryString(prefix + "budgetRulesAssociations" + suffix));
    }

    return joiner.toString();
  }
}

