/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.Promotion.V202406;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * SearchCouponsRequestBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-30T06:06:20.240402Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class SearchCouponsRequestBody {
  public static final String SERIALIZED_NAME_DISPLAY_TYPE = "display_type";
  @SerializedName(SERIALIZED_NAME_DISPLAY_TYPE)
  private List<String> displayType = new ArrayList<>();

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private List<String> status = new ArrayList<>();

  public static final String SERIALIZED_NAME_TITLE_KEYWORD = "title_keyword";
  @SerializedName(SERIALIZED_NAME_TITLE_KEYWORD)
  private String titleKeyword;

  public SearchCouponsRequestBody() {
  }

  public SearchCouponsRequestBody displayType(List<String> displayType) {
    this.displayType = displayType;
    return this;
  }

  public SearchCouponsRequestBody addDisplayTypeItem(String displayTypeItem) {
    if (this.displayType == null) {
      this.displayType = new ArrayList<>();
    }
    this.displayType.add(displayTypeItem);
    return this;
  }

   /**
   * The display type of coupons. Values: - &#x60;REGULAR&#x60;: Regular coupons which are displayed to TikTok users across all display locations available in TTS, including PLPs, PDPs, TikTok Videos, LIVE Rooms, Creator Showcases, and may be shared via TTS Customer Support instant messages. Includes coupons which target select customer segments. - &#x60;LIVE&#x60;: Coupons which are only displayed to TikTok users in LIVE Rooms. - &#x60;CREATOR_EXCLUSIVE&#x60;: Coupons that can be claimed through the display channels of the specified creator, such as their LIVE Rooms, and their Creator Showcase. - &#x60;CHAT&#x60;: Exclusive coupons that may be sent to customers via TTS customer support chat messages, but are not displayed in other display locations. - &#x60;PROMO_CODE&#x60;: Promo codes do not have dedicated display locations on TikTok, but may be shared with customers in LIVEs, in TikTok videos, or other social media platforms. They can be claimed by customers entering a claim code at checkout or by customers that use a custom promo code landing page URL.
   * @return displayType
  **/
  @javax.annotation.Nullable
  public List<String> getDisplayType() {
    return displayType;
  }

  public void setDisplayType(List<String> displayType) {
    this.displayType = displayType;
  }


  public SearchCouponsRequestBody status(List<String> status) {
    this.status = status;
    return this;
  }

  public SearchCouponsRequestBody addStatusItem(String statusItem) {
    if (this.status == null) {
      this.status = new ArrayList<>();
    }
    this.status.add(statusItem);
    return this;
  }

   /**
   * Coupon&#39;s promotion status. Values: - &#x60;NOT_START&#x60;: Not available to TikTok users until the coupon&#39;s configured start time. - &#x60;ONGOING&#x60;: Available to TikTok users. - &#x60;EXPIRED&#x60;: Not available to TikTok users because it has expired. - &#x60;DEACTIVATED&#x60;: Deactivated by the seller and is not available to TikTok users.
   * @return status
  **/
  @javax.annotation.Nullable
  public List<String> getStatus() {
    return status;
  }

  public void setStatus(List<String> status) {
    this.status = status;
  }


  public SearchCouponsRequestBody titleKeyword(String titleKeyword) {
    this.titleKeyword = titleKeyword;
    return this;
  }

   /**
   * Keywords in the coupon titles to search for. The range of the length is &#x60;(0, 100]&#x60;. Fuzzy matching not supported.
   * @return titleKeyword
  **/
  @javax.annotation.Nullable
  public String getTitleKeyword() {
    return titleKeyword;
  }

  public void setTitleKeyword(String titleKeyword) {
    this.titleKeyword = titleKeyword;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCouponsRequestBody promotion202406SearchCouponsRequestBody = (SearchCouponsRequestBody) o;
    return Objects.equals(this.displayType, promotion202406SearchCouponsRequestBody.displayType) &&
        Objects.equals(this.status, promotion202406SearchCouponsRequestBody.status) &&
        Objects.equals(this.titleKeyword, promotion202406SearchCouponsRequestBody.titleKeyword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayType, status, titleKeyword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCouponsRequestBody {\n");
    sb.append("    displayType: ").append(toIndentedString(displayType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    titleKeyword: ").append(toIndentedString(titleKeyword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("display_type");
    openapiFields.add("status");
    openapiFields.add("title_keyword");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SearchCouponsRequestBody
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchCouponsRequestBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchCouponsRequestBody is not found in the empty JSON string", SearchCouponsRequestBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchCouponsRequestBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchCouponsRequestBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("display_type") != null && !jsonObj.get("display_type").isJsonNull() && !jsonObj.get("display_type").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `display_type` to be an array in the JSON string but got `%s`", jsonObj.get("display_type").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull() && !jsonObj.get("status").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be an array in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("title_keyword") != null && !jsonObj.get("title_keyword").isJsonNull()) && !jsonObj.get("title_keyword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title_keyword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title_keyword").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchCouponsRequestBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchCouponsRequestBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchCouponsRequestBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchCouponsRequestBody.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchCouponsRequestBody>() {
           @Override
           public void write(JsonWriter out, SearchCouponsRequestBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchCouponsRequestBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SearchCouponsRequestBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SearchCouponsRequestBody
  * @throws IOException if the JSON string is invalid with respect to SearchCouponsRequestBody
  */
  public static SearchCouponsRequestBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchCouponsRequestBody.class);
  }

 /**
  * Convert an instance of SearchCouponsRequestBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

