/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.Order.V202309;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import tiktokshop.open.sdk_java.model.Order.V202309.GetOrderListResponseDataOrdersHandlingDuration;
import tiktokshop.open.sdk_java.model.Order.V202309.GetOrderListResponseDataOrdersLineItems;
import tiktokshop.open.sdk_java.model.Order.V202309.GetOrderListResponseDataOrdersPackages;
import tiktokshop.open.sdk_java.model.Order.V202309.GetOrderListResponseDataOrdersPayment;
import tiktokshop.open.sdk_java.model.Order.V202309.GetOrderListResponseDataOrdersRecipientAddress;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * GetOrderListResponseDataOrders
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-28T03:28:06.328409Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class GetOrderListResponseDataOrders {
  public static final String SERIALIZED_NAME_AUTO_COMBINE_GROUP_ID = "auto_combine_group_id";
  @SerializedName(SERIALIZED_NAME_AUTO_COMBINE_GROUP_ID)
  @javax.annotation.Nullable
  private String autoCombineGroupId;

  public static final String SERIALIZED_NAME_BUYER_EMAIL = "buyer_email";
  @SerializedName(SERIALIZED_NAME_BUYER_EMAIL)
  @javax.annotation.Nullable
  private String buyerEmail;

  public static final String SERIALIZED_NAME_BUYER_MESSAGE = "buyer_message";
  @SerializedName(SERIALIZED_NAME_BUYER_MESSAGE)
  @javax.annotation.Nullable
  private String buyerMessage;

  public static final String SERIALIZED_NAME_CANCEL_ORDER_SLA_TIME = "cancel_order_sla_time";
  @SerializedName(SERIALIZED_NAME_CANCEL_ORDER_SLA_TIME)
  @javax.annotation.Nullable
  private Long cancelOrderSlaTime;

  public static final String SERIALIZED_NAME_CANCEL_REASON = "cancel_reason";
  @SerializedName(SERIALIZED_NAME_CANCEL_REASON)
  @javax.annotation.Nullable
  private String cancelReason;

  public static final String SERIALIZED_NAME_CANCEL_TIME = "cancel_time";
  @SerializedName(SERIALIZED_NAME_CANCEL_TIME)
  @javax.annotation.Nullable
  private Long cancelTime;

  public static final String SERIALIZED_NAME_CANCELLATION_INITIATOR = "cancellation_initiator";
  @SerializedName(SERIALIZED_NAME_CANCELLATION_INITIATOR)
  @javax.annotation.Nullable
  private String cancellationInitiator;

  public static final String SERIALIZED_NAME_COLLECTION_DUE_TIME = "collection_due_time";
  @SerializedName(SERIALIZED_NAME_COLLECTION_DUE_TIME)
  @javax.annotation.Nullable
  private Long collectionDueTime;

  public static final String SERIALIZED_NAME_COLLECTION_TIME = "collection_time";
  @SerializedName(SERIALIZED_NAME_COLLECTION_TIME)
  @javax.annotation.Nullable
  private Long collectionTime;

  public static final String SERIALIZED_NAME_COMMERCE_PLATFORM = "commerce_platform";
  @SerializedName(SERIALIZED_NAME_COMMERCE_PLATFORM)
  @javax.annotation.Nullable
  private String commercePlatform;

  public static final String SERIALIZED_NAME_CONSULTATION_ID = "consultation_id";
  @SerializedName(SERIALIZED_NAME_CONSULTATION_ID)
  @javax.annotation.Nullable
  private String consultationId;

  public static final String SERIALIZED_NAME_CPF = "cpf";
  @SerializedName(SERIALIZED_NAME_CPF)
  @javax.annotation.Nullable
  private String cpf;

  public static final String SERIALIZED_NAME_CPF_NAME = "cpf_name";
  @SerializedName(SERIALIZED_NAME_CPF_NAME)
  @javax.annotation.Nullable
  private String cpfName;

  public static final String SERIALIZED_NAME_CREATE_TIME = "create_time";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  @javax.annotation.Nullable
  private Long createTime;

  public static final String SERIALIZED_NAME_DELIVERY_DUE_TIME = "delivery_due_time";
  @SerializedName(SERIALIZED_NAME_DELIVERY_DUE_TIME)
  @javax.annotation.Nullable
  private Long deliveryDueTime;

  public static final String SERIALIZED_NAME_DELIVERY_OPTION_ID = "delivery_option_id";
  @SerializedName(SERIALIZED_NAME_DELIVERY_OPTION_ID)
  @javax.annotation.Nullable
  private String deliveryOptionId;

  public static final String SERIALIZED_NAME_DELIVERY_OPTION_NAME = "delivery_option_name";
  @SerializedName(SERIALIZED_NAME_DELIVERY_OPTION_NAME)
  @javax.annotation.Nullable
  private String deliveryOptionName;

  public static final String SERIALIZED_NAME_DELIVERY_OPTION_REQUIRED_DELIVERY_TIME = "delivery_option_required_delivery_time";
  @SerializedName(SERIALIZED_NAME_DELIVERY_OPTION_REQUIRED_DELIVERY_TIME)
  @javax.annotation.Nullable
  private Long deliveryOptionRequiredDeliveryTime;

  public static final String SERIALIZED_NAME_DELIVERY_SLA_TIME = "delivery_sla_time";
  @SerializedName(SERIALIZED_NAME_DELIVERY_SLA_TIME)
  @javax.annotation.Nullable
  private Long deliverySlaTime;

  public static final String SERIALIZED_NAME_DELIVERY_TIME = "delivery_time";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TIME)
  @javax.annotation.Nullable
  private Long deliveryTime;

  public static final String SERIALIZED_NAME_DELIVERY_TYPE = "delivery_type";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TYPE)
  @javax.annotation.Nullable
  private String deliveryType;

  public static final String SERIALIZED_NAME_EXCHANGE_SOURCE_ORDER_ID = "exchange_source_order_id";
  @SerializedName(SERIALIZED_NAME_EXCHANGE_SOURCE_ORDER_ID)
  @javax.annotation.Nullable
  private String exchangeSourceOrderId;

  public static final String SERIALIZED_NAME_FAST_DELIVERY_PROGRAM = "fast_delivery_program";
  @SerializedName(SERIALIZED_NAME_FAST_DELIVERY_PROGRAM)
  @javax.annotation.Nullable
  private String fastDeliveryProgram;

  public static final String SERIALIZED_NAME_FAST_DISPATCH_SLA_TIME = "fast_dispatch_sla_time";
  @SerializedName(SERIALIZED_NAME_FAST_DISPATCH_SLA_TIME)
  @javax.annotation.Nullable
  private Long fastDispatchSlaTime;

  public static final String SERIALIZED_NAME_FULFILLMENT_PRIORITY_LEVEL = "fulfillment_priority_level";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_PRIORITY_LEVEL)
  @javax.annotation.Nullable
  private Integer fulfillmentPriorityLevel;

  public static final String SERIALIZED_NAME_FULFILLMENT_TYPE = "fulfillment_type";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_TYPE)
  @javax.annotation.Nullable
  private String fulfillmentType;

  public static final String SERIALIZED_NAME_HANDLING_DURATION = "handling_duration";
  @SerializedName(SERIALIZED_NAME_HANDLING_DURATION)
  @javax.annotation.Nullable
  private GetOrderListResponseDataOrdersHandlingDuration handlingDuration;

  public static final String SERIALIZED_NAME_HAS_UPDATED_RECIPIENT_ADDRESS = "has_updated_recipient_address";
  @SerializedName(SERIALIZED_NAME_HAS_UPDATED_RECIPIENT_ADDRESS)
  @javax.annotation.Nullable
  private Boolean hasUpdatedRecipientAddress;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_IS_BUYER_REQUEST_CANCEL = "is_buyer_request_cancel";
  @SerializedName(SERIALIZED_NAME_IS_BUYER_REQUEST_CANCEL)
  @javax.annotation.Nullable
  private Boolean isBuyerRequestCancel;

  public static final String SERIALIZED_NAME_IS_COD = "is_cod";
  @SerializedName(SERIALIZED_NAME_IS_COD)
  @javax.annotation.Nullable
  private Boolean isCod;

  public static final String SERIALIZED_NAME_IS_EXCHANGE_ORDER = "is_exchange_order";
  @SerializedName(SERIALIZED_NAME_IS_EXCHANGE_ORDER)
  @javax.annotation.Nullable
  private Boolean isExchangeOrder;

  public static final String SERIALIZED_NAME_IS_ON_HOLD_ORDER = "is_on_hold_order";
  @SerializedName(SERIALIZED_NAME_IS_ON_HOLD_ORDER)
  @javax.annotation.Nullable
  private Boolean isOnHoldOrder;

  public static final String SERIALIZED_NAME_IS_REPLACEMENT_ORDER = "is_replacement_order";
  @SerializedName(SERIALIZED_NAME_IS_REPLACEMENT_ORDER)
  @javax.annotation.Nullable
  private Boolean isReplacementOrder;

  public static final String SERIALIZED_NAME_IS_SAMPLE_ORDER = "is_sample_order";
  @SerializedName(SERIALIZED_NAME_IS_SAMPLE_ORDER)
  @javax.annotation.Nullable
  private Boolean isSampleOrder;

  public static final String SERIALIZED_NAME_LINE_ITEMS = "line_items";
  @SerializedName(SERIALIZED_NAME_LINE_ITEMS)
  @javax.annotation.Nullable
  private List<GetOrderListResponseDataOrdersLineItems> lineItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_NEED_UPLOAD_INVOICE = "need_upload_invoice";
  @SerializedName(SERIALIZED_NAME_NEED_UPLOAD_INVOICE)
  @javax.annotation.Nullable
  private String needUploadInvoice;

  public static final String SERIALIZED_NAME_ORDER_TYPE = "order_type";
  @SerializedName(SERIALIZED_NAME_ORDER_TYPE)
  @javax.annotation.Nullable
  private String orderType;

  public static final String SERIALIZED_NAME_PACKAGES = "packages";
  @SerializedName(SERIALIZED_NAME_PACKAGES)
  @javax.annotation.Nullable
  private List<GetOrderListResponseDataOrdersPackages> packages = new ArrayList<>();

  public static final String SERIALIZED_NAME_PAID_TIME = "paid_time";
  @SerializedName(SERIALIZED_NAME_PAID_TIME)
  @javax.annotation.Nullable
  private Long paidTime;

  public static final String SERIALIZED_NAME_PAYMENT = "payment";
  @SerializedName(SERIALIZED_NAME_PAYMENT)
  @javax.annotation.Nullable
  private GetOrderListResponseDataOrdersPayment payment;

  public static final String SERIALIZED_NAME_PAYMENT_METHOD_NAME = "payment_method_name";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD_NAME)
  @javax.annotation.Nullable
  private String paymentMethodName;

  public static final String SERIALIZED_NAME_PICK_UP_CUT_OFF_TIME = "pick_up_cut_off_time";
  @SerializedName(SERIALIZED_NAME_PICK_UP_CUT_OFF_TIME)
  @javax.annotation.Nullable
  private Long pickUpCutOffTime;

  public static final String SERIALIZED_NAME_RECIPIENT_ADDRESS = "recipient_address";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_ADDRESS)
  @javax.annotation.Nullable
  private GetOrderListResponseDataOrdersRecipientAddress recipientAddress;

  public static final String SERIALIZED_NAME_RECOMMENDED_SHIPPING_TIME = "recommended_shipping_time";
  @SerializedName(SERIALIZED_NAME_RECOMMENDED_SHIPPING_TIME)
  @javax.annotation.Nullable
  private Long recommendedShippingTime;

  public static final String SERIALIZED_NAME_RELEASE_DATE = "release_date";
  @SerializedName(SERIALIZED_NAME_RELEASE_DATE)
  @javax.annotation.Nullable
  private Long releaseDate;

  public static final String SERIALIZED_NAME_REPLACED_ORDER_ID = "replaced_order_id";
  @SerializedName(SERIALIZED_NAME_REPLACED_ORDER_ID)
  @javax.annotation.Nullable
  private String replacedOrderId;

  public static final String SERIALIZED_NAME_REQUEST_CANCEL_TIME = "request_cancel_time";
  @SerializedName(SERIALIZED_NAME_REQUEST_CANCEL_TIME)
  @javax.annotation.Nullable
  private Long requestCancelTime;

  public static final String SERIALIZED_NAME_RTS_SLA_TIME = "rts_sla_time";
  @SerializedName(SERIALIZED_NAME_RTS_SLA_TIME)
  @javax.annotation.Nullable
  private Long rtsSlaTime;

  public static final String SERIALIZED_NAME_RTS_TIME = "rts_time";
  @SerializedName(SERIALIZED_NAME_RTS_TIME)
  @javax.annotation.Nullable
  private Long rtsTime;

  public static final String SERIALIZED_NAME_SELLER_NOTE = "seller_note";
  @SerializedName(SERIALIZED_NAME_SELLER_NOTE)
  @javax.annotation.Nullable
  private String sellerNote;

  public static final String SERIALIZED_NAME_SHIPPING_DUE_TIME = "shipping_due_time";
  @SerializedName(SERIALIZED_NAME_SHIPPING_DUE_TIME)
  @javax.annotation.Nullable
  private Long shippingDueTime;

  public static final String SERIALIZED_NAME_SHIPPING_PROVIDER = "shipping_provider";
  @SerializedName(SERIALIZED_NAME_SHIPPING_PROVIDER)
  @javax.annotation.Nullable
  private String shippingProvider;

  public static final String SERIALIZED_NAME_SHIPPING_PROVIDER_ID = "shipping_provider_id";
  @SerializedName(SERIALIZED_NAME_SHIPPING_PROVIDER_ID)
  @javax.annotation.Nullable
  private String shippingProviderId;

  public static final String SERIALIZED_NAME_SHIPPING_TYPE = "shipping_type";
  @SerializedName(SERIALIZED_NAME_SHIPPING_TYPE)
  @javax.annotation.Nullable
  private String shippingType;

  public static final String SERIALIZED_NAME_SPLIT_OR_COMBINE_TAG = "split_or_combine_tag";
  @SerializedName(SERIALIZED_NAME_SPLIT_OR_COMBINE_TAG)
  @javax.annotation.Nullable
  private String splitOrCombineTag;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_TRACKING_NUMBER = "tracking_number";
  @SerializedName(SERIALIZED_NAME_TRACKING_NUMBER)
  @javax.annotation.Nullable
  private String trackingNumber;

  public static final String SERIALIZED_NAME_TTS_SLA_TIME = "tts_sla_time";
  @SerializedName(SERIALIZED_NAME_TTS_SLA_TIME)
  @javax.annotation.Nullable
  private Long ttsSlaTime;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "update_time";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  @javax.annotation.Nullable
  private Long updateTime;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_WAREHOUSE_ID = "warehouse_id";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_ID)
  @javax.annotation.Nullable
  private String warehouseId;

  public GetOrderListResponseDataOrders() {
  }

  public GetOrderListResponseDataOrders autoCombineGroupId(@javax.annotation.Nullable String autoCombineGroupId) {
    this.autoCombineGroupId = autoCombineGroupId;
    return this;
  }

  /**
   * An identifier assigned to orders from the same customer during a LIVE session to facilitate combined order shipping when \&quot;auto-combination\&quot; is activated in Seller Center.
   * @return autoCombineGroupId
   */
  @javax.annotation.Nullable
  public String getAutoCombineGroupId() {
    return autoCombineGroupId;
  }

  public void setAutoCombineGroupId(@javax.annotation.Nullable String autoCombineGroupId) {
    this.autoCombineGroupId = autoCombineGroupId;
  }


  public GetOrderListResponseDataOrders buyerEmail(@javax.annotation.Nullable String buyerEmail) {
    this.buyerEmail = buyerEmail;
    return this;
  }

  /**
   * The anonymized email address of the buyer. It is not recommended to send messages directly to this email address. If you need to contact the buyer, please go to the TikTok Shop Seller Center - Buyer Messages page.
   * @return buyerEmail
   */
  @javax.annotation.Nullable
  public String getBuyerEmail() {
    return buyerEmail;
  }

  public void setBuyerEmail(@javax.annotation.Nullable String buyerEmail) {
    this.buyerEmail = buyerEmail;
  }


  public GetOrderListResponseDataOrders buyerMessage(@javax.annotation.Nullable String buyerMessage) {
    this.buyerMessage = buyerMessage;
    return this;
  }

  /**
   * The note from the buyer.
   * @return buyerMessage
   */
  @javax.annotation.Nullable
  public String getBuyerMessage() {
    return buyerMessage;
  }

  public void setBuyerMessage(@javax.annotation.Nullable String buyerMessage) {
    this.buyerMessage = buyerMessage;
  }


  public GetOrderListResponseDataOrders cancelOrderSlaTime(@javax.annotation.Nullable Long cancelOrderSlaTime) {
    this.cancelOrderSlaTime = cancelOrderSlaTime;
    return this;
  }

  /**
   * The automatic cancellation time for orders specified by the platform. Unix timestamp.
   * @return cancelOrderSlaTime
   */
  @javax.annotation.Nullable
  public Long getCancelOrderSlaTime() {
    return cancelOrderSlaTime;
  }

  public void setCancelOrderSlaTime(@javax.annotation.Nullable Long cancelOrderSlaTime) {
    this.cancelOrderSlaTime = cancelOrderSlaTime;
  }


  public GetOrderListResponseDataOrders cancelReason(@javax.annotation.Nullable String cancelReason) {
    this.cancelReason = cancelReason;
    return this;
  }

  /**
   * The cancellation reason. Please visit [our list of cancel reasons](https://partner.tiktokshop.com/docv2/page/67e61eee427345048595487d) for more information.
   * @return cancelReason
   */
  @javax.annotation.Nullable
  public String getCancelReason() {
    return cancelReason;
  }

  public void setCancelReason(@javax.annotation.Nullable String cancelReason) {
    this.cancelReason = cancelReason;
  }


  public GetOrderListResponseDataOrders cancelTime(@javax.annotation.Nullable Long cancelTime) {
    this.cancelTime = cancelTime;
    return this;
  }

  /**
   * The time an order&#39;s status was updated to &#x60;CANCELLED&#x60;. Unix timestamp.
   * @return cancelTime
   */
  @javax.annotation.Nullable
  public Long getCancelTime() {
    return cancelTime;
  }

  public void setCancelTime(@javax.annotation.Nullable Long cancelTime) {
    this.cancelTime = cancelTime;
  }


  public GetOrderListResponseDataOrders cancellationInitiator(@javax.annotation.Nullable String cancellationInitiator) {
    this.cancellationInitiator = cancellationInitiator;
    return this;
  }

  /**
   * Cancellation request initiator.  Available values:  - &#x60;SELLER&#x60; - &#x60;BUYER&#x60; - &#x60;SYSTEM&#x60; 
   * @return cancellationInitiator
   */
  @javax.annotation.Nullable
  public String getCancellationInitiator() {
    return cancellationInitiator;
  }

  public void setCancellationInitiator(@javax.annotation.Nullable String cancellationInitiator) {
    this.cancellationInitiator = cancellationInitiator;
  }


  public GetOrderListResponseDataOrders collectionDueTime(@javax.annotation.Nullable Long collectionDueTime) {
    this.collectionDueTime = collectionDueTime;
    return this;
  }

  /**
   * If the order hasn&#39;t updated its status to &#x60;IN_TRANSIT&#x60; before this time, the order will be canceled by TikTok Shop. Unix timestamp.
   * @return collectionDueTime
   */
  @javax.annotation.Nullable
  public Long getCollectionDueTime() {
    return collectionDueTime;
  }

  public void setCollectionDueTime(@javax.annotation.Nullable Long collectionDueTime) {
    this.collectionDueTime = collectionDueTime;
  }


  public GetOrderListResponseDataOrders collectionTime(@javax.annotation.Nullable Long collectionTime) {
    this.collectionTime = collectionTime;
    return this;
  }

  /**
   * The time an order&#39;s status has been updated to &#x60;IN_TRANSIT&#x60;. Unix timestamp.
   * @return collectionTime
   */
  @javax.annotation.Nullable
  public Long getCollectionTime() {
    return collectionTime;
  }

  public void setCollectionTime(@javax.annotation.Nullable Long collectionTime) {
    this.collectionTime = collectionTime;
  }


  public GetOrderListResponseDataOrders commercePlatform(@javax.annotation.Nullable String commercePlatform) {
    this.commercePlatform = commercePlatform;
    return this;
  }

  /**
   * The platform where the order was placed. Possible values: - &#x60;TIKTOK_SHOP&#x60; - &#x60;TOKOPEDIA&#x60;  **Note**: Available only in the Indonesia market.
   * @return commercePlatform
   */
  @javax.annotation.Nullable
  public String getCommercePlatform() {
    return commercePlatform;
  }

  public void setCommercePlatform(@javax.annotation.Nullable String commercePlatform) {
    this.commercePlatform = commercePlatform;
  }


  public GetOrderListResponseDataOrders consultationId(@javax.annotation.Nullable String consultationId) {
    this.consultationId = consultationId;
    return this;
  }

  /**
   * An ID to identify the corresponding ePharmacy consultation.  Applicable only if an ePharmacy consultation was initiated. Not applicable if the prescription was provided by the customer through an image upload.
   * @return consultationId
   */
  @javax.annotation.Nullable
  public String getConsultationId() {
    return consultationId;
  }

  public void setConsultationId(@javax.annotation.Nullable String consultationId) {
    this.consultationId = consultationId;
  }


  public GetOrderListResponseDataOrders cpf(@javax.annotation.Nullable String cpf) {
    this.cpf = cpf;
    return this;
  }

  /**
   * CPF (invoice number), used to issue an invoice.  **Note**: Only available in the Brazil market.
   * @return cpf
   */
  @javax.annotation.Nullable
  public String getCpf() {
    return cpf;
  }

  public void setCpf(@javax.annotation.Nullable String cpf) {
    this.cpf = cpf;
  }


  public GetOrderListResponseDataOrders cpfName(@javax.annotation.Nullable String cpfName) {
    this.cpfName = cpfName;
    return this;
  }

  /**
   * Name belonging to the CPF number for the Brazil market. 
   * @return cpfName
   */
  @javax.annotation.Nullable
  public String getCpfName() {
    return cpfName;
  }

  public void setCpfName(@javax.annotation.Nullable String cpfName) {
    this.cpfName = cpfName;
  }


  public GetOrderListResponseDataOrders createTime(@javax.annotation.Nullable Long createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * The date and time that the order was created. Unix timestamp.
   * @return createTime
   */
  @javax.annotation.Nullable
  public Long getCreateTime() {
    return createTime;
  }

  public void setCreateTime(@javax.annotation.Nullable Long createTime) {
    this.createTime = createTime;
  }


  public GetOrderListResponseDataOrders deliveryDueTime(@javax.annotation.Nullable Long deliveryDueTime) {
    this.deliveryDueTime = deliveryDueTime;
    return this;
  }

  /**
   * If the order hasn&#39;t updated its status to &#x60;DELIVERED&#x60; before this time, the order will be automatically canceled by TikTok Shop. Unix timestamp.
   * @return deliveryDueTime
   */
  @javax.annotation.Nullable
  public Long getDeliveryDueTime() {
    return deliveryDueTime;
  }

  public void setDeliveryDueTime(@javax.annotation.Nullable Long deliveryDueTime) {
    this.deliveryDueTime = deliveryDueTime;
  }


  public GetOrderListResponseDataOrders deliveryOptionId(@javax.annotation.Nullable String deliveryOptionId) {
    this.deliveryOptionId = deliveryOptionId;
    return this;
  }

  /**
   * Delivery option ID is mapped to seller configured logistics templates ID.
   * @return deliveryOptionId
   */
  @javax.annotation.Nullable
  public String getDeliveryOptionId() {
    return deliveryOptionId;
  }

  public void setDeliveryOptionId(@javax.annotation.Nullable String deliveryOptionId) {
    this.deliveryOptionId = deliveryOptionId;
  }


  public GetOrderListResponseDataOrders deliveryOptionName(@javax.annotation.Nullable String deliveryOptionName) {
    this.deliveryOptionName = deliveryOptionName;
    return this;
  }

  /**
   * Delivery option name. For display purposes only. Available values: - &#x60;Economy Shipping&#x60; - &#x60;Standard Shipping&#x60; - &#x60;Express Shipping&#x60;
   * @return deliveryOptionName
   */
  @javax.annotation.Nullable
  public String getDeliveryOptionName() {
    return deliveryOptionName;
  }

  public void setDeliveryOptionName(@javax.annotation.Nullable String deliveryOptionName) {
    this.deliveryOptionName = deliveryOptionName;
  }


  public GetOrderListResponseDataOrders deliveryOptionRequiredDeliveryTime(@javax.annotation.Nullable Long deliveryOptionRequiredDeliveryTime) {
    this.deliveryOptionRequiredDeliveryTime = deliveryOptionRequiredDeliveryTime;
    return this;
  }

  /**
   *  Order should be delivered before this time. Unix timestamp.
   * @return deliveryOptionRequiredDeliveryTime
   */
  @javax.annotation.Nullable
  public Long getDeliveryOptionRequiredDeliveryTime() {
    return deliveryOptionRequiredDeliveryTime;
  }

  public void setDeliveryOptionRequiredDeliveryTime(@javax.annotation.Nullable Long deliveryOptionRequiredDeliveryTime) {
    this.deliveryOptionRequiredDeliveryTime = deliveryOptionRequiredDeliveryTime;
  }


  public GetOrderListResponseDataOrders deliverySlaTime(@javax.annotation.Nullable Long deliverySlaTime) {
    this.deliverySlaTime = deliverySlaTime;
    return this;
  }

  /**
   * Order should arrive by this date to be considered on-time and to avoid late delivery penalties.
   * @return deliverySlaTime
   */
  @javax.annotation.Nullable
  public Long getDeliverySlaTime() {
    return deliverySlaTime;
  }

  public void setDeliverySlaTime(@javax.annotation.Nullable Long deliverySlaTime) {
    this.deliverySlaTime = deliverySlaTime;
  }


  public GetOrderListResponseDataOrders deliveryTime(@javax.annotation.Nullable Long deliveryTime) {
    this.deliveryTime = deliveryTime;
    return this;
  }

  /**
   * The time an order&#39;s status changed to &#x60;DELIVERED&#x60;. Unix timestamp.
   * @return deliveryTime
   */
  @javax.annotation.Nullable
  public Long getDeliveryTime() {
    return deliveryTime;
  }

  public void setDeliveryTime(@javax.annotation.Nullable Long deliveryTime) {
    this.deliveryTime = deliveryTime;
  }


  public GetOrderListResponseDataOrders deliveryType(@javax.annotation.Nullable String deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Indicates whether it is a Pick-Up Drop-Off (PUDO) location. The PUDO location is selected by the buyer when placing orders. Available values: - &#x60;HOME_DELIVERY&#x60;: not a PUDO location - &#x60;COLLECTION_POINT&#x60;: a PUDO location
   * @return deliveryType
   */
  @javax.annotation.Nullable
  public String getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(@javax.annotation.Nullable String deliveryType) {
    this.deliveryType = deliveryType;
  }


  public GetOrderListResponseDataOrders exchangeSourceOrderId(@javax.annotation.Nullable String exchangeSourceOrderId) {
    this.exchangeSourceOrderId = exchangeSourceOrderId;
    return this;
  }

  /**
   * If the order is an exchange order, this field returns the original order&#39;s order ID, from which the exchange order was generated.   Returned only if is_exchange_order &#x3D; true.  Note: Only available in US and UK.
   * @return exchangeSourceOrderId
   */
  @javax.annotation.Nullable
  public String getExchangeSourceOrderId() {
    return exchangeSourceOrderId;
  }

  public void setExchangeSourceOrderId(@javax.annotation.Nullable String exchangeSourceOrderId) {
    this.exchangeSourceOrderId = exchangeSourceOrderId;
  }


  public GetOrderListResponseDataOrders fastDeliveryProgram(@javax.annotation.Nullable String fastDeliveryProgram) {
    this.fastDeliveryProgram = fastDeliveryProgram;
    return this;
  }

  /**
   * A badge presented on the merchandise to tell the buyer that the seller participates in the fast delivery program, such that the order should arrive in a promised time period. Possible values: - &#x60;3_DAY_DELIVERY&#x60; Not returned if order did not meet fast delivery program requirements. Note: Applicable only for the US market.
   * @return fastDeliveryProgram
   */
  @javax.annotation.Nullable
  public String getFastDeliveryProgram() {
    return fastDeliveryProgram;
  }

  public void setFastDeliveryProgram(@javax.annotation.Nullable String fastDeliveryProgram) {
    this.fastDeliveryProgram = fastDeliveryProgram;
  }


  public GetOrderListResponseDataOrders fastDispatchSlaTime(@javax.annotation.Nullable Long fastDispatchSlaTime) {
    this.fastDispatchSlaTime = fastDispatchSlaTime;
    return this;
  }

  /**
   * The latest collection time to gain incentives of NDD (Next Day Delivery) project. Unix timestamp.  **Note**: Only available in Thailand and the Philippines.
   * @return fastDispatchSlaTime
   */
  @javax.annotation.Nullable
  public Long getFastDispatchSlaTime() {
    return fastDispatchSlaTime;
  }

  public void setFastDispatchSlaTime(@javax.annotation.Nullable Long fastDispatchSlaTime) {
    this.fastDispatchSlaTime = fastDispatchSlaTime;
  }


  public GetOrderListResponseDataOrders fulfillmentPriorityLevel(@javax.annotation.Nullable Integer fulfillmentPriorityLevel) {
    this.fulfillmentPriorityLevel = fulfillmentPriorityLevel;
    return this;
  }

  /**
   * Fulfillment priority value that can be used to prioritize shipping (only available in SEA)  100 &#x3D; Instant 200 &#x3D; Sameday 8 Hours  300 &#x3D; Sameday  400 &#x3D; Next Day Delivery 500 &#x3D; Express 600 &#x3D; Standard 700 &#x3D; Economy 800 &#x3D; Cargo
   * @return fulfillmentPriorityLevel
   */
  @javax.annotation.Nullable
  public Integer getFulfillmentPriorityLevel() {
    return fulfillmentPriorityLevel;
  }

  public void setFulfillmentPriorityLevel(@javax.annotation.Nullable Integer fulfillmentPriorityLevel) {
    this.fulfillmentPriorityLevel = fulfillmentPriorityLevel;
  }


  public GetOrderListResponseDataOrders fulfillmentType(@javax.annotation.Nullable String fulfillmentType) {
    this.fulfillmentType = fulfillmentType;
    return this;
  }

  /**
   * Fulfillment type. Only orders with fulfillment type can be shipped by sellers. Available values: - &#x60;FULFILLMENT_BY_SELLER&#x60;: a method where sellers fulfill orders directly from their own inventory, without using TikTok&#39;s fulfillment centers. In this model, the seller is responsible for storing, packaging, and shipping the products to customers. - &#x60;FULFILLMENT_BY_TIKTOK&#x60;: a service offered by TikTok where sellers can send their products to TikTok&#39;s fulfillment centers. TikTok then takes care of storing, picking, packing, and shipping the products to customers. - &#x60;FULFILLMENT_BY_DILAYANI_TOKOPEDIA&#x60;: a method where Tokopedia GoTo Logistics provides warehousing and logistics services to sellers and charges a fee for the service.
   * @return fulfillmentType
   */
  @javax.annotation.Nullable
  public String getFulfillmentType() {
    return fulfillmentType;
  }

  public void setFulfillmentType(@javax.annotation.Nullable String fulfillmentType) {
    this.fulfillmentType = fulfillmentType;
  }


  public GetOrderListResponseDataOrders handlingDuration(@javax.annotation.Nullable GetOrderListResponseDataOrdersHandlingDuration handlingDuration) {
    this.handlingDuration = handlingDuration;
    return this;
  }

  /**
   * Get handlingDuration
   * @return handlingDuration
   */
  @javax.annotation.Nullable
  public GetOrderListResponseDataOrdersHandlingDuration getHandlingDuration() {
    return handlingDuration;
  }

  public void setHandlingDuration(@javax.annotation.Nullable GetOrderListResponseDataOrdersHandlingDuration handlingDuration) {
    this.handlingDuration = handlingDuration;
  }


  public GetOrderListResponseDataOrders hasUpdatedRecipientAddress(@javax.annotation.Nullable Boolean hasUpdatedRecipientAddress) {
    this.hasUpdatedRecipientAddress = hasUpdatedRecipientAddress;
    return this;
  }

  /**
   * Whether the recipient address has been updated or changed.
   * @return hasUpdatedRecipientAddress
   */
  @javax.annotation.Nullable
  public Boolean getHasUpdatedRecipientAddress() {
    return hasUpdatedRecipientAddress;
  }

  public void setHasUpdatedRecipientAddress(@javax.annotation.Nullable Boolean hasUpdatedRecipientAddress) {
    this.hasUpdatedRecipientAddress = hasUpdatedRecipientAddress;
  }


  public GetOrderListResponseDataOrders id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * TikTok Shop order ID.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public GetOrderListResponseDataOrders isBuyerRequestCancel(@javax.annotation.Nullable Boolean isBuyerRequestCancel) {
    this.isBuyerRequestCancel = isBuyerRequestCancel;
    return this;
  }

  /**
   * Whether the buyer has a pending cancellation request.
   * @return isBuyerRequestCancel
   */
  @javax.annotation.Nullable
  public Boolean getIsBuyerRequestCancel() {
    return isBuyerRequestCancel;
  }

  public void setIsBuyerRequestCancel(@javax.annotation.Nullable Boolean isBuyerRequestCancel) {
    this.isBuyerRequestCancel = isBuyerRequestCancel;
  }


  public GetOrderListResponseDataOrders isCod(@javax.annotation.Nullable Boolean isCod) {
    this.isCod = isCod;
    return this;
  }

  /**
   * This option is for sellers that accept cash payment on delivery (COD). Buyers will pay in cash upon receiving the package.   Default: FALSE  Only applicable to countries where COD is supported.
   * @return isCod
   */
  @javax.annotation.Nullable
  public Boolean getIsCod() {
    return isCod;
  }

  public void setIsCod(@javax.annotation.Nullable Boolean isCod) {
    this.isCod = isCod;
  }


  public GetOrderListResponseDataOrders isExchangeOrder(@javax.annotation.Nullable Boolean isExchangeOrder) {
    this.isExchangeOrder = isExchangeOrder;
    return this;
  }

  /**
   * When TRUE, this is an exchange order.  Note: Only available in US and UK.
   * @return isExchangeOrder
   */
  @javax.annotation.Nullable
  public Boolean getIsExchangeOrder() {
    return isExchangeOrder;
  }

  public void setIsExchangeOrder(@javax.annotation.Nullable Boolean isExchangeOrder) {
    this.isExchangeOrder = isExchangeOrder;
  }


  public GetOrderListResponseDataOrders isOnHoldOrder(@javax.annotation.Nullable Boolean isOnHoldOrder) {
    this.isOnHoldOrder = isOnHoldOrder;
    return this;
  }

  /**
   * Indicates whether the order has been changed to or will be updated to &#x60;ON_HOLD&#x60; status.
   * @return isOnHoldOrder
   */
  @javax.annotation.Nullable
  public Boolean getIsOnHoldOrder() {
    return isOnHoldOrder;
  }

  public void setIsOnHoldOrder(@javax.annotation.Nullable Boolean isOnHoldOrder) {
    this.isOnHoldOrder = isOnHoldOrder;
  }


  public GetOrderListResponseDataOrders isReplacementOrder(@javax.annotation.Nullable Boolean isReplacementOrder) {
    this.isReplacementOrder = isReplacementOrder;
    return this;
  }

  /**
   * Whether this is a replacement order.
   * @return isReplacementOrder
   */
  @javax.annotation.Nullable
  public Boolean getIsReplacementOrder() {
    return isReplacementOrder;
  }

  public void setIsReplacementOrder(@javax.annotation.Nullable Boolean isReplacementOrder) {
    this.isReplacementOrder = isReplacementOrder;
  }


  public GetOrderListResponseDataOrders isSampleOrder(@javax.annotation.Nullable Boolean isSampleOrder) {
    this.isSampleOrder = isSampleOrder;
    return this;
  }

  /**
   * Use this field to determine whether the order is a sample order.
   * @return isSampleOrder
   */
  @javax.annotation.Nullable
  public Boolean getIsSampleOrder() {
    return isSampleOrder;
  }

  public void setIsSampleOrder(@javax.annotation.Nullable Boolean isSampleOrder) {
    this.isSampleOrder = isSampleOrder;
  }


  public GetOrderListResponseDataOrders lineItems(@javax.annotation.Nullable List<GetOrderListResponseDataOrdersLineItems> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public GetOrderListResponseDataOrders addLineItemsItem(GetOrderListResponseDataOrdersLineItems lineItemsItem) {
    if (this.lineItems == null) {
      this.lineItems = new ArrayList<>();
    }
    this.lineItems.add(lineItemsItem);
    return this;
  }

  /**
   * Line item info list.
   * @return lineItems
   */
  @javax.annotation.Nullable
  public List<GetOrderListResponseDataOrdersLineItems> getLineItems() {
    return lineItems;
  }

  public void setLineItems(@javax.annotation.Nullable List<GetOrderListResponseDataOrdersLineItems> lineItems) {
    this.lineItems = lineItems;
  }


  public GetOrderListResponseDataOrders needUploadInvoice(@javax.annotation.Nullable String needUploadInvoice) {
    this.needUploadInvoice = needUploadInvoice;
    return this;
  }

  /**
   * Whether an invoice needs to be uploaded and uploaded status (only for Brazil market). - UNKNOWN:  Currently unable to confirm whether an invoice is needed - NEED_INVOICE: This order requires an invoice and the invoice has not been uploaded yet - NO_NEED：This order does not require an invoice - INVOICE_UPLOADED: The invoice for this order has been uploaded and verified. If the order is split, it will be marked as \&quot;uploaded\&quot; once any sub-order&#39;s invoice is uploaded. - INVOICE_PROCESSING: The invoice for this order is currently being uploaded/cancelled. Please wait for the final result and do not repeat the operation
   * @return needUploadInvoice
   */
  @javax.annotation.Nullable
  public String getNeedUploadInvoice() {
    return needUploadInvoice;
  }

  public void setNeedUploadInvoice(@javax.annotation.Nullable String needUploadInvoice) {
    this.needUploadInvoice = needUploadInvoice;
  }


  public GetOrderListResponseDataOrders orderType(@javax.annotation.Nullable String orderType) {
    this.orderType = orderType;
    return this;
  }

  /**
   * The order type. Possible values based on region:  **All regions** - &#x60;ZERO_LOTTERY&#x60;: An order placed during a lottery event in TikTok LIVE.  **US** - &#x60;PRE_ORDER&#x60;: An advance order for items that are not yet available or released. Fulfillment starts on a specific date in the future. - &#x60;MADE_TO_ORDER&#x60;: An order for items that are produced only after the order is received. Fulfillment starts after the product is produced. - &#x60;BACK_ORDER&#x60;: An order for items that are out of stock but expected to be restocked. Fulfillment starts after the product is restocked.  Returns an empty value for standard orders or other types that don&#39;t fall into the above categories.
   * @return orderType
   */
  @javax.annotation.Nullable
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(@javax.annotation.Nullable String orderType) {
    this.orderType = orderType;
  }


  public GetOrderListResponseDataOrders packages(@javax.annotation.Nullable List<GetOrderListResponseDataOrdersPackages> packages) {
    this.packages = packages;
    return this;
  }

  public GetOrderListResponseDataOrders addPackagesItem(GetOrderListResponseDataOrdersPackages packagesItem) {
    if (this.packages == null) {
      this.packages = new ArrayList<>();
    }
    this.packages.add(packagesItem);
    return this;
  }

  /**
   * List of packages included in this order.
   * @return packages
   */
  @javax.annotation.Nullable
  public List<GetOrderListResponseDataOrdersPackages> getPackages() {
    return packages;
  }

  public void setPackages(@javax.annotation.Nullable List<GetOrderListResponseDataOrdersPackages> packages) {
    this.packages = packages;
  }


  public GetOrderListResponseDataOrders paidTime(@javax.annotation.Nullable Long paidTime) {
    this.paidTime = paidTime;
    return this;
  }

  /**
   * The date and time that the order was paid. Unix timestamp.
   * @return paidTime
   */
  @javax.annotation.Nullable
  public Long getPaidTime() {
    return paidTime;
  }

  public void setPaidTime(@javax.annotation.Nullable Long paidTime) {
    this.paidTime = paidTime;
  }


  public GetOrderListResponseDataOrders payment(@javax.annotation.Nullable GetOrderListResponseDataOrdersPayment payment) {
    this.payment = payment;
    return this;
  }

  /**
   * Get payment
   * @return payment
   */
  @javax.annotation.Nullable
  public GetOrderListResponseDataOrdersPayment getPayment() {
    return payment;
  }

  public void setPayment(@javax.annotation.Nullable GetOrderListResponseDataOrdersPayment payment) {
    this.payment = payment;
  }


  public GetOrderListResponseDataOrders paymentMethodName(@javax.annotation.Nullable String paymentMethodName) {
    this.paymentMethodName = paymentMethodName;
    return this;
  }

  /**
   * Payment method name, for display purposes.
   * @return paymentMethodName
   */
  @javax.annotation.Nullable
  public String getPaymentMethodName() {
    return paymentMethodName;
  }

  public void setPaymentMethodName(@javax.annotation.Nullable String paymentMethodName) {
    this.paymentMethodName = paymentMethodName;
  }


  public GetOrderListResponseDataOrders pickUpCutOffTime(@javax.annotation.Nullable Long pickUpCutOffTime) {
    this.pickUpCutOffTime = pickUpCutOffTime;
    return this;
  }

  /**
   * To avoid LDR, you must ensure the package is picked up by this time. Only applicable in South East Asia regions. 
   * @return pickUpCutOffTime
   */
  @javax.annotation.Nullable
  public Long getPickUpCutOffTime() {
    return pickUpCutOffTime;
  }

  public void setPickUpCutOffTime(@javax.annotation.Nullable Long pickUpCutOffTime) {
    this.pickUpCutOffTime = pickUpCutOffTime;
  }


  public GetOrderListResponseDataOrders recipientAddress(@javax.annotation.Nullable GetOrderListResponseDataOrdersRecipientAddress recipientAddress) {
    this.recipientAddress = recipientAddress;
    return this;
  }

  /**
   * Get recipientAddress
   * @return recipientAddress
   */
  @javax.annotation.Nullable
  public GetOrderListResponseDataOrdersRecipientAddress getRecipientAddress() {
    return recipientAddress;
  }

  public void setRecipientAddress(@javax.annotation.Nullable GetOrderListResponseDataOrdersRecipientAddress recipientAddress) {
    this.recipientAddress = recipientAddress;
  }


  public GetOrderListResponseDataOrders recommendedShippingTime(@javax.annotation.Nullable Long recommendedShippingTime) {
    this.recommendedShippingTime = recommendedShippingTime;
    return this;
  }

  /**
   * Recommended time to ship based on the each LSP service type (only available in SEA) 
   * @return recommendedShippingTime
   */
  @javax.annotation.Nullable
  public Long getRecommendedShippingTime() {
    return recommendedShippingTime;
  }

  public void setRecommendedShippingTime(@javax.annotation.Nullable Long recommendedShippingTime) {
    this.recommendedShippingTime = recommendedShippingTime;
  }


  public GetOrderListResponseDataOrders releaseDate(@javax.annotation.Nullable Long releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

  /**
   * The date on which order handling starts and the status of the order changes to [&#x60;AWAITING_SHIPMENT&#x60;](https://partner.tiktokshop.com/docv2/page/650b1b4bbace3e02b76d1011).  Applicable only if the &#x60;order_type&#x60; is &#x60;PRE_ORDER&#x60;.
   * @return releaseDate
   */
  @javax.annotation.Nullable
  public Long getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(@javax.annotation.Nullable Long releaseDate) {
    this.releaseDate = releaseDate;
  }


  public GetOrderListResponseDataOrders replacedOrderId(@javax.annotation.Nullable String replacedOrderId) {
    this.replacedOrderId = replacedOrderId;
    return this;
  }

  /**
   * The order Id for the order that is being replaced.   Returned only if &#x60;is_replacement_order &#x3D; true&#x60;.
   * @return replacedOrderId
   */
  @javax.annotation.Nullable
  public String getReplacedOrderId() {
    return replacedOrderId;
  }

  public void setReplacedOrderId(@javax.annotation.Nullable String replacedOrderId) {
    this.replacedOrderId = replacedOrderId;
  }


  public GetOrderListResponseDataOrders requestCancelTime(@javax.annotation.Nullable Long requestCancelTime) {
    this.requestCancelTime = requestCancelTime;
    return this;
  }

  /**
   * Buyer request cancellation time. Unix timestamp.
   * @return requestCancelTime
   */
  @javax.annotation.Nullable
  public Long getRequestCancelTime() {
    return requestCancelTime;
  }

  public void setRequestCancelTime(@javax.annotation.Nullable Long requestCancelTime) {
    this.requestCancelTime = requestCancelTime;
  }


  public GetOrderListResponseDataOrders rtsSlaTime(@javax.annotation.Nullable Long rtsSlaTime) {
    this.rtsSlaTime = rtsSlaTime;
    return this;
  }

  /**
   * The latest shipping time specified by the platform. Unix timestamp.
   * @return rtsSlaTime
   */
  @javax.annotation.Nullable
  public Long getRtsSlaTime() {
    return rtsSlaTime;
  }

  public void setRtsSlaTime(@javax.annotation.Nullable Long rtsSlaTime) {
    this.rtsSlaTime = rtsSlaTime;
  }


  public GetOrderListResponseDataOrders rtsTime(@javax.annotation.Nullable Long rtsTime) {
    this.rtsTime = rtsTime;
    return this;
  }

  /**
   * The time sellers shipped the order (called [Ship Package API](https://partner.tiktokshop.com/docv2/page/650aa4f1defece02be6e7cb1) successfully). Unix timestamp.
   * @return rtsTime
   */
  @javax.annotation.Nullable
  public Long getRtsTime() {
    return rtsTime;
  }

  public void setRtsTime(@javax.annotation.Nullable Long rtsTime) {
    this.rtsTime = rtsTime;
  }


  public GetOrderListResponseDataOrders sellerNote(@javax.annotation.Nullable String sellerNote) {
    this.sellerNote = sellerNote;
    return this;
  }

  /**
   * The seller note from TikTok Shop Seller Center.
   * @return sellerNote
   */
  @javax.annotation.Nullable
  public String getSellerNote() {
    return sellerNote;
  }

  public void setSellerNote(@javax.annotation.Nullable String sellerNote) {
    this.sellerNote = sellerNote;
  }


  public GetOrderListResponseDataOrders shippingDueTime(@javax.annotation.Nullable Long shippingDueTime) {
    this.shippingDueTime = shippingDueTime;
    return this;
  }

  /**
   * If the order hasn&#39;t updated its status to &#x60;AWAITING_COLLECTION&#x60; before this time, the order will be automatically canceled by TikTok Shop. Unix timestamp.
   * @return shippingDueTime
   */
  @javax.annotation.Nullable
  public Long getShippingDueTime() {
    return shippingDueTime;
  }

  public void setShippingDueTime(@javax.annotation.Nullable Long shippingDueTime) {
    this.shippingDueTime = shippingDueTime;
  }


  public GetOrderListResponseDataOrders shippingProvider(@javax.annotation.Nullable String shippingProvider) {
    this.shippingProvider = shippingProvider;
    return this;
  }

  /**
   * The name of the current shipping provider.
   * @return shippingProvider
   */
  @javax.annotation.Nullable
  public String getShippingProvider() {
    return shippingProvider;
  }

  public void setShippingProvider(@javax.annotation.Nullable String shippingProvider) {
    this.shippingProvider = shippingProvider;
  }


  public GetOrderListResponseDataOrders shippingProviderId(@javax.annotation.Nullable String shippingProviderId) {
    this.shippingProviderId = shippingProviderId;
    return this;
  }

  /**
   * The ID of the current shipping provider.
   * @return shippingProviderId
   */
  @javax.annotation.Nullable
  public String getShippingProviderId() {
    return shippingProviderId;
  }

  public void setShippingProviderId(@javax.annotation.Nullable String shippingProviderId) {
    this.shippingProviderId = shippingProviderId;
  }


  public GetOrderListResponseDataOrders shippingType(@javax.annotation.Nullable String shippingType) {
    this.shippingType = shippingType;
    return this;
  }

  /**
   * Delivery method. Available values: - &#x60;TIKTOK&#x60;: Shipping service provided by TikTok. The seller should obtain shipping label from TikTok. - &#x60;SELLER&#x60;: Seller provides shipping, including through 3rd party fulfillment providers on behalf of the seller.
   * @return shippingType
   */
  @javax.annotation.Nullable
  public String getShippingType() {
    return shippingType;
  }

  public void setShippingType(@javax.annotation.Nullable String shippingType) {
    this.shippingType = shippingType;
  }


  public GetOrderListResponseDataOrders splitOrCombineTag(@javax.annotation.Nullable String splitOrCombineTag) {
    this.splitOrCombineTag = splitOrCombineTag;
    return this;
  }

  /**
   * Indicates whether the order is combined or split: - &#x60;COMBINED&#x60; - &#x60;SPLIT&#x60;  This field will be used in future fulfillment APIs.
   * @return splitOrCombineTag
   */
  @javax.annotation.Nullable
  public String getSplitOrCombineTag() {
    return splitOrCombineTag;
  }

  public void setSplitOrCombineTag(@javax.annotation.Nullable String splitOrCombineTag) {
    this.splitOrCombineTag = splitOrCombineTag;
  }


  public GetOrderListResponseDataOrders status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Specific order status. Available values: - &#x60;UNPAID&#x60;: The order has been placed, but payment has not been completed. - &#x60;ON_HOLD&#x60;: The order has been accepted and is awaiting fulfillment. The buyer may still cancel without the seller’s approval. If &#x60;order_type&#x3D;PRE_ORDER&#x60;, the product is still awaiting release so payment will only be authorized 1 day before the release, but the seller should start preparing for the release. - &#x60;AWAITING_SHIPMENT&#x60;: The order is ready to be shipped, but no items have been shipped yet. - &#x60;PARTIALLY_SHIPPING&#x60;: Some items in the order have been shipped, but not all. - &#x60;AWAITING_COLLECTION&#x60;: Shipping has been arranged, but the package is waiting to be collected by the carrier. - &#x60;IN_TRANSIT&#x60;: The package has been collected by the carrier and delivery is in progress. - &#x60;DELIVERED&#x60;: The package has been delivered to the buyer. - &#x60;COMPLETED&#x60;: The order has been completed, and no further returns or refunds are allowed. - &#x60;CANCELLED&#x60;: The order has been cancelled.
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public GetOrderListResponseDataOrders trackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * Tracking number. Available after the package has been shipped.
   * @return trackingNumber
   */
  @javax.annotation.Nullable
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }


  public GetOrderListResponseDataOrders ttsSlaTime(@javax.annotation.Nullable Long ttsSlaTime) {
    this.ttsSlaTime = ttsSlaTime;
    return this;
  }

  /**
   * The latest collection time specified by the platform. Unix timestamp.
   * @return ttsSlaTime
   */
  @javax.annotation.Nullable
  public Long getTtsSlaTime() {
    return ttsSlaTime;
  }

  public void setTtsSlaTime(@javax.annotation.Nullable Long ttsSlaTime) {
    this.ttsSlaTime = ttsSlaTime;
  }


  public GetOrderListResponseDataOrders updateTime(@javax.annotation.Nullable Long updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * Time of order status change. Unix timestamp.
   * @return updateTime
   */
  @javax.annotation.Nullable
  public Long getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(@javax.annotation.Nullable Long updateTime) {
    this.updateTime = updateTime;
  }


  public GetOrderListResponseDataOrders userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Buyer user ID.
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public GetOrderListResponseDataOrders warehouseId(@javax.annotation.Nullable String warehouseId) {
    this.warehouseId = warehouseId;
    return this;
  }

  /**
   * Seller warehouse ID.
   * @return warehouseId
   */
  @javax.annotation.Nullable
  public String getWarehouseId() {
    return warehouseId;
  }

  public void setWarehouseId(@javax.annotation.Nullable String warehouseId) {
    this.warehouseId = warehouseId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GetOrderListResponseDataOrders instance itself
   */
  public GetOrderListResponseDataOrders putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetOrderListResponseDataOrders order202309GetOrderListResponseDataOrders = (GetOrderListResponseDataOrders) o;
    return Objects.equals(this.autoCombineGroupId, order202309GetOrderListResponseDataOrders.autoCombineGroupId) &&
        Objects.equals(this.buyerEmail, order202309GetOrderListResponseDataOrders.buyerEmail) &&
        Objects.equals(this.buyerMessage, order202309GetOrderListResponseDataOrders.buyerMessage) &&
        Objects.equals(this.cancelOrderSlaTime, order202309GetOrderListResponseDataOrders.cancelOrderSlaTime) &&
        Objects.equals(this.cancelReason, order202309GetOrderListResponseDataOrders.cancelReason) &&
        Objects.equals(this.cancelTime, order202309GetOrderListResponseDataOrders.cancelTime) &&
        Objects.equals(this.cancellationInitiator, order202309GetOrderListResponseDataOrders.cancellationInitiator) &&
        Objects.equals(this.collectionDueTime, order202309GetOrderListResponseDataOrders.collectionDueTime) &&
        Objects.equals(this.collectionTime, order202309GetOrderListResponseDataOrders.collectionTime) &&
        Objects.equals(this.commercePlatform, order202309GetOrderListResponseDataOrders.commercePlatform) &&
        Objects.equals(this.consultationId, order202309GetOrderListResponseDataOrders.consultationId) &&
        Objects.equals(this.cpf, order202309GetOrderListResponseDataOrders.cpf) &&
        Objects.equals(this.cpfName, order202309GetOrderListResponseDataOrders.cpfName) &&
        Objects.equals(this.createTime, order202309GetOrderListResponseDataOrders.createTime) &&
        Objects.equals(this.deliveryDueTime, order202309GetOrderListResponseDataOrders.deliveryDueTime) &&
        Objects.equals(this.deliveryOptionId, order202309GetOrderListResponseDataOrders.deliveryOptionId) &&
        Objects.equals(this.deliveryOptionName, order202309GetOrderListResponseDataOrders.deliveryOptionName) &&
        Objects.equals(this.deliveryOptionRequiredDeliveryTime, order202309GetOrderListResponseDataOrders.deliveryOptionRequiredDeliveryTime) &&
        Objects.equals(this.deliverySlaTime, order202309GetOrderListResponseDataOrders.deliverySlaTime) &&
        Objects.equals(this.deliveryTime, order202309GetOrderListResponseDataOrders.deliveryTime) &&
        Objects.equals(this.deliveryType, order202309GetOrderListResponseDataOrders.deliveryType) &&
        Objects.equals(this.exchangeSourceOrderId, order202309GetOrderListResponseDataOrders.exchangeSourceOrderId) &&
        Objects.equals(this.fastDeliveryProgram, order202309GetOrderListResponseDataOrders.fastDeliveryProgram) &&
        Objects.equals(this.fastDispatchSlaTime, order202309GetOrderListResponseDataOrders.fastDispatchSlaTime) &&
        Objects.equals(this.fulfillmentPriorityLevel, order202309GetOrderListResponseDataOrders.fulfillmentPriorityLevel) &&
        Objects.equals(this.fulfillmentType, order202309GetOrderListResponseDataOrders.fulfillmentType) &&
        Objects.equals(this.handlingDuration, order202309GetOrderListResponseDataOrders.handlingDuration) &&
        Objects.equals(this.hasUpdatedRecipientAddress, order202309GetOrderListResponseDataOrders.hasUpdatedRecipientAddress) &&
        Objects.equals(this.id, order202309GetOrderListResponseDataOrders.id) &&
        Objects.equals(this.isBuyerRequestCancel, order202309GetOrderListResponseDataOrders.isBuyerRequestCancel) &&
        Objects.equals(this.isCod, order202309GetOrderListResponseDataOrders.isCod) &&
        Objects.equals(this.isExchangeOrder, order202309GetOrderListResponseDataOrders.isExchangeOrder) &&
        Objects.equals(this.isOnHoldOrder, order202309GetOrderListResponseDataOrders.isOnHoldOrder) &&
        Objects.equals(this.isReplacementOrder, order202309GetOrderListResponseDataOrders.isReplacementOrder) &&
        Objects.equals(this.isSampleOrder, order202309GetOrderListResponseDataOrders.isSampleOrder) &&
        Objects.equals(this.lineItems, order202309GetOrderListResponseDataOrders.lineItems) &&
        Objects.equals(this.needUploadInvoice, order202309GetOrderListResponseDataOrders.needUploadInvoice) &&
        Objects.equals(this.orderType, order202309GetOrderListResponseDataOrders.orderType) &&
        Objects.equals(this.packages, order202309GetOrderListResponseDataOrders.packages) &&
        Objects.equals(this.paidTime, order202309GetOrderListResponseDataOrders.paidTime) &&
        Objects.equals(this.payment, order202309GetOrderListResponseDataOrders.payment) &&
        Objects.equals(this.paymentMethodName, order202309GetOrderListResponseDataOrders.paymentMethodName) &&
        Objects.equals(this.pickUpCutOffTime, order202309GetOrderListResponseDataOrders.pickUpCutOffTime) &&
        Objects.equals(this.recipientAddress, order202309GetOrderListResponseDataOrders.recipientAddress) &&
        Objects.equals(this.recommendedShippingTime, order202309GetOrderListResponseDataOrders.recommendedShippingTime) &&
        Objects.equals(this.releaseDate, order202309GetOrderListResponseDataOrders.releaseDate) &&
        Objects.equals(this.replacedOrderId, order202309GetOrderListResponseDataOrders.replacedOrderId) &&
        Objects.equals(this.requestCancelTime, order202309GetOrderListResponseDataOrders.requestCancelTime) &&
        Objects.equals(this.rtsSlaTime, order202309GetOrderListResponseDataOrders.rtsSlaTime) &&
        Objects.equals(this.rtsTime, order202309GetOrderListResponseDataOrders.rtsTime) &&
        Objects.equals(this.sellerNote, order202309GetOrderListResponseDataOrders.sellerNote) &&
        Objects.equals(this.shippingDueTime, order202309GetOrderListResponseDataOrders.shippingDueTime) &&
        Objects.equals(this.shippingProvider, order202309GetOrderListResponseDataOrders.shippingProvider) &&
        Objects.equals(this.shippingProviderId, order202309GetOrderListResponseDataOrders.shippingProviderId) &&
        Objects.equals(this.shippingType, order202309GetOrderListResponseDataOrders.shippingType) &&
        Objects.equals(this.splitOrCombineTag, order202309GetOrderListResponseDataOrders.splitOrCombineTag) &&
        Objects.equals(this.status, order202309GetOrderListResponseDataOrders.status) &&
        Objects.equals(this.trackingNumber, order202309GetOrderListResponseDataOrders.trackingNumber) &&
        Objects.equals(this.ttsSlaTime, order202309GetOrderListResponseDataOrders.ttsSlaTime) &&
        Objects.equals(this.updateTime, order202309GetOrderListResponseDataOrders.updateTime) &&
        Objects.equals(this.userId, order202309GetOrderListResponseDataOrders.userId) &&
        Objects.equals(this.warehouseId, order202309GetOrderListResponseDataOrders.warehouseId)&&
        Objects.equals(this.additionalProperties, order202309GetOrderListResponseDataOrders.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoCombineGroupId, buyerEmail, buyerMessage, cancelOrderSlaTime, cancelReason, cancelTime, cancellationInitiator, collectionDueTime, collectionTime, commercePlatform, consultationId, cpf, cpfName, createTime, deliveryDueTime, deliveryOptionId, deliveryOptionName, deliveryOptionRequiredDeliveryTime, deliverySlaTime, deliveryTime, deliveryType, exchangeSourceOrderId, fastDeliveryProgram, fastDispatchSlaTime, fulfillmentPriorityLevel, fulfillmentType, handlingDuration, hasUpdatedRecipientAddress, id, isBuyerRequestCancel, isCod, isExchangeOrder, isOnHoldOrder, isReplacementOrder, isSampleOrder, lineItems, needUploadInvoice, orderType, packages, paidTime, payment, paymentMethodName, pickUpCutOffTime, recipientAddress, recommendedShippingTime, releaseDate, replacedOrderId, requestCancelTime, rtsSlaTime, rtsTime, sellerNote, shippingDueTime, shippingProvider, shippingProviderId, shippingType, splitOrCombineTag, status, trackingNumber, ttsSlaTime, updateTime, userId, warehouseId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetOrderListResponseDataOrders {\n");
    sb.append("    autoCombineGroupId: ").append(toIndentedString(autoCombineGroupId)).append("\n");
    sb.append("    buyerEmail: ").append(toIndentedString(buyerEmail)).append("\n");
    sb.append("    buyerMessage: ").append(toIndentedString(buyerMessage)).append("\n");
    sb.append("    cancelOrderSlaTime: ").append(toIndentedString(cancelOrderSlaTime)).append("\n");
    sb.append("    cancelReason: ").append(toIndentedString(cancelReason)).append("\n");
    sb.append("    cancelTime: ").append(toIndentedString(cancelTime)).append("\n");
    sb.append("    cancellationInitiator: ").append(toIndentedString(cancellationInitiator)).append("\n");
    sb.append("    collectionDueTime: ").append(toIndentedString(collectionDueTime)).append("\n");
    sb.append("    collectionTime: ").append(toIndentedString(collectionTime)).append("\n");
    sb.append("    commercePlatform: ").append(toIndentedString(commercePlatform)).append("\n");
    sb.append("    consultationId: ").append(toIndentedString(consultationId)).append("\n");
    sb.append("    cpf: ").append(toIndentedString(cpf)).append("\n");
    sb.append("    cpfName: ").append(toIndentedString(cpfName)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    deliveryDueTime: ").append(toIndentedString(deliveryDueTime)).append("\n");
    sb.append("    deliveryOptionId: ").append(toIndentedString(deliveryOptionId)).append("\n");
    sb.append("    deliveryOptionName: ").append(toIndentedString(deliveryOptionName)).append("\n");
    sb.append("    deliveryOptionRequiredDeliveryTime: ").append(toIndentedString(deliveryOptionRequiredDeliveryTime)).append("\n");
    sb.append("    deliverySlaTime: ").append(toIndentedString(deliverySlaTime)).append("\n");
    sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    exchangeSourceOrderId: ").append(toIndentedString(exchangeSourceOrderId)).append("\n");
    sb.append("    fastDeliveryProgram: ").append(toIndentedString(fastDeliveryProgram)).append("\n");
    sb.append("    fastDispatchSlaTime: ").append(toIndentedString(fastDispatchSlaTime)).append("\n");
    sb.append("    fulfillmentPriorityLevel: ").append(toIndentedString(fulfillmentPriorityLevel)).append("\n");
    sb.append("    fulfillmentType: ").append(toIndentedString(fulfillmentType)).append("\n");
    sb.append("    handlingDuration: ").append(toIndentedString(handlingDuration)).append("\n");
    sb.append("    hasUpdatedRecipientAddress: ").append(toIndentedString(hasUpdatedRecipientAddress)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isBuyerRequestCancel: ").append(toIndentedString(isBuyerRequestCancel)).append("\n");
    sb.append("    isCod: ").append(toIndentedString(isCod)).append("\n");
    sb.append("    isExchangeOrder: ").append(toIndentedString(isExchangeOrder)).append("\n");
    sb.append("    isOnHoldOrder: ").append(toIndentedString(isOnHoldOrder)).append("\n");
    sb.append("    isReplacementOrder: ").append(toIndentedString(isReplacementOrder)).append("\n");
    sb.append("    isSampleOrder: ").append(toIndentedString(isSampleOrder)).append("\n");
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("    needUploadInvoice: ").append(toIndentedString(needUploadInvoice)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("    paidTime: ").append(toIndentedString(paidTime)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    paymentMethodName: ").append(toIndentedString(paymentMethodName)).append("\n");
    sb.append("    pickUpCutOffTime: ").append(toIndentedString(pickUpCutOffTime)).append("\n");
    sb.append("    recipientAddress: ").append(toIndentedString(recipientAddress)).append("\n");
    sb.append("    recommendedShippingTime: ").append(toIndentedString(recommendedShippingTime)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    replacedOrderId: ").append(toIndentedString(replacedOrderId)).append("\n");
    sb.append("    requestCancelTime: ").append(toIndentedString(requestCancelTime)).append("\n");
    sb.append("    rtsSlaTime: ").append(toIndentedString(rtsSlaTime)).append("\n");
    sb.append("    rtsTime: ").append(toIndentedString(rtsTime)).append("\n");
    sb.append("    sellerNote: ").append(toIndentedString(sellerNote)).append("\n");
    sb.append("    shippingDueTime: ").append(toIndentedString(shippingDueTime)).append("\n");
    sb.append("    shippingProvider: ").append(toIndentedString(shippingProvider)).append("\n");
    sb.append("    shippingProviderId: ").append(toIndentedString(shippingProviderId)).append("\n");
    sb.append("    shippingType: ").append(toIndentedString(shippingType)).append("\n");
    sb.append("    splitOrCombineTag: ").append(toIndentedString(splitOrCombineTag)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    ttsSlaTime: ").append(toIndentedString(ttsSlaTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    warehouseId: ").append(toIndentedString(warehouseId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("auto_combine_group_id", "buyer_email", "buyer_message", "cancel_order_sla_time", "cancel_reason", "cancel_time", "cancellation_initiator", "collection_due_time", "collection_time", "commerce_platform", "consultation_id", "cpf", "cpf_name", "create_time", "delivery_due_time", "delivery_option_id", "delivery_option_name", "delivery_option_required_delivery_time", "delivery_sla_time", "delivery_time", "delivery_type", "exchange_source_order_id", "fast_delivery_program", "fast_dispatch_sla_time", "fulfillment_priority_level", "fulfillment_type", "handling_duration", "has_updated_recipient_address", "id", "is_buyer_request_cancel", "is_cod", "is_exchange_order", "is_on_hold_order", "is_replacement_order", "is_sample_order", "line_items", "need_upload_invoice", "order_type", "packages", "paid_time", "payment", "payment_method_name", "pick_up_cut_off_time", "recipient_address", "recommended_shipping_time", "release_date", "replaced_order_id", "request_cancel_time", "rts_sla_time", "rts_time", "seller_note", "shipping_due_time", "shipping_provider", "shipping_provider_id", "shipping_type", "split_or_combine_tag", "status", "tracking_number", "tts_sla_time", "update_time", "user_id", "warehouse_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetOrderListResponseDataOrders
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetOrderListResponseDataOrders.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetOrderListResponseDataOrders is not found in the empty JSON string", GetOrderListResponseDataOrders.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("auto_combine_group_id") != null && !jsonObj.get("auto_combine_group_id").isJsonNull()) && !jsonObj.get("auto_combine_group_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `auto_combine_group_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auto_combine_group_id").toString()));
      }
      if ((jsonObj.get("buyer_email") != null && !jsonObj.get("buyer_email").isJsonNull()) && !jsonObj.get("buyer_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buyer_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyer_email").toString()));
      }
      if ((jsonObj.get("buyer_message") != null && !jsonObj.get("buyer_message").isJsonNull()) && !jsonObj.get("buyer_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buyer_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyer_message").toString()));
      }
      if ((jsonObj.get("cancel_reason") != null && !jsonObj.get("cancel_reason").isJsonNull()) && !jsonObj.get("cancel_reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cancel_reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancel_reason").toString()));
      }
      if ((jsonObj.get("cancellation_initiator") != null && !jsonObj.get("cancellation_initiator").isJsonNull()) && !jsonObj.get("cancellation_initiator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cancellation_initiator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancellation_initiator").toString()));
      }
      if ((jsonObj.get("commerce_platform") != null && !jsonObj.get("commerce_platform").isJsonNull()) && !jsonObj.get("commerce_platform").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `commerce_platform` to be a primitive type in the JSON string but got `%s`", jsonObj.get("commerce_platform").toString()));
      }
      if ((jsonObj.get("consultation_id") != null && !jsonObj.get("consultation_id").isJsonNull()) && !jsonObj.get("consultation_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `consultation_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("consultation_id").toString()));
      }
      if ((jsonObj.get("cpf") != null && !jsonObj.get("cpf").isJsonNull()) && !jsonObj.get("cpf").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cpf` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cpf").toString()));
      }
      if ((jsonObj.get("cpf_name") != null && !jsonObj.get("cpf_name").isJsonNull()) && !jsonObj.get("cpf_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cpf_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cpf_name").toString()));
      }
      if ((jsonObj.get("delivery_option_id") != null && !jsonObj.get("delivery_option_id").isJsonNull()) && !jsonObj.get("delivery_option_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_option_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_option_id").toString()));
      }
      if ((jsonObj.get("delivery_option_name") != null && !jsonObj.get("delivery_option_name").isJsonNull()) && !jsonObj.get("delivery_option_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_option_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_option_name").toString()));
      }
      if ((jsonObj.get("delivery_type") != null && !jsonObj.get("delivery_type").isJsonNull()) && !jsonObj.get("delivery_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_type").toString()));
      }
      if ((jsonObj.get("exchange_source_order_id") != null && !jsonObj.get("exchange_source_order_id").isJsonNull()) && !jsonObj.get("exchange_source_order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `exchange_source_order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("exchange_source_order_id").toString()));
      }
      if ((jsonObj.get("fast_delivery_program") != null && !jsonObj.get("fast_delivery_program").isJsonNull()) && !jsonObj.get("fast_delivery_program").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fast_delivery_program` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fast_delivery_program").toString()));
      }
      if ((jsonObj.get("fulfillment_type") != null && !jsonObj.get("fulfillment_type").isJsonNull()) && !jsonObj.get("fulfillment_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fulfillment_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fulfillment_type").toString()));
      }
      // validate the optional field `handling_duration`
      if (jsonObj.get("handling_duration") != null && !jsonObj.get("handling_duration").isJsonNull()) {
        GetOrderListResponseDataOrdersHandlingDuration.validateJsonElement(jsonObj.get("handling_duration"));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (jsonObj.get("line_items") != null && !jsonObj.get("line_items").isJsonNull()) {
        JsonArray jsonArraylineItems = jsonObj.getAsJsonArray("line_items");
        if (jsonArraylineItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("line_items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `line_items` to be an array in the JSON string but got `%s`", jsonObj.get("line_items").toString()));
          }

          // validate the optional field `line_items` (array)
          for (int i = 0; i < jsonArraylineItems.size(); i++) {
            GetOrderListResponseDataOrdersLineItems.validateJsonElement(jsonArraylineItems.get(i));
          };
        }
      }
      if ((jsonObj.get("need_upload_invoice") != null && !jsonObj.get("need_upload_invoice").isJsonNull()) && !jsonObj.get("need_upload_invoice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `need_upload_invoice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("need_upload_invoice").toString()));
      }
      if ((jsonObj.get("order_type") != null && !jsonObj.get("order_type").isJsonNull()) && !jsonObj.get("order_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `order_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_type").toString()));
      }
      if (jsonObj.get("packages") != null && !jsonObj.get("packages").isJsonNull()) {
        JsonArray jsonArraypackages = jsonObj.getAsJsonArray("packages");
        if (jsonArraypackages != null) {
          // ensure the json data is an array
          if (!jsonObj.get("packages").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `packages` to be an array in the JSON string but got `%s`", jsonObj.get("packages").toString()));
          }

          // validate the optional field `packages` (array)
          for (int i = 0; i < jsonArraypackages.size(); i++) {
            GetOrderListResponseDataOrdersPackages.validateJsonElement(jsonArraypackages.get(i));
          };
        }
      }
      // validate the optional field `payment`
      if (jsonObj.get("payment") != null && !jsonObj.get("payment").isJsonNull()) {
        GetOrderListResponseDataOrdersPayment.validateJsonElement(jsonObj.get("payment"));
      }
      if ((jsonObj.get("payment_method_name") != null && !jsonObj.get("payment_method_name").isJsonNull()) && !jsonObj.get("payment_method_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payment_method_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_method_name").toString()));
      }
      // validate the optional field `recipient_address`
      if (jsonObj.get("recipient_address") != null && !jsonObj.get("recipient_address").isJsonNull()) {
        GetOrderListResponseDataOrdersRecipientAddress.validateJsonElement(jsonObj.get("recipient_address"));
      }
      if ((jsonObj.get("replaced_order_id") != null && !jsonObj.get("replaced_order_id").isJsonNull()) && !jsonObj.get("replaced_order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `replaced_order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("replaced_order_id").toString()));
      }
      if ((jsonObj.get("seller_note") != null && !jsonObj.get("seller_note").isJsonNull()) && !jsonObj.get("seller_note").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `seller_note` to be a primitive type in the JSON string but got `%s`", jsonObj.get("seller_note").toString()));
      }
      if ((jsonObj.get("shipping_provider") != null && !jsonObj.get("shipping_provider").isJsonNull()) && !jsonObj.get("shipping_provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipping_provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipping_provider").toString()));
      }
      if ((jsonObj.get("shipping_provider_id") != null && !jsonObj.get("shipping_provider_id").isJsonNull()) && !jsonObj.get("shipping_provider_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipping_provider_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipping_provider_id").toString()));
      }
      if ((jsonObj.get("shipping_type") != null && !jsonObj.get("shipping_type").isJsonNull()) && !jsonObj.get("shipping_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipping_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipping_type").toString()));
      }
      if ((jsonObj.get("split_or_combine_tag") != null && !jsonObj.get("split_or_combine_tag").isJsonNull()) && !jsonObj.get("split_or_combine_tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `split_or_combine_tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("split_or_combine_tag").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("tracking_number") != null && !jsonObj.get("tracking_number").isJsonNull()) && !jsonObj.get("tracking_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tracking_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tracking_number").toString()));
      }
      if ((jsonObj.get("user_id") != null && !jsonObj.get("user_id").isJsonNull()) && !jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
      if ((jsonObj.get("warehouse_id") != null && !jsonObj.get("warehouse_id").isJsonNull()) && !jsonObj.get("warehouse_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `warehouse_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("warehouse_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetOrderListResponseDataOrders.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetOrderListResponseDataOrders' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetOrderListResponseDataOrders> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetOrderListResponseDataOrders.class));

       return (TypeAdapter<T>) new TypeAdapter<GetOrderListResponseDataOrders>() {
           @Override
           public void write(JsonWriter out, GetOrderListResponseDataOrders value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GetOrderListResponseDataOrders read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GetOrderListResponseDataOrders instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetOrderListResponseDataOrders given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetOrderListResponseDataOrders
   * @throws IOException if the JSON string is invalid with respect to GetOrderListResponseDataOrders
   */
  public static GetOrderListResponseDataOrders fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetOrderListResponseDataOrders.class);
  }

  /**
   * Convert an instance of GetOrderListResponseDataOrders to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

