/*
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tiktokshop.open.sdk_java.model.Promotion.V202309;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import tiktokshop.open.sdk_java.model.Promotion.V202309.SearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tiktokshop.open.sdk_java.invoke.JSON;

/**
 * SearchActivitiesResponseDataActivitiesDiscountGiftDiscount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-28T03:28:06.328409Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class SearchActivitiesResponseDataActivitiesDiscountGiftDiscount {
  public static final String SERIALIZED_NAME_GIFT_INFOS = "gift_infos";
  @SerializedName(SERIALIZED_NAME_GIFT_INFOS)
  @javax.annotation.Nullable
  private List<SearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos> giftInfos = new ArrayList<>();

  public static final String SERIALIZED_NAME_GIFT_RECEIVING_TYPE = "gift_receiving_type";
  @SerializedName(SERIALIZED_NAME_GIFT_RECEIVING_TYPE)
  @javax.annotation.Nullable
  private String giftReceivingType;

  public SearchActivitiesResponseDataActivitiesDiscountGiftDiscount() {
  }

  public SearchActivitiesResponseDataActivitiesDiscountGiftDiscount giftInfos(@javax.annotation.Nullable List<SearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos> giftInfos) {
    this.giftInfos = giftInfos;
    return this;
  }

  public SearchActivitiesResponseDataActivitiesDiscountGiftDiscount addGiftInfosItem(SearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos giftInfosItem) {
    if (this.giftInfos == null) {
      this.giftInfos = new ArrayList<>();
    }
    this.giftInfos.add(giftInfosItem);
    return this;
  }

  /**
   * Configurations regarding Gift With Purchase (GWP) promotions.  A maximum of two &#x60;tier&#x60;s are permitted in SEA and UK. Only one &#x60;tier&#x60; is permitted in US. And &#x60;threshold_type&#x60; must be the same across all &#x60;tier&#x60;s. 
   * @return giftInfos
   */
  @javax.annotation.Nullable
  public List<SearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos> getGiftInfos() {
    return giftInfos;
  }

  public void setGiftInfos(@javax.annotation.Nullable List<SearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos> giftInfos) {
    this.giftInfos = giftInfos;
  }


  public SearchActivitiesResponseDataActivitiesDiscountGiftDiscount giftReceivingType(@javax.annotation.Nullable String giftReceivingType) {
    this.giftReceivingType = giftReceivingType;
    return this;
  }

  /**
   * The receiving type of gift. Currently only supports one type: &#x60;ALL_RECEIVE&#x60; -&#x60;ALL_RECEIVE&#x60;: All gifts configured in the promotion can be collected.
   * @return giftReceivingType
   */
  @javax.annotation.Nullable
  public String getGiftReceivingType() {
    return giftReceivingType;
  }

  public void setGiftReceivingType(@javax.annotation.Nullable String giftReceivingType) {
    this.giftReceivingType = giftReceivingType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SearchActivitiesResponseDataActivitiesDiscountGiftDiscount instance itself
   */
  public SearchActivitiesResponseDataActivitiesDiscountGiftDiscount putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchActivitiesResponseDataActivitiesDiscountGiftDiscount promotion202309SearchActivitiesResponseDataActivitiesDiscountGiftDiscount = (SearchActivitiesResponseDataActivitiesDiscountGiftDiscount) o;
    return Objects.equals(this.giftInfos, promotion202309SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.giftInfos) &&
        Objects.equals(this.giftReceivingType, promotion202309SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.giftReceivingType)&&
        Objects.equals(this.additionalProperties, promotion202309SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(giftInfos, giftReceivingType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchActivitiesResponseDataActivitiesDiscountGiftDiscount {\n");
    sb.append("    giftInfos: ").append(toIndentedString(giftInfos)).append("\n");
    sb.append("    giftReceivingType: ").append(toIndentedString(giftReceivingType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("gift_infos", "gift_receiving_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchActivitiesResponseDataActivitiesDiscountGiftDiscount
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchActivitiesResponseDataActivitiesDiscountGiftDiscount is not found in the empty JSON string", SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("gift_infos") != null && !jsonObj.get("gift_infos").isJsonNull()) {
        JsonArray jsonArraygiftInfos = jsonObj.getAsJsonArray("gift_infos");
        if (jsonArraygiftInfos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("gift_infos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `gift_infos` to be an array in the JSON string but got `%s`", jsonObj.get("gift_infos").toString()));
          }

          // validate the optional field `gift_infos` (array)
          for (int i = 0; i < jsonArraygiftInfos.size(); i++) {
            SearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos.validateJsonElement(jsonArraygiftInfos.get(i));
          };
        }
      }
      if ((jsonObj.get("gift_receiving_type") != null && !jsonObj.get("gift_receiving_type").isJsonNull()) && !jsonObj.get("gift_receiving_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gift_receiving_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gift_receiving_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchActivitiesResponseDataActivitiesDiscountGiftDiscount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchActivitiesResponseDataActivitiesDiscountGiftDiscount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchActivitiesResponseDataActivitiesDiscountGiftDiscount>() {
           @Override
           public void write(JsonWriter out, SearchActivitiesResponseDataActivitiesDiscountGiftDiscount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchActivitiesResponseDataActivitiesDiscountGiftDiscount read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SearchActivitiesResponseDataActivitiesDiscountGiftDiscount instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchActivitiesResponseDataActivitiesDiscountGiftDiscount given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchActivitiesResponseDataActivitiesDiscountGiftDiscount
   * @throws IOException if the JSON string is invalid with respect to SearchActivitiesResponseDataActivitiesDiscountGiftDiscount
   */
  public static SearchActivitiesResponseDataActivitiesDiscountGiftDiscount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchActivitiesResponseDataActivitiesDiscountGiftDiscount.class);
  }

  /**
   * Convert an instance of SearchActivitiesResponseDataActivitiesDiscountGiftDiscount to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

