CREATE TABLE IF NOT EXISTS `mas_skill_def` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `skill_code` varchar(128) NOT NULL COMMENT '技能唯一编码',
  `name` varchar(128) NOT NULL COMMENT '技能名称',
  `description` varchar(512) DEFAULT NULL COMMENT '技能描述',
  `icon` varchar(255) DEFAULT NULL COMMENT '技能图标 url',
  `use_case_tags` varchar(255) DEFAULT NULL COMMENT '适用场景标签',
  `strategy_instruction` text COMMENT '策略指导书',
  `required_tools` varchar(1024) DEFAULT NULL COMMENT '允许使用的工具集 json',
  `param_schema` text COMMENT '技能参数定义 schema json',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_code` (`skill_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MAS 技能定义表';

CREATE TABLE IF NOT EXISTS `mas_task_skill_rel` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `task_id` bigint NOT NULL COMMENT '关联的 mas_task_job 的 ID',
  `skill_code` varchar(128) NOT NULL COMMENT '应用的技能编码',
  `target_biz_id` varchar(128) NOT NULL COMMENT '目标业务对象的唯一标识',
  `target_biz_name` varchar(255) DEFAULT NULL COMMENT '目标业务对象的名称',
  `config_params` text COMMENT '用户配置的运行参数 JSON',
  `current_stage` varchar(255) DEFAULT NULL COMMENT '当前进度或状态文本',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MAS 任务与技能绑定关系表';

INSERT INTO mas_skill_def (skill_code, name, description, icon, use_case_tags, strategy_instruction, required_tools, param_schema) VALUES
('NEW_PRODUCT_LAUNCH_V1', '「火箭飙升」冷启动全案', '专为新品打造的 30 天自动出价与拓词策略，包含基础搭建、引流、否定清洗到最终利润优化的完整周期。', 'Lightning', '新品期, 流量冷启', '{"summary": {"description": "一套专为新品期打造的全自动起量策略，通过精细化长尾词打法，在安全阈值下平稳渡过冷启动。", "phases": [{"name": "Phase 1: 基础设施搭建 (Day 1)", "description": "自动创建 Auto 广告活动及精准核心词 Campaign，设置低预算启动探测"},{"name": "Phase 2: 广泛流量试探 (Day 2-5)", "description": "开启 Auto 广泛匹配，提升曝光，每日记录高点击词干"},{"name": "Phase 3: 恶劣流量清洗 (Day 6-10)", "description": "分析过去7天数据，将点击大于10次但0转化的词自动加入否定池"},{"name": "Phase 4: 长尾词提炼转化 (Day 11-20)", "description": "将出单且 ACOS 低于基准值的 Search Term 提取并开启精确匹配"},{"name": "Phase 5: 预算倾斜与聚焦 (Day 21-30)", "description": "将 80% 的预算转移到表现优异的精确 Campaign，关停低效的探索活动"}]}, "strategy": "This is the full markdown of the NEW_PRODUCT_LAUNCH_V1 skill..."}', '["AD_SP_API", "KEYWORD_SUGGESTION", "BUDGET_OPTIMIZER"]', '{"targetAcos": { "type": "number", "label": "预期稳定 ACOS (%)", "required": true }, "totalAutoBudget": { "type": "number", "label": "冷启总预算 ($)", "required": true }}'),
('SEASONAL_RUSH_V1', '「旺季抢位」防守反击', '针对黑五网一等旺季的高频波动，高频次监控竞争加剧导致的排名下降，自动进行防守调价与时段放量。', 'DataLine', '旺季爆单, 排名卡位', '{"summary": {"description": "应对特殊大促场景，依靠高频执行策略确保核心金刚词不下榜，保障旺季产出最大化。", "phases": [{"name": "Phase 1: 关键身位锚定", "description": "记录大促前 3 天的主力出单词的自然排名与广告坑位作为防守基准"},{"name": "Phase 2: 高频时段监控", "description": "大促期间每 1 小时轮询一次排名，若掉出首页立发告警事件"},{"name": "Phase 3: 阶梯出价防御", "description": "排名下跌时，按照 10%, 20%, 30% 幅度阶梯尝试抬高 Bid 进行反抢"},{"name": "Phase 4: 竞争对手断货探测", "description": "扫描竞品的库存异动，在对手断货时立刻加码抢夺空出的流量份额"},{"name": "Phase 5: 破防阈值熔断", "description": "若 Bid 上升至极值且 ACOS 超过熔断线 2 次以上，则退守次要位置止损"},{"name": "Phase 6: 大促长尾平切", "description": "大促结束后 48 小时，将所有激进 Bid 恢复至大促前水位"}]}, "strategy": "This is the full markdown of the SEASONAL_RUSH_V1 skill..."}', '["AD_RANK_API", "COMPETITOR_ASIN_ANALYSIS"]', '{"maxCpc": { "type": "number", "label": "单次点击断头台 ($)", "required": true }, "baselineRoas": { "type": "number", "label": "防守容忍底线 ROAS", "required": true }}'),
('CLEARANCE_V1', '「库容卫士」智能清仓', '联动降价打折机制与清仓广告放量，在最短周期内释放冗余库存压力，挽回安全库存分数和现金流。', 'ShoppingCart', '降备抛售, 现金流恢复', '{"summary": {"description": "依据库龄和动销率测算出的最优清仓策略，在亏损最小化的前提下加速周转。", "phases": [{"name": "Phase 1: 库龄水位分析", "description": "扫描 ASIN 超过 180 天的库存比例及仓储超龄费预估"},{"name": "Phase 2: 阶梯折扣计算", "description": "结合当前动销速率与目标清空日期，倒推所需的折扣力度 (e.g. 15% -> 30%)"},{"name": "Phase 3: 清仓引流拉升", "description": "新建高曝光、低转化门槛的粗犷泛匹配广告，全面铺开入口"},{"name": "Phase 4: 动态流速校验", "description": "跟踪开启后的每日动销 (Velocity)，若未达标则触发下一级降价"},{"name": "Phase 5: 清空与复盘", "description": "库存低于 20 件时自动终止清仓程序，生成本次清仓资产损失核算简报"}]}, "strategy": "This is the full markdown of the CLEARANCE_V1 skill..."}', '["INVENTORY_API", "COUPON_API", "PROFIT_CALCULATOR"]', '{"targetClearDate": { "type": "string", "label": "期望清空截止日期 (YYYY-MM-DD)", "required": true }, "lowestPrice": { "type": "number", "label": "底裤承受价 ($)", "required": false }}'),
('AUTO_BID_OPTIMIZATION_V2', '「夜神」分时出价接管', '依据商品不同时段的真实转化率时差，自动进行分时出价管理，避免在低转化深夜时段白烧广告费。', 'Clock', '降本增效, 分时策略', '{"summary": {"description": "针对 Amazon 平台未提供原生分时调价工具的短板，利用定时代理脚本实现的降耗策略。", "phases": [{"name": "Phase 1: 时区地图测算", "description": "获取连续 14 天的逐小时订单发生曲线，绘制时区高峰图"},{"name": "Phase 2: 黄金节点标记", "description": "选出订单量占比最大的连续 6 小时作为重点投放时段 (Prime Time)"},{"name": "Phase 3: 深夜降耗执行", "description": "设定美东时间凌晨 1 点至 早上 7 点为低迷期，自动执行全量 Bid 下调 40%"},{"name": "Phase 4: 晨峰预热反弹", "description": "在黄金时段前 1 小时，提前将广告出价位上抬，进行坑位预热"},{"name": "Phase 5: 转化错觉纠偏", "description": "周度复盘分时出价后的 ACOS 波动，使用强化学习微调下周的时段比例系数"}]}, "strategy": "This is the full markdown of the AUTO_BID_OPTIMIZATION_V2 skill..."}', '["AD_HOURLY_REPORT", "CRON_EXECUTOR"]', '{"timezone": { "type": "string", "label": "参照时区 (默认 PST)", "required": false }, "nightBidDiscount": { "type": "number", "label": "深夜下调幅度 (%)", "required": true }}'),
('KEYWORD_MINER_V1', '「拓词猎手」长尾词挖掘', '针对成熟期商品，利用广泛匹配探索低CPC长尾词，并将优质长尾词推向Exact组。', 'Position', '老品拓词, 流量拓展', '{"summary": {"description": "针对老品流量见顶，开启细颗粒度长尾词探索。", "phases": [{"name": "Phase 1: 弱相关隔离", "description": "计算过去30天高点击低转化的词并加入精准否定"},{"name": "Phase 2: 广泛漏斗开启", "description": "采用低竞价大预算开启 Broad/Phrase 广告组"},{"name": "Phase 3: 词干频率统热", "description": "每 3 天收集一次 Search Terms 里的高频共现词干"},{"name": "Phase 4: 出单长尾提取", "description": "将产生至少 2 单且 ACOS < 30% 的词提取到精确匹配组"},{"name": "Phase 5: 转化闭环验证", "description": "监控精确匹配组中提取词的转化，转化稳定后加预算"}]}, "strategy": "..."}', '["KEYWORD_SUGGESTION", "AD_REPORT_API"]', '{"maxAcosThreshold": { "type": "number", "label": "最高提取 ACOS 阈值 (%)", "required": true }, "explorationBudget": { "type": "number", "label": "探索预算 ($)", "required": true }}'),
('ACOS_SAVER_V1', '「预算刀客」ACOS急救', '当ACOS突然爆表时触发，紧急压低无效点击词，释放被占用的无效预算，恢复整体投产比。', 'WarnTriangle', 'ACOS管控, 预算挽救', '{"summary": {"description": "触发式的 ACOS 急救方案，当整体或某活动 ACOS 超过阈值后紧急介入。", "phases": [{"name": "Phase 1: 扫描血包词", "description": "找出账户中花费极高但完全没有转化的词或 ASIN"},{"name": "Phase 2: 紧急降速", "description": "对血包词执行大幅度降价（如降低50% Bid）或直接暂停"},{"name": "Phase 3: 预算再平衡", "description": "将被切断的预算转移给 ACOS 表现良好的盈利词"},{"name": "Phase 4: 断尾观察期", "description": "等待 48 小时归因期，重新审视调整后的整体 ACOS 水平"},{"name": "Phase 5: 常态恢复", "description": "当 ACOS 脱离红线后，退出急救模式，交由常规优化系统"}]}, "strategy": "..."}', '["BUDGET_OPTIMIZER", "AD_SP_API"]', '{"alertAcos": { "type": "number", "label": "报警 ACOS 线 (%)", "required": true }}'),
('AUTO_CAMPAIGN_SPLITTER_V1', '「组别架构师」自动拆组', '由于单一Campaign预算受限或表现不均，将大流量词自动拆分至独立Campaign，并给予独立预算。', 'Coin', '架构优化, 核心词独立', '{"summary": {"description": "解决大词吸干预算或组内竞争不充分的问题，按转化效果分裂 Campaign。", "phases": [{"name": "Phase 1: 霸权词界定", "description": "识别一个 Campaign 中吞噬超 60% 预算的头部大词"},{"name": "Phase 2: 源组降权隔离", "description": "在原 Campaign 中将大词加入精确否定，切断流量源"},{"name": "Phase 3: 独立战区创建", "description": "为大词单独创建 Exact 匹配的独立 Campaign"},{"name": "Phase 4: 独立预算赋能", "description": "赋予该独立大词充足但不越界的专属预算池"},{"name": "Phase 5: 原组新生观察", "description": "监控原 Campaign 中其他词在失去压制后是否能够出单"}]}, "strategy": "..."}', '["BULK_OPERATION_API"]', '{"budgetSplitRatio": { "type": "number", "label": "新组分配预算比例", "required": false }}'),
('SPONSORED_BRAND_DOMINATOR', '「品牌霸屏」SB广告投放', '在竞争对手发力或品牌活动日期间，通过激进的SBV（视频）与SB（品牌）广告抢占页面头部。', 'VideoCamera', '品牌防御, 主流量口', '{"summary": {"description": "活动期间抢占顶部坑位，依靠视频与集合页优势建立品牌壁垒。", "phases": [{"name": "Phase 1: 竞争词集锁定", "description": "框定行业主词、品牌词及主要竞品核心词"},{"name": "Phase 2: 视频素材就绪", "description": "审核 SBV 等素材状态，确认通过合规审查"},{"name": "Phase 3: 置顶激进出价", "description": "采用 Top of Search 溢价策略，以获取绝对首屏曝光"},{"name": "Phase 4: 防御性护城河", "description": "对自身品牌词建立低价长期防御组，防止对手抢夺品牌词"},{"name": "Phase 5: 归因延迟处理", "description": "品牌广告具有更长的归因周期(14天)，需使用预测模型进行中期评判"},{"name": "Phase 6: 大促后复盘衰减", "description": "活动期结束后平缓下调溢价幅度，稳固获取的长效心智"}]}, "strategy": "..."}', '["SB_API", "SBV_API"]', '{"bidMultiplier": { "type": "number", "label": "出价倍率", "required": true }}'),
('BUDGET_PACING_V2', '「平滑释放」预算均分', '解决预算在上午过早消耗殆尽的问题，将总预算按时段分配，保证全天所有流量高峰期都有预算。', 'DataAnalysis', '预算拉环, 均匀曝光', '{"summary": {"description": "解决预算过快触顶的问题，实现全天候平滑引流。", "phases": [{"name": "Phase 1: 每日消耗轮廓", "description": "描绘过往七天的按小时花费率 (Spend Rate)"},{"name": "Phase 2: 计算理想水温", "description": "将总预算按各时段预期转化率分配到 24 小时节点"},{"name": "Phase 3: 超速踩刹车", "description": "若某时段实际花费远超理想阈值，自动挂起活动以减缓流速"},{"name": "Phase 4: 余量加速", "description": "若临近一日结尾预算仍有富余，则放开竞价获取剩余流量"},{"name": "Phase 5: 异常告警拦截", "description": "防范系统异常导致的瞬时爆量烧空预算，触发硬熔断"}]}, "strategy": "..."}', '["BUDGET_OPTIMIZER", "CRON_EXECUTOR"]', '{"dailyLimit": { "type": "number", "label": "单日预算墙 ($)", "required": true }}'),
('INVENTORY_PROTECTOR_V1', '「断货预警」缓冲降速', '当库存可售天数低于14天时，自动调低所有广告出价，减缓出单速度，避免断货带来权重惩罚。', 'Lock', '断货防御, 库存拉平', '{"summary": {"description": "针对即将断货的 ASIN，强制控速降本，保护 Listing 权重，直到新库存上架。", "phases": [{"name": "Phase 1: 动销天数探测", "description": "拉取 FBA 在库及在途库存，计算安全库存天数(DOI)"},{"name": "Phase 2: 降速线触发", "description": "当 DOI < 15 天时，拉响断货预警，切入防守降速模式"},{"name": "Phase 3: 宽匹配砍光", "description": "立刻暂停所有 Auto/Broad/Phrase 词，仅保留核心精确词"},{"name": "Phase 4: 预算软着陆", "description": "每日阶梯式下调广告总预算 15%，逐步收缩直至停摆"},{"name": "Phase 5: 核心词慢速给氧", "description": "保持主关键词极低的出价，维持底限的转化动作，保持坑位"},{"name": "Phase 6: 到货满血复活", "description": "侦测到新库存成功签收入库后，释放限制，切回冷启动或正常"}]}, "strategy": "..."}', '["INVENTORY_API", "AD_SP_API"]', '{"safeDoi": { "type": "number", "label": "安全动销天数 (默认15)", "required": false }}');
